### ISSUE TITLE
Create EXTERNAL LOCATIONs to map to External Tables (Azure)

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#100]
Related issues:
- https://github.com/databrickslabs/ucx/issues/339
- https://github.com/databrickslabs/ucx/issues/862
- https://github.com/databrickslabs/ucx/issues/338

Jobs to be done:

- use `ExternalLocations` from https://github.com/databrickslabs/ucx/blob/main/src/databricks/labs/ucx/hive_metastore/locations.py and `tables.TablesCrawler` to verify if we have matching external locations configured already - use `ws.external_locations.list()` API for this.
- validate the logic of `ExternalLocations` for correctness and corner-cases
- create `databricks labs ucx validate-external-locations` command to display a number of tables per external location and any HMS table locations that don't belong to an existing external location
- print Terraform resource definitions to have those external locations setup

**Comment by zpappa** [comment]
Needs a PRD

**Comment by pohlposition** [comment]
Relates to 
https://github.com/databrickslabs/ucx/issues/339 (Migrate Azure Service Principals that access storage to UC Storage Credentials)
and
https://github.com/databrickslabs/ucx/issues/338 (Migrate AWS Instance Profile to UC Storage Credentials)

**Comment by zpappa** [comment]
So there's a bit of a catch-22 here.

We can try to force create a credential if it hasn't been set up on the cloud provider, but it may not work and you won't be able to sync tables or create external locations with that credential.

I think what needs to happen here is:

1. We gather information from cloud provider about the credentials and what storage accounts they have access to
2. We produce a report with some commands that a customer can run to create credentials
3. OFFLINE, the customer has to go and create these credentials
- What if they renamed the credentials, potential interactivity or mapping step
- What if they collapsed credentials, potential interactivity or mapping step 
**4. We create credentials in Unity
5. We use the mapping information to register external locations
6. Then we can use storage paths of external tables to map to their containing external locations**
