### ISSUE TITLE
`create-catalogs-schemas` should work for external paths

### ISSUE THREAD

**Issue by william-conti** [databrickslabs/ucx#1039]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

For users that relies on mount points and not on external tables, we should provide to them an easy way to migrate their existing mounts into external tables on UC.

### Proposed Solution

Rely on `ExternalLocations` from https://github.com/databrickslabs/ucx/blob/main/src/databricks/labs/ucx/hive_metastore/locations.py#L32-L213

Similar to the output of create-table-mapping, the user will provide a mapping file where each source path will be mapped to a target external table on UC.
The command will then create catalogs / schemas / tables appropriately.

Related issues:
- https://github.com/databrickslabs/ucx/pull/1028

**Comment by nfx** [comment]
we unfold mount mounts to the actual paths on the external locations

**Comment by nfx** [comment]
see:
https://github.com/databrickslabs/ucx/commit/056c9a1fe36ab940e58c4a024aabf3fbdc907598
https://github.com/databrickslabs/ucx/commit/08d1f5b8e584615e48939514e8dbae6af9f656db

**Comment by JCZuurmond** [comment]
@nfx or @FastLee : For clarification, should the table mapping be extended with user provided external paths?
