### ISSUE TITLE
Verify that metastore has been configured on account

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#104]

**Comment by zpappa** [comment]
Can you clarify what this means please @nfx ?

We should ideally be checking if there is a metastore in region, and in region only to the workspace, not in general if there is one setup.

**Comment by pohlposition** [comment]
Sounds like something that is run during assessment.

If there is no metastore, then indicate in the assessment that the pre-req is not met.

If there is ONE, then we can include it's id in the config file.

It's possible for there to be more than 1 metastore per region, so we would need to ask the user to pick one for this workspace.

**Comment by zpappa** [comment]
Only assign a metastore if it's not already assigned, need a step somewhere to produce insight into whether or not the metastore is assigned for a given workspace.
