### ISSUE TITLE
[FEATURE]: Create Cluster Policy to Prevent Externally Orchestrated Job Failures

### ISSUE THREAD

**Issue by pohlposition** [databrickslabs/ucx#1040]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

When a UC Metastore is attached to a workspace it defaults all new clusters to use a UC supported security mode.

### Proposed Solution

1. Create Cluster Policy for External Orchestrators and set “data_security_mode”: “NONE”
2. Assign Cluster Policy to Service Principals used by the external orchestrators

### Additional Context

The product team is looking at ways to resolve this, but no timeline yet.

go/ddsm

**Comment by nfx** [comment]
apparently, it's not possible. See internal comms.
