### ISSUE TITLE
[FEATURE]: Capture SYNC command failure

### ISSUE THREAD

**Issue by qziyuan** [databrickslabs/ucx#1069]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

When running `SYNC` sql statement, some errors like `LOCATION_OVERLAP` will not fail the statement execution. Instead the statement will be executed successfully with error details in `status_code` and `description` columns in returned query result.

### Proposed Solution

Modify the `StatementExecutionBackend.execute` to return the `ExecuteStatementResponse` so the errors of `SYNC` can be extracted.

**Comment by nfx** [comment]
It’s a bug, not a feature
