### ISSUE TITLE
[BUG]: create account groups using workspace id flag

### ISSUE THREAD

**Issue by mathieupelletier-db** [databrickslabs/ucx#1090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The CLI is not interpreting the workspace_ids specified as a list of integer. Instead it's trying to parse the workspace value as a list of int. 6934690829137754 will be interpreted as list[] = [6,9,3,4,5,9,0,8,2,9,1,3,7,7,5,4] instead of list[] = [6934690829137754].

### Expected Behavior

Groups are synchronized for a specific workspace

### Steps To Reproduce

1. Run the command using workspaces_ids parameter
databricks labs ucx create-account-groups --workspace_ids "6934690829137754"

### Cloud

Azure

### Operating System

Windows

### Version

latest via Databricks CLI

### Relevant log output

```shell
C:\Users\IBCVTLUD>databricks labs ucx create-account-groups --workspace_ids "6934690829137754"

09:46:40  INFO [src/databricks/labs/ucx] Account ID: 0b7be851-285c-46bf-b676-49958ddb2ff6

09:46:44  INFO [d.l.ucx.account] 23 account groups found

09:46:44  INFO [d.l.ucx.account] Workspace id 6 not found on the account

09:46:44  INFO [d.l.ucx.account] Workspace id 9 not found on the account

09:46:44  INFO [d.l.ucx.account] Workspace id 3 not found on the account

09:46:44  INFO [d.l.ucx.account] Workspace id 4 not found on the account

09:46:44  INFO [d.l.ucx.account] Workspace id 6 not found on the account

09:46:44  INFO [d.l.ucx.account] Workspace id 9 not found on the account

09:46:44  INFO [d.l.ucx.account] Workspace id 0 not found on the account

09:46:44  INFO [d.l.ucx.account] Workspace id 8 not found on the account

09:46:44  INFO [d.l.ucx.account] Workspace id 2 not found on the account

09:46:44  INFO [d.l.ucx.account] Workspace id 9 not found on the account

09:46:44  INFO [d.l.ucx.account] Workspace id 1 not found on the account

09:46:44  INFO [d.l.ucx.account] Workspace id 3 not found on the account

09:46:44  INFO [d.l.ucx.account] Workspace id 7 not found on the account

09:46:44  INFO [d.l.ucx.account] Workspace id 7 not found on the account

09:46:44  INFO [d.l.ucx.account] Workspace id 5 not found on the account

09:46:44  INFO [d.l.ucx.account] Workspace id 4 not found on the account

09:46:44 ERROR [src/databricks/labs/ucx.create-account-groups] ValueError: No workspace ids provided in the configuration found in the account
```

**Comment by nfx** [comment]
Thank you for the feature request! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.
