### ISSUE TITLE
[BUG]: UCX Assessment workflow fails with error -- DBFS library installations are not supported on DBR 15 or above.

### ISSUE THREAD

**Issue by rkkalluri** [databrickslabs/ucx#1096]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug
UCX Assessment workflow fails with error 

run failed with error message
 Library installation failed for library due to user error for whl: "dbfs:/Applications/ucx/wheels/databricks_labs_ucx-0.18.0-py3-none-any.whl"
 Error messages:
Library installation attempted on the driver node of cluster 0325-034406-7snc4yap and failed. Please refer to the following error message to fix the library or contact Databricks support. Error Code: DRIVER_LIBRARY_INSTALLATION_FAILURE. Error Message: com.databricks.api.base.DatabricksServiceException: BAD_REQUEST: DBFS library installations are not supported on DBR 15 or above.

I have updated the compute profile generated by the installer to downgrade to 14.3, but I am unable to change the workflow to a 14.3 it keeps complaining that 14.3 is not in the list of 15.0

### Steps to Reproduce

Install UCX with databricks ucx labs install --profile dbx-profile
Run Assessment workflow

### Setup and versions
UCX - 0.18
Databricks cli - 0.215

### Cloud

Azure

### Operating System

Windows

### Version

latest via Databricks CLI

**Comment by nfx** [comment]
Thanks for the report, we’ll look into it shortly

**Comment by nfx** [comment]
@rkkalluri as a stopgap, can you change the UCX cluster policy and use the LTS runtime instead?

**Comment by gvidaspr** [comment]
hello,
have you been able to solve this issue? I am still running into it, `Message: com.databricks.api.base.DatabricksServiceException: BAD_REQUEST: DBFS library installations are not supported on DBR 15 or above.`

Running on Azure Databricks
