### ISSUE TITLE
[BUG]: databricks labs uninstall ucx --profile  does not work when we have multiple databricks profiles

### ISSUE THREAD

**Issue by rkkalluri** [databrickslabs/ucx#1102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we have multiple profiles in .databrickscfg file lets say for dev, tst, prd. Installs for one profile seems to inteterer with installs for others. The same for uninstalls, Can we modify to share installs for a given profile under different directories. 

Currently I have 2 prilfes dbx-dev and dbx-prd, it I uninstall with databricks labs uninstall ucx --profile dbx-dev , I cannot uninstall for dbx-prd as the .databricks/labs/ucs get wiped out. Also the remote install should check for the install on workspace irrespective of what is on the local workstation. May be this info can be tracked in the ucs schema in hive metastore as history.

### Expected Behavior

I expect install and uninstall for different profiles to not step on each others foot.

### Cloud

Azure

### Operating System

Windows

### Version

latest via Databricks CLI

**Comment by nfx** [comment]
@rkkalluri essentially, what you ask is the cross-workspace installation, right? Few questions:

1. dev & prod workspaces - are they in the same account?
2. how many workspaces are there in the account?
3. why do you need to uninstall?

At the moment, one UCX installation on the workstation maps to a remote installation

**Comment by rkkalluri** [comment]
dev & prod workspaces - are they in the same account?     
     Yes they are in the same account
how many workspaces are there in the account?
    About 100, but we may be working on 5-6 at a time.
why do you need to uninstall?
    For cleanup purposes. And if I can install, I would expect to be able to uninstall.

**Comment by rkkalluri** [comment]
I guess with DBR 15 you can run databricks cli on the workspace....that can solve some of these. Once DBR 15 works with UCX :)

**Comment by nfx** [comment]
@rkkalluri we're planning on cross-workspace installations - https://github.com/databrickslabs/ucx/issues?q=is%3Aopen+is%3Aissue+label%3A%22account-level+work%22

the first increment would be to install UCX on all workspaces in the account - it's the easiest happy path for account admins.

Later we may consider doing things in batches.
