### ISSUE TITLE
[FEATURE]: Detect usages of DBFS Mount paths in SQL code

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#1105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

```
SELECT * FROM parquet.`dbfs:/...` LIMIT 10
SELECT * FROM delta.`/mnt/...` WHERE foo > 6
DELETE FROM json.`/...` WHERE foo = 'bar'
MERGE INTO delta.`/dbfs/...` t USING source ON t.key = source.key WHEN MATCHED THEN DELETE
```
https://docs.databricks.com/en/sql/language-manual/delta-merge-into.html

### Proposed Solution

Solution has to be in https://github.com/databrickslabs/ucx/blob/main/src/databricks/labs/ucx/source_code/queries.py

**Comment by nfx** [comment]
@jimidle ^

**Comment by jimidle** [comment]
The pylint plugin repo does not seem to exist any longer. Looking.
