### ISSUE TITLE
Active Jobs Assessment Report

### ISSUE THREAD

**Issue by souvik-databricks** [databrickslabs/ucx#111]
I am taking over this work :: @FastLee , @nfx 

List of Active Jobs

- [ ] - DBR
- [ ] - Libraries
- [ ] - Spark configs
- [ ] - Interactive cluster usage vs new jobs cluster flags
- [ ] - Mount paths referenced in parameters (dbfs:/mnt and /dbfs/mnt)
- [ ] - Passthrough vs no passthrough

**Comment by nfx** [comment]
merged in https://github.com/databrickslabs/ucx/pull/244
