### ISSUE TITLE
[FEATURE]: Rewrite incompatible SQL UDF declarations

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#1119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

..

### Proposed Solution

..

### Additional Context
 Related:
- https://github.com/databrickslabs/ucx/issues/1118

**Comment by JCZuurmond** [comment]
@nfx : Could you add more context? Give an example of incompatible SQL udf and/or reference to docs about incompatible SQL udf

**Comment by nfx** [comment]
irrelevant
