### ISSUE TITLE
[BUG]: Files.for_cli unusably slow in unit tests

### ISSUE THREAD

**Issue by ericvergnaud** [databrickslabs/ucx#1127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Calling `Files.for_cli` from a unit test with a `workspace_client_mock` takes minutes (or maybe more, I was never patient enough)

### Expected Behavior

It should be fast enough so we can use it in unit tests.

### Steps To Reproduce

Use Pycharm
In `test_files.py`, uncomment `test_files_for_cli`
Run the test

### Cloud

AWS

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by nfx** [comment]
perhaps you need to mock out the call to SqlExecution API. see https://github.com/databrickslabs/lsql tests
