### ISSUE TITLE
Migrate legacy init scripts from DBFS

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#113]
We have to migrate  [legacy init scripts on DBFS](https://www.databricks.com/blog/securing-databricks-cluster-init-scripts), for every workspace. Needs:

* dry-run
* Consider the scenario where many jobs/clusters share the same DBFS init script: do not create a copy of the same script for each cluster/job.

**Comment by zpappa** [comment]
# Background
Migrate legacy global init scripts to cluster init scripts

# Input considerations
- Customer needs to provide a volume on which cluster init scripts can be stored.

# Implementation Considerations
- Do not duplicate global init scripts
- Create a cluster-scoped init script that invokes the global init scripts
- Move the global init scripts to a volume /global
- Move cluster-scoped init scripts to a volume /cluster

**Comment by nfx** [comment]
Handled outside of ucx
