### ISSUE TITLE
[FEATURE]: Detect spark code that reads directly from cloud storage 

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#1133]
Historically, customers have used mount points to connect their Databricks workspaces to their chosen cloud object storage, and many chose to utilize file paths as opposed to tables for accessing their data. For these long-time customers, the migration process is extremely manual, slow, and disruptive. This drastically decreases the chances of legacy customers upgrading their environment to Unity Catalog, which over time will lead to increased customer churn in favor of other platforms which do not require such a manual refactoring. Until now, we have not been able to provide an easier path forward for these customers.

**Comment by jimidle** [comment]
@nfx is this specifically looking for call sites base at `Spark.` that use cloud mount points?

**Comment by nfx** [comment]
It's rather using data directly, not through mounts. You can identify them by s3a://, abfss://, and few other file system schemes
