### ISSUE TITLE
[FEATURE]: Check circular dependencies when migrating views

### ISSUE THREAD

**Issue by ericvergnaud** [databrickslabs/ucx#1158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

Although theoretically made impossible by the database server, there exists a scenario where views could refer to each other:
```
CREATE VIEW V1 AS SELECT * FROM V2
CREATE VIEW V2 AS SELECT * FROM V1
```
This could happen if the DDL is extracted at different points in time and consolidated outside the database.
This would lead to an infinite loop in the ViewMigrator, and an impossibility to migrate altogether.
It is therefore useful to check for this scenario.

### Proposed Solution

Enhance `src/databricks/labs/ucx/hive_metastore/views_migrator.py` such that it checks for circular dependencies and eventually raises an error

**Comment by ericvergnaud** [comment]
Added a test at the end of `ViewsMigrator._next_batch` to prevent the infinite loop disaster but that does not suffice to explain which views are causing it.

**Comment by FastLee** [comment]
The current view code is checking for that.
Not directly but by failing _next batch if there are no view to satisfy it.

**Comment by ericvergnaud** [comment]
Already fixed, closing.
