### ISSUE TITLE
[FEATURE]: Support for downloading log files > 10Mb

### ISSUE THREAD

**Issue by william-conti** [databrickslabs/ucx#1171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Each UCX task write log files to the /Application folders, but in some cases, it is not possible to visualize them directly through the UI because these files exceeed 10Mb. As shown below

![Capture d’écran 2024-03-29 à 14 11 56](https://github.com/databrickslabs/ucx/assets/107417584/5a0e71e5-2029-430c-9234-02af8711b27b)

![Capture d’écran 2024-03-29 à 14 12 03](https://github.com/databrickslabs/ucx/assets/107417584/00de66d9-c059-4662-8385-d0c3791dc2ed)

### Expected Behavior

We should have a logging strategy to not write more than 10Mb of log files

### Cloud

AWS

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by nfx** [comment]
@william-conti there are two options:
1. log every 5 minutes instead of every 10 minutes
2. See https://github.com/databrickslabs/ucx/issues/1148
3. download logs via CLI

**Comment by william-conti** [comment]
@nfx Downloading logs via CLI also produces the same error message. See below 

<img width="1440" alt="Capture d’écran 2024-04-03 à 21 50 31" src="https://github.com/databrickslabs/ucx/assets/107417584/b32e86c3-8a56-4974-a278-a86abc1116fd">

**Comment by nfx** [comment]
I see... then we have to flush more often - it's a easy fix in framework/tasks
