### ISSUE TITLE
[FEATURE]: Support `is_partitioned` in scala notebook.

### ISSUE THREAD

**Issue by FastLee** [databrickslabs/ucx#1176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

Newly introduced `is_partitioned` property is currently not covered by the scala notebook used by the assessment workflow.

### Proposed Solution

Modify the notebook to support this new functionality.

**Comment by nfx** [comment]
it does - https://github.com/databrickslabs/ucx/commit/eb50f9adf5cccc4b43202c28b692fe578ef0e8c2
