### ISSUE TITLE
[FEATURE]: Create External Location, Catalog, Schema ACL for Principals based on Interactive cluster permission using instance profiles

### ISSUE THREAD

**Issue by HariGS-DB** [databrickslabs/ucx#1193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

Currently Users access interactive clusters using instance profile configured which has permission on the underlying was bucket.
When migrating to UC, we need to create permission to interactive clusters users on the external location, catalog and schema based on the underlying instance profile access on the buckets
Related issues:

https://github.com/databrickslabs/ucx/issues/887

### Proposed Solution

identify interactive clusters with instance profile configured.
check instance profile permission on the underlying buckets
grant appropriate permission on the external location to the users of the interactive clusters
grant use permission on the catalog and schema equivalent tin UC for the users of the interactive clusters

**Comment by HariGS-DB** [comment]
887 is for table/view access like 907 which is added TableMigrate, but we also need to give access to schema, database and external location which needs to be added as part of the databricks labs ucx migrate-location and databricks labs ucx create-catalogs-schemas

**Comment by nfx** [comment]
Ah. Good. They both can be merged into one. You can pick this one up if you have cycles - start a PR, as usual
