### ISSUE TITLE
[FEATURE]: Detect notebook include graph by analysing `dbutils.notebook.run(...)` calls

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#1200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

From https://docs.databricks.com/en/notebooks/notebook-workflows.html:

The dbutils.notebook API is a complement to %run because it lets you pass parameters to and return values from a notebook. This allows you to build complex workflows and pipelines with dependencies. For example, you can get a list of files in a directory and pass the names to another notebook, which is not possible with %run. You can also create if-then-else workflows based on return values or call other notebooks using relative paths. Unlike %run, the dbutils.notebook.run() method starts a new job to run the notebook. These methods, like all of the dbutils APIs, are available only in Python and Scala. However, you can use dbutils.notebook.run() to invoke an R notebook.

### Proposed Solution

Scan Python code for `dbutils.notebook.run(...)` calls and treat them like a dependency

**Comment by ericvergnaud** [comment]
What about Scala code ?

**Comment by nfx** [comment]
We don't have scala parser yet, for now let's create higher level epic and postpone until py and sql migrations are fully operational. Scala also has good almost builtin parser which is typesafer, so it is just a matter of priorities

**Comment by nfx** [comment]
closed in:
- https://github.com/databrickslabs/ucx/pull/1284
