### ISSUE TITLE
[FEATURE]: If a code computes a value dynamically, do value inference, at least at the state of linting

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#1205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

If arguments to the relevant functions are string literals, resolve them and perform linting:

- https://github.com/databrickslabs/ucx/issues/1133
- https://github.com/databrickslabs/ucx/issues/1118
- https://github.com/databrickslabs/ucx/issues/1104
- https://github.com/databrickslabs/ucx/issues/1082
- https://github.com/databrickslabs/ucx/issues/391
- https://github.com/databrickslabs/ucx/issues/315

e.g. in cases like:

```python
db = 'foo'
t = f'{db}.bar'
display(spark.table(t))
```

we have to check if `foo.bar` table is migrated. 

### Proposed Solution

infer values from the available scope.

**Comment by ericvergnaud** [comment]
migration to astroid is successful
simple inference works

What doesn't work at all (no inference):
 - fstrings i.e.` dbutils.notebook.run(f"prefix {value} suffix")` -> see test_raises_advice_when_dbutils_notebook_run_is_too_complex

What is problematic:
 - loops:
```
paths = [ "p1", "p2" ] 
for path in paths:
    dbutils.notebook.run(path)
```
the value is inferred only once (for the first item)

**Comment by ericvergnaud** [comment]
@nfx I believe value inference is done for all currently implemented scenarios, see #1835, #1860, #1866, #1868 and #1870
Not sure if missing linters should be implemented as part of this issue (I guess not) ? Rather value inference should be done as part of their dedicated implementation ?

**Comment by ericvergnaud** [comment]
@nfx as of writing, the only known issue is with fstrings (see above). I've created corresponding ticket #1871

**Comment by nfx** [comment]
@ericvergnaud lets solve the f-string issue, as it's very common
