### ISSUE TITLE
[BUG]: CLI command create-account-groups fails with ImportError

### ISSUE THREAD

**Issue by pritishpai** [databrickslabs/ucx#1208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

➜  ~ databricks labs ucx create-account-groups --profile ppai-azure-account-test --debug
09:18:58  INFO start pid=4958 version=0.215.0 args="databricks, labs, ucx, create-account-groups, --profile, ppai-azure-account-test, --debug"
09:18:58 DEBUG Loading installed version info from: /Users/pritish.pai/.databricks/labs/ucx/state/version.json pid=4958
09:18:58  INFO Overriding login profile: ppai-azure-account-test pid=4958
09:18:58 DEBUG Loading ppai-azure-account-test profile from /Users/pritish.pai/.databrickscfg pid=4958 sdk=true
09:18:58 DEBUG Resolved login: Config: host=https://accounts.azuredatabricks.net/, account_id=827e3e09-89ba-4dd2-9161-a3301d0f21c0, profile=ppai-azure-account-test, config_file=/Users/pritish.pai/.databrickscfg pid=4958 sdk=true
09:18:58 DEBUG Passing down environment variables: DATABRICKS_HOST, DATABRICKS_ACCOUNT_ID pid=4958
09:18:58 DEBUG Forwarding subprocess: /Users/pritish.pai/.databricks/labs/ucx/state/venv/bin/python3 /Users/pritish.pai/.databricks/labs/ucx/lib/src/databricks/labs/ucx/cli.py {"command":"create-account-groups","flags":{"log_level":"debug","workspace_ids":""},"output_type":""} pid=4958
09:18:58 DEBUG starting: /Users/pritish.pai/.databricks/labs/ucx/state/venv/bin/python3 /Users/pritish.pai/.databricks/labs/ucx/lib/src/databricks/labs/ucx/cli.py {"command":"create-account-groups","flags":{"log_level":"debug","workspace_ids":""},"output_type":""} pid=4958
Traceback (most recent call last):
  File "/Users/pritish.pai/.databricks/labs/ucx/lib/src/databricks/labs/ucx/cli.py", line 19, in <module>
    from databricks.labs.ucx.aws.credentials import IamRoleMigration
  File "/Users/pritish.pai/.databricks/labs/ucx/lib/src/databricks/labs/ucx/aws/credentials.py", line 9, in <module>
    from databricks.sdk.service.catalog import (
ImportError: cannot import name 'AwsIamRoleRequest' from 'databricks.sdk.service.catalog' (/Users/pritish.pai/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/service/catalog.py)
Error: exit status 1
09:18:58 ERROR failed execution pid=4958 exit_code=1 error="exit status 1"

### Expected Behavior

Copy workspace-groups to account level

### Steps To Reproduce

Run 
databricks labs ucx create-account-groups 

### Cloud

AWS

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by nfx** [comment]
fixed in v0.21.0 https://github.com/databrickslabs/ucx/commit/b84bb7f54b9ae662170417bae13a4ce98488c20a
