### ISSUE TITLE
[FEATURE]: Detect and process `USE <database>` statements

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#1215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

USE statement is used to set the current database. After the current database is set, the unqualified database artifacts such as tables, functions and views that are referenced by SQLs are resolved from the current database. The default database name is ‘default’.

```
USE database_name
```

```
spark.sql("use something")
spark.table("anything").show()
```

the second statement would show records from `something.anything`, not `default.anything`.

See https://spark.apache.org/docs/3.0.0-preview/sql-ref-syntax-qry-select-usedb.html

The following test case has to produce three different table advice:

```
# Databricks notebook source
display(spark.table('people')) # we are looking at default.people table

# COMMAND ----------

# MAGIC %sql USE something

# COMMAND ----------

display(spark.table('persons')) # we are looking at something.persons table

# COMMAND ----------

spark.sql('USE whatever')

# COMMAND ----------

display(spark.table('kittens')) # we are looking at whatever.kittens table
```

### Proposed Solution

have linters/fixers pickup `USE database` statements if they occur in the code to resolve single-table-name lookups

**Comment by nfx** [comment]
@jimidle

**Comment by jimidle** [comment]
Currently the tests etc supply the schema and if they do not, it is defaulting to None. Should I make it default to 'default'? It seems so.
