### ISSUE TITLE
[FEATURE]: Detect table schemas that have changed between HMS and UC

### ISSUE THREAD

**Issue by william-conti** [databrickslabs/ucx#1218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

UCX cannot identify if a table schema is different, this can lead to unexpected scenarios when a table in HMS / UC has completely changed.

### Proposed Solution

When checking if a table exists in UC or not, additionally check the table schema. 
Ask the user if he would like to recreate the table.

**Comment by JCZuurmond** [comment]
Already implemented: https://github.com/databrickslabs/ucx/blob/9b69dac477f6b8a676237bf5324399b3409b4c2e/src/databricks/labs/ucx/recon/migration_recon.py#L108C13-L108C30
