### ISSUE TITLE
[FEATURE]: Detect tables that are not present in the mapping file

### ISSUE THREAD

**Issue by william-conti** [databrickslabs/ucx#1221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

For large enterprise customers that are migrating tables in mount points, they generally do not exactly know how many tables they have in these mount points.
It can happen that after producing the csv mapping file, some tables cannot be migrated to UC and it would be ideal to be alerted that some tables are missing in the csv mapping file.

### Proposed Solution

Add a verification that if a table identified in the assessment isn't present in the csv file, a warning/error message should be prompted.

**Comment by ericvergnaud** [comment]
Would it make sense to generate a `not-mapped.csv` file such that results from a previous migration run can be exmined without running again ?

**Comment by JCZuurmond** [comment]
yes, or print out the `not-mapped` tables so that users can pipe it to any file or command they like
