### ISSUE TITLE
[FEATURE]: add command for migrating DBFS_ROOT_NON_DELTA tables

### ISSUE THREAD

**Issue by ericvergnaud** [databrickslabs/ucx#1230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

There exists commands for migrating DBFS_ROOT_DELTA, EXTERNAL_SYNC and VIEW tables, but not for DBFS_ROOT_NON_DELTA.

### Proposed Solution

Add command in `runtime.py`.

**Comment by nfx** [comment]
Duplicate of https://github.com/databrickslabs/ucx/issues/332
