### ISSUE TITLE
[BUG]: principal_prefix_access for azure cloud results in error

### ISSUE THREAD

**Issue by apd-ahusain** [databrickslabs/ucx#1249]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Azure CLI is installed and credentials have been configured via `az login`. However, running `databricks labs ucx principal-prefix-access --subscription-id 123456789` returns "ERROR [d.labs.ucx] In order to obtain AAD token, Please run azure cli to authenticate". There is no way to manually override the Databricks `WorkspaceClient` auth type to `azure-cli`.

### Expected Behavior

The command `databricks labs ucx principal-prefix-access --subscription-id 123456789` should recognize that the Azure CLI authentication has already been setup and the AAD token already exists, and save storage and spn info under  {install_folder}/.ucx/azure_storage_account_info.csv

### Steps To Reproduce

1. Install prerequisites: Databricks CLI v0.215.0, UCX v0.20.0, Azure CLI v2.59.0; complete all prerequisite steps as outlined under `README/migration-process`
2. `az login`
3. `az account set --subscription "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"`
4. `az account show` to validate login
5. `az account get-access-token` to validate that token exists
6. `databricks labs ucx create-uber-principal [--subscription-id X]`

### Cloud

Azure

### Operating System

macOS

### Version

latest via Databricks CLI

### Relevant log output

```shell
14:50:33 ERROR [d.labs.ucx] In order to obtain AAD token, Please run azure cli to authenticate.
```

**Comment by nfx** [comment]
Run command again but with "--debug" flag, it should show the current auth type. What is it?

**Comment by nfx** [comment]
@apd-ahusain Alternatively, run with an explicit auth type set: DATABRICKS_AUTH_TYPE=azure-cli databricks labs ucx ...

I don't remember if python SDK understands that environment variable, but I remember writing it in CLI in Go for sure. Let me know if this one works

**Comment by apd-ahusain** [comment]
> @apd-ahusain Alternatively, run with an explicit auth type set: DATABRICKS_AUTH_TYPE=azure-cli databricks labs ucx ...
> 
> I don't remember if python SDK understands that environment variable, but I remember writing it in CLI in Go for sure. Let me know if this one works

This worked - closing the issue now. Thanks!

**Comment by artsheiko** [comment]
The workaround proposed didn't work on Windows.
If the same happens for you, try the following : 
1. Open %userprofile% (the path like C:\Users\<user name>)
2. Open .databrickscfg
3. Change the profile definition by setting auth_type=azure-cli
4. Save, close the file, re-run databricks labs ucx principal-prefix-access
