### ISSUE TITLE
[BUG]: Upgrade not working from 0.8.0: ModuleNotFoundError: No module named 'databricks.labs.blueprint'

### ISSUE THREAD

**Issue by skantzidis** [databrickslabs/ucx#1276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Receive error while upgrading from v0.8.0 via databricks labs command.

Attempted method to upgrade:
databricks labs upgrade ucx --debug 

Error received:
(venv310) xyzxyz@xxxxxxxxx ucx % databricks labs upgrade ucx --debug 
22:05:54  INFO start pid=97387 version=0.217.0 args="databricks, labs, upgrade, ucx, --debug"
22:05:54 DEBUG Latest ucx version is: v0.21.0 pid=97387
22:05:54 DEBUG Reading labs.yml@v0.21.0 from databrickslabs/ucx pid=97387
⣾ Cleaning up previous installation if necessary22:05:54 DEBUG Downloading zipball for v0.21.0 from databrickslabs/ucx pid=97387
⣷ Downloading and unpacking zipball for v0.21.022:05:57 DEBUG Unpacking zipball to: /Users/xyzxyz/.databricks/labs/ucx/lib pid=97387
⣾ Downloading and unpacking zipball for v0.21.022:05:57 DEBUG Writing installed version info to: /Users/xyzxyz/.databricks/labs/ucx/state/version.json pid=97387
22:05:57 DEBUG Launching installer script src/databricks/labs/ucx/install.py in /Users/xyzxyz/.databricks/labs/ucx/lib pid=97387
22:05:57 DEBUG Loading login configuration from: /Users/xyzxyz/.databricks/labs/ucx/config/login.json pid=97387
22:05:57 DEBUG Using workspace-level login profile: DEFAULT pid=97387
22:05:57 DEBUG Loading DEFAULT profile from /Users/xyzxyz/.databrickscfg pid=97387 sdk=true
22:05:57 DEBUG Resolved login: Config: host=https://xxxxxxxx-staging.cloud.databricks.com/, token=***, profile=DEFAULT, config_file=/Users/xyzxyz/.databrickscfg pid=97387 sdk=true
22:05:57 DEBUG Passing down environment variables: DATABRICKS_HOST, DATABRICKS_TOKEN pid=97387
22:05:57 DEBUG starting: /Users/xyzxyz/.databricks/labs/ucx/state/venv/bin/python3 src/databricks/labs/ucx/install.py pid=97387
Traceback (most recent call last):
  File "/Users/xyzxyz/.databricks/labs/ucx/lib/src/databricks/labs/ucx/install.py", line 12, in <module>
    from databricks.labs.blueprint.entrypoint import get_logger
ModuleNotFoundError: No module named 'databricks.labs.blueprint'
Error: installer: exit status 1
22:05:58 ERROR failed execution pid=97387 exit_code=1 error="installer: exit status 1"

Also a bit weird that when I run:
databricks labs installed --debug, I see:

Name  Description                            Version
ucx   Unity Catalog Migration Toolkit (UCX)  *

(i.e. no version displayed).

Is 0.8.0 "too old" a version to run upgrade? Is my only option to manually delete and re-install?

### Expected Behavior

Running upgrade command should enable me to upgrade to 0.21.0, or most recent ucx version.

### Cloud

AWS

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by nfx** [comment]
Yes, v0.8.0 is too old. Please reinstall for now. 

Meanwhile, I’ll work on fixing the update method in the CLI, as it’s a real bug

**Comment by jarnawer** [comment]
Just to add more context, it is also happening with version v0.21.0, when I execute create-table-mapping (and I would say that with any operation that invokes the CLI): 

```
20:13:45  INFO start pid=16019 version=0.215.0 args="databricks, labs, ucx, create-table-mapping, -p, plf007003-chn-dev, --debug"
20:13:45 DEBUG (development mode) using active virtual environment from: /home/tka4o/projects/azure/databricks/ucx/venv pid=16019 sdk=true
20:13:45 DEBUG (development mode) using active virtual environment from: /home/tka4o/projects/azure/databricks/ucx/venv pid=16019 sdk=true
20:13:45  INFO Overriding login profile: plf007003-chn-dev pid=16019
20:13:45 DEBUG Loading plf007003-chn-dev profile from /home/tka4o/.databrickscfg pid=16019 sdk=true
20:13:45 DEBUG Resolved login: Config: host=https://adb-7958625398921876.16.azuredatabricks.net, profile=plf007003-chn-dev, config_file=/home/tka4o/.databrickscfg pid=16019 sdk=true
20:13:45 DEBUG Passing down environment variables: DATABRICKS_AUTH_TYPE, DATABRICKS_HOST pid=16019
20:13:45 DEBUG Forwarding subprocess: /home/tka4o/projects/azure/databricks/ucx/venv/bin/python3 /home/tka4o/projects/azure/databricks/ucx/src/databricks/labs/ucx/cli.py {"command":"create-table-mapping","flags":{"log_level":"debug"},"output_type":""} pid=16019
20:13:45 DEBUG starting: /home/tka4o/projects/azure/databricks/ucx/venv/bin/python3 /home/tka4o/projects/azure/databricks/ucx/src/databricks/labs/ucx/cli.py {"command":"create-table-mapping","flags":{"log_level":"debug"},"output_type":""} pid=16019
Traceback (most recent call last):
  File "/home/tka4o/projects/azure/databricks/ucx/src/databricks/labs/ucx/cli.py", line 8, in <module>
    from databricks.labs.blueprint.cli import App
ModuleNotFoundError: No module named 'databricks.labs.blueprint'
Error: exit status 1
20:13:45 ERROR failed execution pid=16019 exit_code=1 error="exit status 1"
```

**Comment by nfx** [comment]
@jarnawer It doesn't seem that you installed correctly: the invoked file is not from .databricks/labs/ucx/lib folder:

20:13:45 DEBUG starting: /home/***/projects/azure/databricks/ucx/venv/bin/python3 /home/***/projects/azure/databricks/ucx/src/databricks/labs/ucx/cli.py

Where did you get faulty installation instructions?..

**Comment by jarnawer** [comment]
Not faulty instructions, actually. My terminal was working inside a virtual environment but somehow it wasn't showing that. You can completely ignore my message :)

**Comment by jarnawer** [comment]
Yes, exactly I did that. So I was working actually from a virtual environment that I created, but some UI issue was not showing me that I really was using the venv. So I pip installed the blueprint library and also the lsql modules to use the CLI from that venv, and continued working

**Comment by nfx** [comment]
@jimidle the solution to this issue is to add `pip install .` in the downstreams of 

https://github.com/databricks/cli/blob/c7818560ca1c60a3324c190fa2b24e29c5acf8c2/cmd/labs/upgrade.go#L15-L19
