### ISSUE TITLE
[BUG]: Error when running `databricks labs ucx create-uber-principal`

### ISSUE THREAD

**Issue by mohanab-db** [databrickslabs/ucx#1289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

> databricks labs ucx create-uber-principal -p tmp_ucx --aws-profile=sandbox  
17:26:23 ERROR [d.l.ucx.create-uber-principal] TypeError: _aws_setup_uber_principal() got an unexpected keyword argument 'aws_permissions'

### Expected Behavior

Error should not be thrown

### Steps To Reproduce

Execute command
`databricks labs ucx create-uber-principal -p tmp_ucx --aws-profile=sandbox`

### Cloud

AWS

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by qziyuan** [comment]
fixed by https://github.com/databrickslabs/ucx/pull/1209
