### ISSUE TITLE
[FEATURE]: Mark notebooks as migrated

### ISSUE THREAD

**Issue by ericvergnaud** [databrickslabs/ucx#1327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

There is currently no way to mark notebooks as migrated. This is suboptimal because when migrating notebook dependencies, we may end up migrating the same notebook more than once

### Proposed Solution

Register migrated notebooks

**Comment by nfx** [comment]
Technically, we can have an ignore list in teh .ucx folder, which will be human-editable and we can skip certain notebooks

**Comment by JCZuurmond** [comment]
Rerunning code migration on an already migrated code should result the same code, otherwise that is a bug. So this is a performance improvement

**Comment by nfx** [comment]
Closing in favor of https://github.com/databrickslabs/ucx/issues/2073
