### ISSUE TITLE
[BUG]: View Migrator omits a view's column list argument

### ISSUE THREAD

**Issue by danielm-db** [databrickslabs/ucx#1345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using the view text instead of a show create table statement will create views; however, if the view was created with the argument column_list, it will result in an erroneous view with no errors raised. 

Here is an example of a view created using the argument column list, in the image it is represented as (name,user_id), note how leveraging the view text completely resulted in a successful view creation but erroneous column names. 
![image](https://github.com/databrickslabs/ucx/assets/107701650/e7da7a2e-e2d6-4ba7-b6ee-e724810d9c32)

### Expected Behavior

If a view was created and used the argument column_list, the migratory should recreate the view using the column list argument. (can be extracted using SHOW CREATE TABLE instead of the DESC EXTENDED, View Text logic. 

### Cloud

Azure

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by FastLee** [comment]
We are looking into it.

**Comment by nfx** [comment]
Fixed in https://github.com/databrickslabs/ucx/commit/3998c4574f74ecc7584ef2d81b809be900034e19
