### ISSUE TITLE
[FEATURE]: Update README.md and assessment workflow document to improve discoverability of "[UCX] UCX Assessment (Interactive)" dashboard

### ISSUE THREAD

**Issue by dmoore247** [databrickslabs/ucx#1347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

Users happening across UCX repo and README.md would not be aware that UCX has a dashboard that may detect code issues with SHARED cluster usage, as part of the assessment process. There is no mention of the newer dashboard.

### Proposed Solution

Add intro sentences and links and possibly an overview .md for the "[UCX] UCX Assessment (Interactive)" report.

### Additional Context

Internal slack conversation pointed out this question could not be answered with a single link.

**Comment by nfx** [comment]
what is this dashboard? do we need it?

**Comment by nfx** [comment]
No longer necessary with linter work
