### ISSUE TITLE
[BUG]: RESOURCE_DOES_NOT_EXIST error not returned when loading inexistent object in DependencyLoader

### ISSUE THREAD

**Issue by ericvergnaud** [databrickslabs/ucx#1361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`DependencyLoader` calls `WorkspaceAPI.get_status`, which does not seem to cater for `error_code`.
As a result, the behavior in case of inexistent object is undetermined.

### Expected Behavior

The result of `WorkspaceAPI.get_status` should be `ObjectInfo | dict`, the latter signaling an error condition.

### Cloud

AWS

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by nfx** [comment]
catch `NotFound`, `WorkspaceAPI.get_status` is `ObjectInfo`. there's no dict there. Probably you're seeing a wrong mock.

**Comment by ericvergnaud** [comment]
I'm seeing this in `workspace.py` (not a mock) :
```
        res = self._api.do('GET', '/api/2.0/workspace/get-status', query=query, headers=headers)
        return ObjectInfo.from_dict(res)

```
and this in `core.py`:
```
        return {**resp, **json}
```
None of the above caters for error_code or throws on 404
