### ISSUE TITLE
[FEATURE]: Detect workspace file programming language

### ISSUE THREAD

**Issue by ericvergnaud** [databrickslabs/ucx#1363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

Workspace files do not have a default language (see https://docs.databricks.com/api/workspace/workspace/getstatus).
Therefore, when fetching a workspace file, we need to discover the file's programming language

### Proposed Solution

Look at the file extension if any. Ultimately, assume the language is implicit based on context (a file imported from a Python file would also be Python)

### Additional Context

Sub-ticket of #1202

**Comment by nfx** [comment]
this is almost a noop - we know the extensions

**Comment by ericvergnaud** [comment]
This was about workspace files, not local files. Workspace files are out of scope, closing.
