### ISSUE TITLE
[FEATURE]: When detecting compatibility issues, check against current DB runtime version 

### ISSUE THREAD

**Issue by ericvergnaud** [databrickslabs/ucx#1382]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

Compatibility issues vary depending on package version and DB runtime version.
There is a need to check compatibility with given version to avoid false positives (incorrect Advice) and false negatives (missing Advice)

### Proposed Solution

Read current DB runtime version, and installed package version, and use them in Whitelist

### Additional Context

sub-ticker of #1202

**Comment by nfx** [comment]
Should be a field in the `CurrentSessionState`

**Comment by ericvergnaud** [comment]
Duplicate of #1527
