### ISSUE TITLE
[BUG]: UCX labs install 0.21 spews warnings 

### ISSUE THREAD

**Issue by rkkalluri** [databrickslabs/ucx#1390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Not sure what the issue is and it may be harmless but wanted to file it anyway.

11:42:29  WARN [d.l.u.framework.dashboards][installing_components_0] Type error in SDK API response, ES-1061370
11:42:29  WARN [d.l.u.framework.dashboards][installing_components_0] Type error in SDK API response, ES-1061370

### Cloud

Azure

### Operating System

Windows

### Version

latest via Databricks CLI

**Comment by pritishpai** [comment]
Already resolved in https://github.com/databrickslabs/ucx/pull/1207 will be a part of the next release.
