### ISSUE TITLE
Propagate file and start/end line/character information for incompatible dependencies

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#1418]
Modify to highlight the exact code range where deprecated import happened

_Originally posted by @nfx in https://github.com/databrickslabs/ucx/pull/1395#discussion_r1566448143_

**Comment by ericvergnaud** [comment]
@nfx I believe this is already done, or am I missing something ?

**Comment by nfx** [comment]
solved in 

https://github.com/databrickslabs/ucx/blob/f3c8cb05cf06e6bce3ba74729041c4fc21d0444c/tests/unit/source_code/test_dependencies.py#L210-L214
