### ISSUE TITLE
[FEATURE]: Enhance 'WorkspaceContext' with whitelist, dependency_resolver (and possibly local_loader)

### ISSUE THREAD

**Issue by ericvergnaud** [databrickslabs/ucx#1466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

WorkspaceContext provides a local_file_migrator, but its initialization is not context aware. 

### Proposed Solution

Provide missing cached_properties

**Comment by nfx** [comment]
it has to be in the `GlobalContext`

**Comment by nfx** [comment]
done in https://github.com/databrickslabs/ucx/commit/da71371bb4bfa61505eaca6ddcded1bac4acbfb4
