### ISSUE TITLE
[BUG]: UCX_FORCE_INSTALL=user  does not change the default installation folder to user's folder

### ISSUE THREAD

**Issue by aminmovahed-db** [databrickslabs/ucx#1471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I run UCX for the first time in a workspace with the parameter `UCX_FORCE_INSTALL=user`(i,e, `UCX_FORCE_INSTALL=user databricks labs install ucx`), it installs the files under `/Applications/ucx` rather than `/Users/X/.ucx`.

### Expected Behavior

Based on the change [#854](https://github.com/databrickslabs/ucx/pull/854) in release [v0.21.0](https://github.com/databrickslabs/ucx/releases/tag/v0.21.0), if `UCX_FORCE_INSTALL` is set to `user` then the installation folder should be the users folder e.g., `/Users/X/.ucx/`.

### Steps To Reproduce

Run `UCX_FORCE_INSTALL=user databricks labs install ucx` where there is no ucx already installed in the target workspace.

### Cloud

Azure

### Operating System

macOS

### Version

latest via Databricks CLI

### Relevant log output
![image](https://github.com/databrickslabs/ucx/assets/140028681/5baa7507-ee1d-4ae5-a8b9-f57c8936c6f0)

_No response_

**Comment by pritishpai** [comment]
<img width="1689" alt="image" src="https://github.com/databrickslabs/ucx/assets/136742693/b50ed720-0ef1-4604-a968-07d232e820bc">
@aminmovahed-db It is installing in the user location now. Can you retry?
