### ISSUE TITLE
[FEATURE]: Save ucx version

### ISSUE THREAD

**Issue by JCZuurmond** [databrickslabs/ucx#1482]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

The ucx version is not saved in the installation, while it is [loaded during version compare](https://github.com/databrickslabs/ucx/blob/73db677b2998dd8e5f1fa5486a748dfb6ac4856c/src/databricks/labs/ucx/install.py#L220).

### Proposed Solution

The ucx version should be saved when the [configuration is saved during installation](https://github.com/databrickslabs/ucx/blob/73db677b2998dd8e5f1fa5486a748dfb6ac4856c/src/databricks/labs/ucx/install.py#L309)

**Comment by nfx** [comment]
@JCZuurmond it's saved when we upload the wheel in ~/.ucx/version.json - https://github.com/databrickslabs/blueprint?tab=readme-ov-file#application-state-migrations

**Comment by JCZuurmond** [comment]
Thank you. Ran into this when debugging #1467. Probably stopped the installation before the wheel is uploaded. Could not find the version create anywhere
