### ISSUE TITLE
Create end-to-end documentation for table migration

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#1488]
Expectation is to fully document the table migration workflow and commands:

- [ ] [Table Migration Workflow](https://github.com/databrickslabs/ucx?tab=readme-ov-file#table-migration-workflow)
- [ ] [Dependency CLI commands](https://github.com/databrickslabs/ucx?tab=readme-ov-file#dependency-cli-commands)
- [ ] [Table Migration Workflow Tasks](https://github.com/databrickslabs/ucx?tab=readme-ov-file#table-migration-workflow-tasks)
- [ ] [Other considerations](https://github.com/databrickslabs/ucx?tab=readme-ov-file#other-considerations)
- [ ] [principal-prefix-access command](https://github.com/databrickslabs/ucx#principal-prefix-access-command)
- [ ] [Access for AWS S3 Buckets](https://github.com/databrickslabs/ucx#access-for-aws-s3-buckets)
- [ ] [Access for Azure Storage Accounts](https://github.com/databrickslabs/ucx#access-for-azure-storage-accounts)
- [ ] [create-uber-principal command](https://github.com/databrickslabs/ucx#create-uber-principal-command)
- [ ] [migrate-credentials command](https://github.com/databrickslabs/ucx#migrate-credentials-command)
- [ ] [validate-external-locations command](https://github.com/databrickslabs/ucx#validate-external-locations-command)
- [ ] [migrate-locations command](https://github.com/databrickslabs/ucx#migrate-locations-command)
- [ ] [create-table-mapping command](https://github.com/databrickslabs/ucx#create-table-mapping-command)
- [ ] [skip command](https://github.com/databrickslabs/ucx#skip-command)
- [ ] [revert-migrated-tables command](https://github.com/databrickslabs/ucx#revert-migrated-tables-command)
- [ ] [create-catalogs-schemas command](https://github.com/databrickslabs/ucx#create-catalogs-schemas-command)
- [ ] [move command](https://github.com/databrickslabs/ucx#move-command)
- [ ] [alias command](https://github.com/databrickslabs/ucx#alias-command)

**Comment by gregorymiguel** [comment]
It seems that "migrate-credentials" and "migrate-locations" need a named parameter subscription-id to work properly on Azure.
If it's not informed, it won't work.
The docummentation needs to be fixed.
