### ISSUE TITLE
[BUG]: Truncate logs from `acceptance` action

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#1494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="1003" alt="image" src="https://github.com/databrickslabs/ucx/assets/259697/3feac3d6-bbbf-4331-82cc-d34a4e7cddac">

### Cloud

AWS

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by nfx** [comment]
when jobs fail, on the side of the workflow within DBR, we may produce more than 1MB of logs and if we try to post it into github comment, we get bad request error, because the total payload size of github comments or descriptions must not exceed 1MB. The fix for this must truncate the exceessive log output. See the relevant code:

https://github.com/databrickslabs/ucx/blob/e3bdd3d0395324238d51748322acdc11c43e7f9d/src/databricks/labs/ucx/installer/workflows.py#L125-L130

**Comment by ericvergnaud** [comment]
@nfx exploring this again
I'm not sure if the suggested fix (implemented in #1655) is relevant:
 - it only applies to a small subset of the acceptance tests (the ones that run a workflow)
 - the failing upload seems to be attempting to upload the entire logs for the GH action, not just for the failing test
 Wouldn't it be more relevant to limit the comment size in https://github.com/databrickslabs/sandbox/blob/88d1d5e50a001b9d8e4d6a819f0e9e47d37eb631/acceptance/boilerplate/actions.go#L96 ?

**Comment by JCZuurmond** [comment]
Issued poped up again: https://github.com/databrickslabs/ucx/actions/runs/11007362115/job/30563142660

**Comment by nfx** [comment]
fixed in https://github.com/databrickslabs/sandbox/pull/261
