### ISSUE TITLE
[FEATURE]: Scan all notebooks and python files attached to every job and render a dashboard

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#1539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

1. Jobs may contain multiple notebook tasks
2. Notebook tasks may be written in python or sql
3. but tasks could also be python files and packages
4. python files may live on dbfs or git repo

### Proposed Solution

scan notebooks and python files as dependencies of a job and refresh a dashboard with results, that link to notebooks/files in the same workspace

**Comment by JCZuurmond** [comment]
@JCZuurmond : Split out dashboard creation

**Comment by JCZuurmond** [comment]
Updated title as split out to #1740
