### ISSUE TITLE
[BUG]:  wasbs:// and dbfs:// mount external tables are not listing in principal-prefix-access command

### ISSUE THREAD

**Issue by heydil** [databrickslabs/ucx#1552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, external tables mounted using the wasbs:// and dbfs:// are not being listed when using the principal-prefix-access command, azure_storage_account_info.csv file is not getting generated.

### Expected Behavior

External tables mounted using the wasbs:// and dbfs:// protocol should be listed when using the principal-prefix-access command and successful creation of azure_storage_account_info.csv file.

### Steps To Reproduce

1. I have external table , mount point and external locations listed in the inventory database after the assessment run.
![Screenshot 2024-04-25 112727](https://github.com/databrickslabs/ucx/assets/76246320/5e632898-c820-4d8f-84ef-77eaeda5c488)
![Screenshot 2024-04-25 112913](https://github.com/databrickslabs/ucx/assets/76246320/b73faf0d-fa72-4a13-9321-a0a8e665f5b8)

2. When running the principal-prefix-access command, receive the below warning message: 
![Screenshot 2024-04-25 114100](https://github.com/databrickslabs/ucx/assets/76246320/986df75b-9cf6-4ae0-b9fa-ace0cf7ddc32)

### Cloud

Azure

### Operating System

Windows

### Version

latest via Databricks CLI

### Relevant log output

```shell
WARN [d.l.u.assessment.crawlers] There are no external table present with azure storage account. Please check if assessment job is run
```

**Comment by HariGS-DB** [comment]
principal-prefix-access cmd creates a list of storage account used by tables along with its permission. This list is then used to create storage credentials. for table referring to wasb:// and adl:// , we shouldn't be creating its service principal as credential. The ideal solution would be to migrate the data from wasb:// ad adl:// to abfss storage and use its storage credential and location. 
refer #1065 for more details.
we should update the documentation to make this clear
