### ISSUE TITLE
[BUG]: OAuth not configured or not available: cannot get access token: Error: cache: databricks OAuth is not configured for this host

### ISSUE THREAD

**Issue by rkkalluri-dbx** [databrickslabs/ucx#1574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have configured account level  auth via  databricks auth login --host https://adb-54fdfdf.  but looks like sync-workspace-info  is not working here is the debug info

21:30:50 DEBUG [databricks.sdk] Attempting to configure auth: databricks-cli
21:30:50 DEBUG [databricks.sdk] OAuth not configured or not available: cannot get access token: Error: cache: databricks OAuth is not configured for this host

 databricks labs ucx sync-workspace-info --debug
21:30:49  INFO start pid=99891 version=0.218.1 args="databricks, labs, ucx, sync-workspace-info, --debug"
21:30:49 DEBUG Loading installed version info from: /Users/user/.databricks/labs/ucx/state/version.json pid=99891
21:30:49 DEBUG Loading login configuration from: /Users/user/.databricks/labs/ucx/config/login.json pid=99891
21:30:49 DEBUG Using account-level login profile: accounts pid=99891
21:30:49 DEBUG Loading accounts profile from /Users/user/.databrickscfg pid=99891 sdk=true
21:30:49 DEBUG Resolved login: Config: host=https://accounts.azuredatabricks.net/, account_id=2b0b0274-763c-4895-9b4f-9162bf344c58, profile=accounts, config_file=/Users/user/.databrickscfg pid=99891 sdk=true
21:30:49 DEBUG Passing down environment variables: DATABRICKS_HOST, DATABRICKS_ACCOUNT_ID, DATABRICKS_AUTH_TYPE pid=99891
21:30:49 DEBUG Forwarding subprocess: /Users/user/.databricks/labs/ucx/state/venv/bin/python3 /Users/user/.databricks/labs/ucx/lib/src/databricks/labs/ucx/cli.py {"command":"sync-workspace-info","flags":{"log_level":"debug"},"output_type":""} pid=99891
21:30:49 DEBUG starting: /Users/user/.databricks/labs/ucx/state/venv/bin/python3 /Users/user/.databricks/labs/ucx/lib/src/databricks/labs/ucx/cli.py {"command":"sync-workspace-info","flags":{"log_level":"debug"},"output_type":""} pid=99891
21:30:50 DEBUG [databricks.sdk] Loaded from environment
21:30:50 DEBUG [databricks.sdk] Ignoring pat auth, because databricks-cli is preferred
21:30:50 DEBUG [databricks.sdk] Ignoring basic auth, because databricks-cli is preferred
21:30:50 DEBUG [databricks.sdk] Ignoring metadata-service auth, because databricks-cli is preferred
21:30:50 DEBUG [databricks.sdk] Ignoring oauth-m2m auth, because databricks-cli is preferred
21:30:50 DEBUG [databricks.sdk] Ignoring azure-client-secret auth, because databricks-cli is preferred
21:30:50 DEBUG [databricks.sdk] Ignoring github-oidc-azure auth, because databricks-cli is preferred
21:30:50 DEBUG [databricks.sdk] Ignoring azure-cli auth, because databricks-cli is preferred
21:30:50 DEBUG [databricks.sdk] Ignoring external-browser auth, because databricks-cli is preferred
21:30:50 DEBUG [databricks.sdk] Attempting to configure auth: databricks-cli
21:30:50  INFO [databricks.sdk] Using Databricks CLI authentication
21:30:50  INFO [d.labs.ucx] Account ID: 
21:30:50 DEBUG [databricks.sdk] GET /api/2.0/accounts/2dsdsadsadsadsadsad
< 200 OK
< [
<   {
<     "account_id": "",
<     "azure_workspace_info": {
<       "resource_group": "dbx-rg",
<       "subscription_id": ""
<     },
<     "creation_time": 1709337050316,
<     "deployment_name": "adb-5675576.3",
<     "identity_federation_info": {
<       "enable_identity_federation": true
<     },
<     "location": "eastus",
<     "network_connectivity_config_id": "xxxxxx",
<     "pricing_tier": "PREMIUM",
<     "workspace_id": 123456789,
<     "workspace_name": "azdbx",
<     "workspace_status": "RUNNING",
<     "workspace_status_message": "Workspace is running."
<   },
<   "... (2 additional elements)"
< ]
21:30:50 DEBUG [databricks.sdk] Ignoring pat auth, because databricks-cli is preferred
21:30:50 DEBUG [databricks.sdk] Ignoring basic auth, because databricks-cli is preferred
21:30:50 DEBUG [databricks.sdk] Ignoring metadata-service auth, because databricks-cli is preferred
21:30:50 DEBUG [databricks.sdk] Ignoring oauth-m2m auth, because databricks-cli is preferred
21:30:50 DEBUG [databricks.sdk] Ignoring azure-client-secret auth, because databricks-cli is preferred
21:30:50 DEBUG [databricks.sdk] Ignoring github-oidc-azure auth, because databricks-cli is preferred
21:30:50 DEBUG [databricks.sdk] Ignoring azure-cli auth, because databricks-cli is preferred
21:30:50 DEBUG [databricks.sdk] Ignoring external-browser auth, because databricks-cli is preferred
21:30:50 DEBUG [databricks.sdk] Attempting to configure auth: databricks-cli
21:30:50  INFO [databricks.sdk] Using Databricks CLI authentication
21:30:50 DEBUG [databricks.sdk] Ignoring pat auth, because databricks-cli is preferred
21:30:50 DEBUG [databricks.sdk] Ignoring basic auth, because databricks-cli is preferred
21:30:50 DEBUG [databricks.sdk] Ignoring metadata-service auth, because databricks-cli is preferred
21:30:50 DEBUG [databricks.sdk] Ignoring oauth-m2m auth, because databricks-cli is preferred
21:30:50 DEBUG [databricks.sdk] Ignoring azure-client-secret auth, because databricks-cli is preferred
21:30:50 DEBUG [databricks.sdk] Ignoring github-oidc-azure auth, because databricks-cli is preferred
21:30:50 DEBUG [databricks.sdk] Ignoring azure-cli auth, because databricks-cli is preferred
21:30:50 DEBUG [databricks.sdk] Ignoring external-browser auth, because databricks-cli is preferred
21:30:50 DEBUG [databricks.sdk] Attempting to configure auth: databricks-cli
21:30:50 DEBUG [databricks.sdk] OAuth not configured or not available: cannot get access token: Error: cache: databricks OAuth is not configured for this host
21:30:50 DEBUG [databricks.sdk] Ignoring runtime auth, because databricks-cli is preferred
21:30:50 DEBUG [databricks.sdk] Ignoring google-credentials auth, because databricks-cli is preferred
21:30:50 DEBUG [databricks.sdk] Ignoring google-id auth, because databricks-cli is preferred
21:30:50 ERROR [d.l.ucx.sync-workspace-info] Failed to call sync-workspace-info: Traceback (most recent call last):
  File "/Users/user/.databricks/labs/ucx/state/venv/lib/python3.11/site-packages/databricks/sdk/config.py", line 442, in init_auth
    self._header_factory = self._credentials_provider(self)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.databricks/labs/ucx/state/venv/lib/python3.11/site-packages/databricks/sdk/credentials_provider.py", line 626, in __call__
    raise ValueError(
ValueError: cannot configure default credentials, please check https://docs.databricks.com/en/dev-tools/auth.html#databricks-client-unified-authentication to configure credentials for your preferred authentication method.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/user/.databricks/labs/ucx/state/venv/lib/python3.11/site-packages/databricks/labs/blueprint/cli.py", line 90, in _route
    cmd.fn(**kwargs)
  File "/Users/user/.databricks/labs/ucx/lib/src/databricks/labs/ucx/cli.py", line 90, in sync_workspace_info
    ctx.account_workspaces.sync_workspace_info()
  File "/Users/user/.databricks/labs/ucx/lib/src/databricks/labs/ucx/account.py", line 65, in sync_workspace_info
    for ws in self.workspace_clients(workspaces):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.databricks/labs/ucx/lib/src/databricks/labs/ucx/account.py", line 51, in workspace_clients
    ws = self.client_for(workspace)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.databricks/labs/ucx/lib/src/databricks/labs/ucx/account.py", line 40, in client_for
    return self._ac.get_workspace_client(workspace)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.databricks/labs/ucx/state/venv/lib/python3.11/site-packages/databricks/sdk/__init__.py", line 837, in get_workspace_client
    config.init_auth()
  File "/Users/user/.databricks/labs/ucx/state/venv/lib/python3.11/site-packages/databricks/sdk/config.py", line 447, in init_auth
    raise ValueError(f'{self._credentials_provider.auth_type()} auth: {e}') from e
ValueError: databricks-cli auth: cannot configure default credentials, please check https://docs.databricks.com/en/dev-tools/auth.html#databricks-client-unified-authentication to configure credentials for your preferred authentication method.
21:30:50  INFO completed execution pid=99891 exit_code=0

### Cloud

AWS

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by nkvuong** [comment]
when you run `databricks auth login --host https://adb-54fdfdf/`, it only authenticates at workspace-level. `sync-workspace-info` requires account-level authentication, so you need to run `databricks auth login --host https://accounts.azuredatabricks.net/`

**Comment by rkkalluri-dbx** [comment]
I have already run databricks auth login at account level --host https://accounts.azuredatabricks.net/ and the debug logs show it

11:47:26 DEBUG Using account-level login profile: accounts pid=4312
11:47:26 DEBUG Loading accounts profile from /Users/rk/.databrickscfg pid=4312 sdk=true
11:47:26 DEBUG Resolved login: Config: host=https://accounts.azuredatabricks.net/, account_id=xyz-763c-4895-9b4f-xyz, profile=accounts, config_file=/Users/rk/.databrickscfg pid=4312 sdk=true

**Comment by rkkalluri-dbx** [comment]
Little bit more context...it is able to list the workspaces at account level via API call.

11:47:26  INFO [databricks.sdk] Using Databricks CLI authentication
11:47:26  INFO [d.labs.ucx] Account ID: 12-763c-4895-9b4f-
11:47:27 DEBUG [databricks.sdk] GET /api/2.0/accounts/-763c-4895-9b4f-/workspaces
< 200 OK
< [
<   {
<     "account_id": "accopuntid-9162bf38",
<     "azure_workspace_info": {
<       "resource_group": "dbx-rg",
<       "subscription_id": "subid"
<     },
<     "creation_time": 1709337050316,
<     "deployment_name": "adb-12",
<     "identity_federation_info": {
<       "enable_identity_federation": true
<     },
<     "location": "eastus",
<     "network_connectivity_config_id": "nccoid",
<     "pricing_tier": "PREMIUM",
<     "workspace_id": 12345,
<     "workspace_name": "azdbx",
<     "workspace_status": "RUNNING",
<     "workspace_status_message": "Workspace is running."
<   },
<   "... (2 additional elements)"

**Comment by nkvuong** [comment]
I understand the issue now. Basically ucx lists all workspaces and constructs a new workspace client per workspace. It defaults to the same authentication method of the account client, i.e. databricks-cli, and failed.

The cleanest option here is to use az-cli auth instead of databricks-cli, either via an env variable or inside databrickscfg.

Will add this to our documentation & troubleshooting guide

**Comment by rkkalluri-dbx** [comment]
Thank you , I have tried az login with similar results….can you provide some more details on how I can troubleshoot

From: vuong-nguyen ***@***.***>
Date: Monday, April 29, 2024 at 2:00 PM
To: databrickslabs/ucx ***@***.***>
Cc: Rajesh Kalluri ***@***.***>, Author ***@***.***>
Subject: Re: [databrickslabs/ucx] [BUG]: OAuth not configured or not available: cannot get access token: Error: cache: databricks OAuth is not configured for this host (Issue #1574)

I understand the issue now. Basically ucx lists all workspaces and constructs a new workspace client per workspace. It defaults to the same authentication method of the account client, i.e. databricks-cli, and failed.

The cleanest option here is to use az-cli auth instead of databricks-cli, either via an env variable or inside databrickscfg.

Will add this to our documentation & troubleshooting guide

**Comment by nkvuong** [comment]
the debug log shows that you have an env variable `DATABRICKS_AUTH_TYPE`, so the sdk will default to that auth type. To force ucx to use azure-cli auth, you can run `DATABRICKS_AUTH_TYPE=azure-cli databricks labs ucx ...`

**Comment by nfx** [comment]
@ericvergnaud  if we get this error, look at `ws.config.auth_type` and if it's not `azure-cli`, create new instance of the workspace or account client with `auth_type="azure-cli"` and repeat the operation. if it's turns out too complicated to do so, re-wrap error message and tell end-user to invoke the same command as `DATABRICKS_AUTH_TYPE=azure-cli databricks labs ucx ...`.
