### ISSUE TITLE
[IMPROVEMENT] Handling hitting (default) quota of 200 storage credential

### ISSUE THREAD

**Issue by JCZuurmond** [databrickslabs/ucx#1600]
Our default quota for storage credential is 200, versus 500 for external location, so creating one access connector per storage account might hit quota limit for customers

_Originally posted by @nkvuong in https://github.com/databrickslabs/ucx/pull/1589#discussion_r1587437369_

**Comment by ericvergnaud** [comment]
I understand the concern, but is there a suggested solution ?

**Comment by JCZuurmond** [comment]
To be discussed, access connectors can be reused for multiple storage accounts, so we could create less. Though, we would need a strategy on how to group them. Typically, I would do this following a company's structure, like department and team. Another solution would be for the user to request a quota increase. 

As far as the work goes, we could first log that this will be an issue. So, after the user prompts to create an access connector for each storage account, then we warn this will fail if the quota is reached, maybe including a link to this issue. Then we wait for users to report back to us and based on their input decide how to handle this.

**Comment by nfx** [comment]
this should be a widget on the assessment dashboard. no need to overcomplicate this.
