### ISSUE TITLE
[BUG]: Error running "migrate-tables" - failed for getting token from AzureAD - UBER PRINCIPAL

### ISSUE THREAD

**Issue by gregorymiguel** [databrickslabs/ucx#1629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I found an issue when trying to execute the migrate-tables workflow.
The uber principal has been created and the policy was updated correctly with the uber credentials info.
All the 4 tasks returns with the same error:

![image](https://github.com/databrickslabs/ucx/assets/12303534/bf72e8cd-e7e3-4255-8a8a-5b53ad40b1db)
![image](https://github.com/databrickslabs/ucx/assets/12303534/b1a7ca07-bb2c-46a7-8f85-d8a5530a2349)

![image](https://github.com/databrickslabs/ucx/assets/12303534/5bdb7b95-78cf-4788-b715-f7e5d9351264)

Both clusters (main and migrate_tables) are using the policy created by create-uber-principal task.

Policy:
![image](https://github.com/databrickslabs/ucx/assets/12303534/e228de15-5b48-4c28-bf56-d023dfe3272e)

![image](https://github.com/databrickslabs/ucx/assets/12303534/95b2530d-3901-4976-9ea9-3243d55e2501)

### Expected Behavior

The cluster should be able to get AAD token using the uber principal credentials.

### Cloud

Azure

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by nkvuong** [comment]
@gregorymiguel this is similar to #1625 - could you also update the spn details for sql warehouse configuration in the meantime?

**Comment by gregorymiguel** [comment]
Hi @nkvuong ,

I added the spn config to the sql warehouse before opening this issue. It didn't work for me. 
I don't think the issue reported in #1625 is correct. The migrate-tables task doesn't use sql warehouse compute to execute the inner tasks. The clusters related to migrate-tables are Job Clusters and assigned to ucx compute policy.
I'm debugging the issue. I hope bringing you more information soon. Wish me luck! =)

**Comment by JCZuurmond** [comment]
Hi @gregorymiguel , thank you for being elaborate in your Gihub issues :) it's much appreciated. How are you doing on this bug?

I was thinking: could it be something simple like the single curly brackets in the secret instead of double curly brackets:

```
{secrets/ucx/uber_principal_secret}
```
should be
```
{{secrets/ucx/uber_principal_secret}}
```

**Comment by JCZuurmond** [comment]
@gregorymiguel : Could you confirm that the proposed solution solves your issue? Otherwise we need to investigate the issue further

**Comment by gregorymiguel** [comment]
Hi @JCZuurmond , 
Thank you! The solution proposed worked!

<img width="403" alt="image" src="https://github.com/databrickslabs/ucx/assets/12303534/79591f87-cb35-465d-9c4f-b24361069d49">
