### ISSUE TITLE
Workflow linter to analyse Egg library

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#1643]

**Comment by JCZuurmond** [comment]
@ericvergnaud : I did a quick research; I could not `pip install` an `.egg`. I think we need a separate resolver that:
1. Unzips the egg
2. Adds the unzipped code to the path
3. Process the `EGG-INFO` to install dependencies 

The process is similar to the existing `PIpResolver`. I recommend to avoid `easy_install` as [it is deprecated](https://setuptools.pypa.io/en/latest/history.html#v58-3-0) and not available in setuptools with later python versions (tested with python 3.11)

**Comment by ericvergnaud** [comment]
See https://setuptools.pypa.io/en/latest/deprecated/python_eggs.html
