### ISSUE TITLE
Workflow linter to analyse requirements.txt

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#1644]

**Comment by ericvergnaud** [comment]
@nfx Since we're already analyzing .egg #1643 , .whl #1640 and pypi libraries #1640, what is the usage scenario for this?

**Comment by JCZuurmond** [comment]
It is a different way to define dependencies that will reuse the logic from the PRs to install the dependencies

**Comment by ericvergnaud** [comment]
See https://docs.databricks.com/en/libraries/notebooks-python-libraries.html
