### ISSUE TITLE
Generalize config handling to the entire toolkit

### ISSUE THREAD

**Issue by larsgeorge-db** [databrickslabs/ucx#165]
Right now `MigrationConfig` is coming from the group migration code side. We should generalize this to be useful for all toolkits.

**Comment by nfx** [comment]
@larsgeorge-db is it about using the same config file for all the steps or making the configuration itself simpler?

**Comment by larsgeorge-db** [comment]
I think #264 is solving this. Yes, the idea is that the config is something that can be used in every step. Right now `MigrationConfig` is focused on the group migration step only. So we either add more settings for other steps to the same class and make it generally used, or we divide the config up for each step and probably do the same in the code.

**Comment by nfx** [comment]
@larsgeorge-db the plan is to flatten everything to one level, except `ConnectConfig`. We won't have hundreds of configuration options to justify any nesting needs and maintenance overhead

**Comment by larsgeorge-db** [comment]
Feel free to close this issue with the linked PR.
