### ISSUE TITLE
[BUG]: Error when running migrate-tables workflow. Views in an invalid state break the migrate-views task

### ISSUE THREAD

**Issue by gregorymiguel** [databrickslabs/ucx#1676]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Workflow: migrate-tables
task: migrate_views
Error: When the View is in an Invalid state in the hive_metastore and all dependencies have been successfully migrated, the "migration_view" task attempts to create the view in the target database, however, the view cannot be compiled due to a structural error, such as : referencing a column that does not exist in a table.

![image](https://github.com/databrickslabs/ucx/assets/12303534/1da7667d-6290-4c26-a53d-44f78604ed42)

![image](https://github.com/databrickslabs/ucx/assets/12303534/46f6a7e6-0135-43b2-a9a2-6bb82aa5ec36)

### Expected Behavior

I was expecting that the process would not fail completely.
Maybe a better approach would be log a message like: "The view XXXX cannot be migrated."

### Cloud

Azure

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by nkvuong** [comment]
@gregorymiguel could you share the log, or if even better, which function the code is failing on?

**Comment by gregorymiguel** [comment]
Sorry @nkvuong 
I should have sent you more details...
This was how I fixed at my side.

<img width="1054" alt="image" src="https://github.com/databrickslabs/ucx/assets/12303534/a3d9830f-9f54-4e2c-b2f3-0201dfeb8977">
