### ISSUE TITLE
[BUG]: posix flavour

### ISSUE THREAD

**Issue by aminmovahed-db** [databrickslabs/ucx#1677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

ImportError: cannot import name ‘_PosixFlavour’ from ‘pathlib’ (C:\Users\usernamexxx\AppData\Local\Programs\Python\Python312\Lib\pathlib.py)
This error appears to be related to a platform-specific implementation in the code, where _PosixFlavour (typically used in Unix-like environments) is being referenced in a context that is not compatible with Windows. 

### Cloud

AWS

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by JCZuurmond** [comment]
Hi @aminmovahed-db , thank you for reporting this bug. This issue should be solved by #1672, which unfortunately just missed the last release. It will become available in the next release. In the mean time, could you try installing from the main branch with `database labs install ucx@main`?
