### ISSUE TITLE
[BUG]: Linting raises library-not-found problem when import `type_extensions`

### ISSUE THREAD

**Issue by JCZuurmond** [databrickslabs/ucx#1707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We raise a library-not-found problem when import type_extentions

```
if TYPE_CHECKING:
    from typing_extensions import ParamSpec

    P = ParamSpec("P")
```

### Expected Behavior

No problem should be raised. Maybe we should white list this library

### Steps To Reproduce

1. Create unit test for above code snippet

### Cloud

Azure

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by ericvergnaud** [comment]
This happens when PathLookup is a mock because then it doesn't find typing_expensions,py.
Add a test in #1709
