### ISSUE TITLE
[BUG]: Acceptance tests cannot run for PR raised from forks

### ISSUE THREAD

**Issue by nkvuong** [databrickslabs/ucx#1725]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Acceptance tests cannot run for PR raised from forks
<img width="627" alt="image" src="https://github.com/databrickslabs/ucx/assets/44292934/8bece9cf-a71c-4cfb-9fc2-84a0ae6db853">

Issue is likely with `databrickslabs/sandbox/acceptance`

### Cloud

AWS

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by nfx** [comment]
works as intended, according to our threat model
