### ISSUE TITLE
[FEATURE]: Refactor `PipCell` into a `PipCommand`

### ISSUE THREAD

**Issue by JCZuurmond** [databrickslabs/ucx#1729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

The `%pip` magic command can be executed anywhere in a cell, it does not mark the whole cell to be a `PipCell` but a single line to be a `PipCommand`. The current implementation assumes that `%pip` is run at the beginning of the cell without other code before/after it (as it often is), however, it would be more accurate if the `PipCell` is refactored in a `PipCommand` that does not assume `%pip` is run without code around it.

Example

``` python
print("before pip install")
%pip install matplotlib
print("after pip install")
```

### Proposed Solution

See problem statement

**Comment by ericvergnaud** [comment]
Already done via #1905 , closing
