### ISSUE TITLE
[FEATURE]: Dashboard for post-migration reconciliation results

### ISSUE THREAD

**Issue by nkvuong** [databrickslabs/ucx#1736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

As part of #927, I also need a dashboard to summarise reconciliation results from UCX

### Proposed Solution

- The dashboard should show the outcome of the migration, including success metrics e.g. "% of tables/views/etc successfully migrated", "# of tables migrated". 
- Regression should also be shown, split into dataset mismatch, i.e. schema mismatch or row mismatch
- This dashboard should be built in Lakeview, to avoid tech debt

**Comment by JCZuurmond** [comment]
@nkvuong : This looks to be covered by the migration dashboard already. Please reopen this issue while specifying what exactly your are missing in the migration dashboard
