### ISSUE TITLE
[FEATURE]: Table migration process only logs errors to files, but not to migration status tables for further analysis

### ISSUE THREAD

**Issue by nkvuong** [databrickslabs/ucx#1754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

When running `migrate-tables` workflow, I want to know any failures, so that I can debug & re-run the process for those tables

### Proposed Solution

Capture error during table migration process - potentially to a separate table
For example:
https://github.com/databrickslabs/ucx/blob/4ea2b0bcc783233913e75b555af5e5ef244354a5/src/databricks/labs/ucx/hive_metastore/table_migrate.py#L216-L224
`logger.warning` is not enough, needs to also log the error to a ucx table, for further analysis

**Comment by nfx** [comment]
@nkvuong take a look at logs table - the last step of every workflow is adding records there. Select only the migration workflows. See assessment report for the reference
