### ISSUE TITLE
[BUG]: sync-workspace-info does not find workspace endpoint

### ISSUE THREAD

**Issue by william-conti** [databrickslabs/ucx#1762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running sync-workspace-info on latest release, the following issue occurs:

```
➜  ~ cat .databrickscfg
[ps-env-ucx]
host = https://workspace.ting.azuredatabricks.net/
account_id = secret_account_ting
```

```
➜  ~ databricks labs ucx sync-workspace-info
Using account profile: ps-env-ucx
13:36:02  INFO [databricks.sdk] Using Azure CLI authentication with AAD tokens
13:36:02  WARN [databricks.sdk] azure_workspace_resource_id field not provided. It is recommended to specify this field in the Databricks configuration to avoid authentication errors.
13:36:02  INFO [d.labs.ucx] Account ID: secret_account_ting
13:36:02 ERROR [d.l.ucx.sync-workspace-info] NotFound: Endpoint not found for /2.0/accounts/secret_account_ting/workspaces
```

This blocks table migration setup 

### Cloud

Azure

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by william-conti** [comment]
I've managed to make it run by changing my .databrickscfg with the following:

```
[ps-env-ucx]
host = https://accounts.azuredatabricks.net/
account_id = secret_account_ting
client_secret = secret_client_ting
client_id = secret_id_ting
```

This means that only SPs can run those commands on Azure, we should highlight this somewhere

**Comment by nfx** [comment]
@william-conti Upns also able to do it, you have used the wrong host

**Comment by FastLee** [comment]
We should consider documenting it. Running this command requires access to the account console.
The profile is the account profile and now workspace profile.
