### ISSUE TITLE
[BUG]: parse_logs yields AssertionError 

### ISSUE THREAD

**Issue by william-conti** [databrickslabs/ucx#1763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This behaviour occured on our internal environment in small workspace.
![Capture d’écran 2024-05-24 à 13 39 13](https://github.com/databrickslabs/ucx/assets/107417584/597e6a21-925b-46c5-82d6-0717af8fd395)

### Cloud

Azure

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by JCZuurmond** [comment]
Hi @william-conti , thank you for opening this issue. Could you share the logs that are being parsed? It is in the logs folder under the runs in the UCX installation. Top and bottom 5/10 lines is sufficient. Thanks
