### ISSUE TITLE
[FEATURE]: Let CLI commands run on a collection of workspaces

### ISSUE THREAD

**Issue by HariGS-DB** [databrickslabs/ucx#1782]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

Currently, ucx cli commands are run per workspace. With the introduction of collection concepts, the cli command should support the option to run commands on a collection of workspaces. This would help customers with large number of workspaces to run multiple cli cmds (like assessment , table mapping  etc) for a collection of workspaces and reduce effort

### Proposed Solution

 - Add a flag to mention the collection run
 - create workspace context for each workspace in the collection 
 - run the cli cmd for each workspace context
 - report status 
 - validate if running user has permission on all workspaces in the collection

### Additional Context

Eligible commands:
- [x] `ensure-assessment-run`: https://github.com/databrickslabs/ucx/pull/1925
- [x] `create-table-mapping`: https://github.com/databrickslabs/ucx/pull/2602
- [x] `principal-prefix-access`: https://github.com/databrickslabs/ucx/pull/2450
- [x] `migrate-credentials`: https://github.com/databrickslabs/ucx/pull/2532
- [x] #2605
- [x] #2606
- [x] #2607
- [x] #2608
- [x] #2609
- [x] #2610
- [x] #2611
- [x] #2612
- [x] #2613

**Comment by JCZuurmond** [comment]
@HariGS-DB and @nfx : Could you review the list of eligible commands
- Prioritize them by moving the bullets up or down
- Remove commands for which we do not have to implement this functionality (for now)
- Add missing commands

**Comment by HariGS-DB** [comment]
> @HariGS-DB and @nfx : Could you review the list of eligible commands
> 
> * Prioritize them by moving the bullets up or down
> * Remove commands for which we do not have to implement this functionality (for now)
> * Add missing commands

The commands I have listed in the description are the eligible commands where collection is applicable. We should ideally have this support for all the cmd mentioned. We should implement them as per the process of how each cmd will likely be used. I have updated the order based on my understanding of how critical it is
