### ISSUE TITLE
[FEATURE]: Enable download and upload of ucx files for a collection of workspaces

### ISSUE THREAD

**Issue by HariGS-DB** [databrickslabs/ucx#1783]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

Currently, for various ucx commands, there require an option for the user to edit some files (Ex: azure_storage_account_info, uc_roles_access, mapping.csv, aws_instance_profile_info). Currently these files are edited per workspace. For customers having multiple workspaces we have introduced the concept of collection where they could run cli cmd for a collection of workspaces. These customers would also like the option to edit the files for a collection at one go by downloading them locally , editing them, syncing them back in the respective workspace.  

### Proposed Solution

Add cli cmd to download a file for a given collection
download the file by combining the data from all the workspaces in a collection include workspace ID if not
user uploads the data through cli command
sync the data in each workspace based on workspace id

**Comment by JCZuurmond** [comment]
Implemented; see linked PRs
