### ISSUE TITLE
[FEATURE]: Add ability to query inventory database data for a collection of workspaces at once

### ISSUE THREAD

**Issue by HariGS-DB** [databrickslabs/ucx#1784]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

Currently all reporting of UCX data is done in dashboards created per workspace. With the introduction of collection, user would like to query the inventory data for a collection of workspaces at once. ,

### Proposed Solution

To be decided:
 - Extend the cli cmd report_account_compatibility to add additional inventory database query option
 - use an existing workspace in a collection as the designated workspace to store inventory data from all workspace
 - any other options

**Comment by nfx** [comment]
fixed in https://github.com/databrickslabs/ucx/commit/2bd859e9698f82120f955e9cf8c070e049adf926
