### ISSUE TITLE
[FEATURE]: New dashboard widget for source table type per location type

### ISSUE THREAD

**Issue by anjalijain-db** [databrickslabs/ucx#1916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

In dashboard separate section for table counts summary by **type (external/managed)**, **location (dbfs root/mount/cloud) and format (delta, parquet etc)** is required.
Currently this needs to be manually created by downloading the full details.

### Proposed Solution

In dashboard if we have a summary like below it would be really helpful 
<img width="432" alt="image" src="https://github.com/databrickslabs/ucx/assets/153831300/7fb39b8d-0012-4800-80e1-ea97ef11c1ff">

**Comment by nfx** [comment]
Thank you for the feature request! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.

Essentially, it's just a SQL fine, that would get turned into a dashboard widget
