### ISSUE TITLE
[BUG]: Handle empty string in Group Migration Regex subsitution

### ISSUE THREAD

**Issue by anjalijain-db** [databrickslabs/ucx#1922]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For group migration  choosing a strategy "Regex substitution".  All the ws group names have suffix "_old". Need to remove it to map to account name

**ws group name** : AZ-BackOfficeTech-QA_old
**Acc group Name** : AZ-BackOfficeTech-QA
**Enter a regular expression for substitution**: '_old'
**Enter the substitution value**: ''
I am trying to remove/subsitute  **_old** with **blank**

![image](https://github.com/databrickslabs/ucx/assets/153831300/dc2b5261-4871-4990-8c71-419ea037cbae)
![image](https://github.com/databrickslabs/ucx/assets/153831300/ee49af4e-57d2-42a7-8613-41b9f3df72e4)
I think in code if replace_regex is empty or '' it's not a valid input

![Uploading image.png…]()

### Expected Behavior

**ws group name** : AZ-BackOfficeTech-QA_old
**Acc group Name** : AZ-BackOfficeTech-QA
Using above ws_group_name **AZ-BackOfficeTech-QA_old** should map to acc group name **AZ-BackOfficeTech-QA**

### Cloud

Azure

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by JCZuurmond** [comment]
@anjalijain-db : Thank you for opening this issue. I will look into it. In your comment above it `Uploading image png...`, I guess you submitted the issue before a picture was uploaded to Github. Could you verify that? And reupload the picture in case it is missing?

**Comment by anjalijain-db** [comment]
@JCZuurmond below is the image 
![image](https://github.com/databrickslabs/ucx/assets/153831300/df52ade9-812d-4801-ad6a-851f3e063bec)

**Comment by JCZuurmond** [comment]
@anjalijain-db : Thanks. Your hypothesis was correct, see #1953 for the changes.

If you have the time, could you verify everything is working as expected by installing the fix `databricks labs install ucx@fix/replacing-with-empty-regex`, then running your script again? 

In any case, the changes become available after reviewing and release.
