### ISSUE TITLE
[FEATURE]: Pre-process packages available via the DBR without installation

### ISSUE THREAD

**Issue by asnare** [databrickslabs/ucx#1931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

The various DBR runtimes include many packages[^1] that are always available and do not need to be installed or declared by notebooks (or jobs): they can simply be used. At present our dependency tracking isn't aware of these.

[^1]: As an example, here is the [list of packages for DBR 14.3](https://docs.databricks.com/en/release-notes/runtime/14.3lts.html#installed-python-libraries).

### Proposed Solution

The packages included in the various DBR versions should be included in the list of known packages that we maintain.

### Additional Context

The published lists for each DBR version are roughly correct; it turns out that the base OS images used also include some packages. I've scanned most of the currently supported DBR versions (9.1, 10.4, 11.3, 12.2, 13.3, 14.1, 14.2, 14.3, 15.1 & 15.2) and produced [this list](https://github.com/user-attachments/files/15967257/dbr-packages.txt) of installed pip packages and the various versions in use across these runtimes.

**Comment by JCZuurmond** [comment]
I am oké with a "good enough" approach. Great to have full coverage of the pre-installed packages, but good enough to get 80%.

**Comment by JCZuurmond** [comment]
Use `make known` to update the known.json
