### ISSUE TITLE
[FEATURE]: Remove skipped tables/schemas through CLI

### ISSUE THREAD

**Issue by maruppel** [databrickslabs/ucx#1938]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

Can currently skip schemas/tables but doesn't seem to be anyway to remove skip table properties from CLI.

### Proposed Solution

Add additional parameter to skip command to restore the object, or created new command unskip.

**Comment by JCZuurmond** [comment]
@maruppel : Could you please clarify the issue? I am not understanding it well enough. 

> remove skip table properties

You want functionality to remove table properties set by ucx?

**Comment by maruppel** [comment]
It seems we can set the property: ((databricks.labs.ucx.skip, true)) but as far as I can tell, there is no way to unset without running an ALTER in the UI. Additionally it seems only empty string constitutes as a false, ie the table is still skipped when the value is set as ((databricks.labs.ucx.skip, false)).
