### ISSUE TITLE
[FEATURE]: Tag migrated clusters/jobs/dlts and provide a dashboard of percentage of those that were migrated or remaining

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#2073]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

- When run, validate post-migration workloads against their pre-migration counterparts. This could take the form of completeness e.g. has the migration of assets occurred AND/OR a separate process to measure successful execution of migrated workloads. These should be split processes.

# Stretch goal
- Monitor failure rate of jobs that was migrated to UC after migration
- Show a view of the outcome of the migration, including rollup success metrics e.g. "% of workflows/clusters/policies/etc successfully migrated", "# of workflows/jobs migrated". Regression can be classified as workflow-related asset migration failure for the asset migration AND/OR metrics related to the success/failure of workflow execution post-migration. Failures can be detected by capturing failures from the workflow asset migration tooling in UCX (pending) as well as failures upon first run of migrated assets.

### Proposed Solution

Add new tag: `UcxMigratedOn: <date>`, which would be added by automation and could also be done manually

**Comment by JCZuurmond** [comment]
@nfx : Is this issue still relevant as we decided not to use tagging and rely on reassesing if a migration is still pending for a resource, see https://github.com/databrickslabs/ucx/issues/2074

**Comment by nfx** [comment]
not relevant, see #2074
