### ISSUE TITLE
[TECH DEBT] Document the lint problems

### ISSUE THREAD

**Issue by JCZuurmond** [databrickslabs/ucx#2122]
Similar to the [assessment findings index](https://github.com/databrickslabs/ucx/blob/main/docs/assessment.md#assessment-finding-index), create an index for the lint problems detailing the:
- code
- message
- solution

# Child issues
- [ ] #2117

_Originally posted by @mohanab-db in https://github.com/databrickslabs/ucx/issues/2104#issuecomment-2218761719_

**Comment by JCZuurmond** [comment]
@FastLee is looking into this, could you please provide an update?

**Comment by nfx** [comment]
fixed in https://github.com/databrickslabs/ucx/commit/f7d793d126e0b3f8af37a41a948013ea81340b9d
