### ISSUE TITLE
Allow empty group filter in `install.py` 

### ISSUE THREAD

**Issue by larsgeorge-db** [databrickslabs/ucx#216]
The script right now wants users to enter a list of groups to migrate. Allow to not enter anything to trigger the automatic discovery of groups instead.

**Comment by larsgeorge-db** [comment]
@nfx you mentioned there is an issue with the auto discovery of groups? I thought I heard you saying that yesterday, please chime in here.

**Comment by nfx** [comment]
@larsgeorge-db auto-discovery of groups doesn't work properly now
