### ISSUE TITLE
Improve switch from install script to browser to be less jarring

### ISSUE THREAD

**Issue by larsgeorge-db** [databrickslabs/ucx#220]
Right now when choosing to have the install script to open the config in the browser, the user is distracted away from the install process and must find their way back. Also, it is unclear what they can do with the config in the browser. Improve this process.

**Comment by zpappa** [comment]
Do you have a suggestion how this could be improved @larsgeorge-db

**Comment by nfx** [comment]
There were no reports on this from customers in couple of months, closing. Feel free to reopen when it's relevant again
