### ISSUE TITLE
[BUG]: UCX assessment not working 

### ISSUE THREAD

**Issue by taherusk777** [databrickslabs/ucx#2203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

run failed with error message
 Library installation failed for library due to user error for whl: "/Workspace/Applications/ucx/wheels/databricks_labs_ucx-0.28.2-py3-none-any.whl"
 Error messages:
Library installation attempted on the driver node of cluster 0717-175847-nze68msj and failed. Pip could not find a version that satisfies the requirement for the library. Error Code: NO_MATCHING_DISTRIBUTION_ERROR. Error Message: org.apache.spark.SparkException: Process List(/bin/su, libraries, -c, bash /local_disk0/.ephemeral_nfs/cluster_libraries/python/python_start_clusterwide.sh /local_disk0/.ephemeral_nfs/cluster_libraries/python/bin/pip install --upgrade /local_disk0/tmp/addedFile0cb975ae25f14604b26c4d1f6446bea72863393583401111800/databricks_labs_ucx-0.28.2-py3-none-any.whl --disable-pip-version-check) exited with code 1. WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after conne ...
***WARNING: message truncated. Skipped 1609 bytes of output**

### Expected Behavior

UCX Assessment should be completed without any errors 

### Steps To Reproduce

No response

### Cloud

Azure

### Operating System

Linux

### Version

latest via Databricks CLI

### Relevant log output

```shell
run failed with error message
 Library installation failed for library due to user error for whl: "/Workspace/Applications/ucx/wheels/databricks_labs_ucx-0.28.2-py3-none-any.whl"
 Error messages:
Library installation attempted on the driver node of cluster 0717-175847-nze68msj and failed. Pip could not find a version that satisfies the requirement for the library. Error Code: NO_MATCHING_DISTRIBUTION_ERROR. Error Message: org.apache.spark.SparkException: Process List(/bin/su, libraries, -c, bash /local_disk0/.ephemeral_nfs/cluster_libraries/python/python_start_clusterwide.sh /local_disk0/.ephemeral_nfs/cluster_libraries/python/bin/pip install --upgrade /local_disk0/tmp/addedFile0cb975ae25f14604b26c4d1f6446bea72863393583401111800/databricks_labs_ucx-0.28.2-py3-none-any.whl --disable-pip-version-check) exited with code 1. WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after conne ...
***WARNING: message truncated. Skipped 1609 bytes of output**
```

**Comment by nfx** [comment]
@taherusk777 please provide more log messages from `/Workspace/Applications/ucx/logs/assessment` folder. it's not clear what library is missing

**Comment by JCZuurmond** [comment]
@taherusk777 : Please provide more logs and make sure you use the latest version of ucx
