### ISSUE TITLE
[FEATURE]: Grants Migration for DB objects(schema, catalog,tables)

### ISSUE THREAD

**Issue by anjalijain-db** [databrickslabs/ucx#2204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

Assign the same grants to groups as  on HMS DB objects after migration to UC

### Proposed Solution

Assign same grants to groups as on HMS on DB objects after migration to UC

**Comment by nfx** [comment]
it's implemented as part of `migrate-tables` workflow.

**Comment by biswadeepupadhyay-db** [comment]
Hi There, so currently I'm running UCX v0.33.0 and would like to understand what I might be doing wrong as my HMS ACLs are not reflecting on UC catalog/schema/tables. To begin with I see data getting populated on all the relevant inventory tables i.e `ucx.groups`, `ucx.permissions`, `ucx.grants`   etc properly to my knowledge. I tested 2 usecases so far with UCX  : external tables as well as dbfs root managed, and for both of them, I see the UC permissions tab is completely empty. To add, My Group Migration workflow successfully takes care of replacing the workspace groups with account level groups and also reflects the ACLs with new account level groups on my HMS tables as expected.
Also adding the logs from `migrate-tables` workflow :

`08:47:33 DEBUG [databricks.labs.lsql.backends] {migrate_tables_3} [spark][execute] ALTER TABLE beepz_stream_stage.reviews_stream_stage.reviews_silver OWNER TO `biswadeep.upadhyay@... (15 more bytes)
08:47:33 DEBUG [databricks.labs.ucx.hive_metastore.table_migrate] {migrate_tables_2} Migrating acls on beepz_live_stage.ratings_live_staging.ratings_bronze using SQL query: ALTER TABLE beepz_live_stage.ratings_live_staging.ratings_bronze OWNER TO `biswadeep.upadhyay@databricks.com`
08:47:33 DEBUG [databricks.labs.lsql.backends] {migrate_tables_2} [spark][execute] ALTER TABLE beepz_live_stage.ratings_live_staging.ratings_bronze OWNER TO `biswadeep.upadhyay@da... (13 more bytes)
08:47:33 DEBUG [databricks.labs.ucx.hive_metastore.table_migrate] {migrate_tables_1} Migrating acls on beepz_live_stage.ratings_live_staging.ratings_silver using SQL query: ALTER TABLE beepz_live_stage.ratings_live_staging.ratings_silver OWNER TO `biswadeep.upadhyay@databricks.com`
08:47:33 DEBUG [databricks.labs.lsql.backends] {migrate_tables_1} [spark][execute] ALTER TABLE beepz_live_stage.ratings_live_staging.ratings_silver OWNER TO `biswadeep.upadhyay@da... (13 more bytes)
08:47:34 INFO [databricks.labs.blueprint.parallel] {migrate_tables_0} migrate tables 4/4, rps: 0.051/sec
08:47:34 INFO [databricks.labs.blueprint.parallel] {MainThread} Finished 'migrate tables' tasks: 100% results available (4/4). Took 0:01:18.006780 `

<img width="1590" alt="image" src="https://github.com/user-attachments/assets/d029d4a3-9e23-4479-8f1b-3bf2e4b0a7b0">
<img width="1592" alt="image" src="https://github.com/user-attachments/assets/70a60633-3a05-4d34-8bb3-162756bd1053">
<img width="1589" alt="image" src="https://github.com/user-attachments/assets/b5f67597-1fe3-4d7c-b93c-903e61c060d4">
<img width="1582" alt="image" src="https://github.com/user-attachments/assets/1e8cdbd1-d57f-4547-a159-20fe158ee3dd">
<img width="1591" alt="image" src="https://github.com/user-attachments/assets/0557db80-3add-4693-83d2-32cf7bad5191">
<img width="1596" alt="image" src="https://github.com/user-attachments/assets/2b01ef46-fe44-4eb9-b620-41020f7bba94">
