### ISSUE TITLE
[BUG]: UCX table migration workflow does not create target table schemas correctly. It renames column names to lowercase

### ISSUE THREAD

**Issue by bwreeves** [databrickslabs/ucx#2218]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

UCX table migration workflow does not create target table schemas correctly. It renames column names to lowercase.

### Expected Behavior

UCX table migration workflow is expected to create target tables with the exact same column names. 

### Steps To Reproduce

1. Run the assessment workflow
2. Run the table migration workflow
3. Run the data reconciliation workflow.
4. Source / target column names do not match for some tables due to lowercase names. 

### Cloud

AWS

### Operating System

macOS

### Version

latest via Databricks CLI

### Relevant log output

```shell
[{"is_matching":false,"notes":"Column is missing in target","source_column":"100g_USD","source_datatype":"double","target_column":null,"target_datatype":null},
{"is_matching":false,"notes":"Column is missing in source","source_column":null,"source_datatype":null,"target_column":"100g_usd","target_datatype":"double"},
```

**Comment by pritishpai** [comment]
Unable to recreate
