### ISSUE TITLE
[BUG]: Unable to run code assessment 

### ISSUE THREAD

**Issue by harsingh-jnpr** [databrickslabs/ucx#2221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

version - 0.28.2
I would like to get the code blocks which needs to be changed before we move to UC. Code assessment command is describing all the hive metastore tables before it gets to actual assessment(screenshot 1). This was not the case with previous version. 

During the code assessment, I observed that is doesn't describe the actual change(screenshot 2) as well as it fails with below error(screenshot 3)- 
ERROR [d.l.ucx.lint-local-code] RecursionError: maximum recursion depth exceeded

Second time it showed a different error (screenshot 4) - 
ERROR [d.l.ucx.lint-local-code] KeyError: PYTHON: import pandas as pd

I am attaching all the screenshots. 

<img width="1012" alt="Screenshot 1" src="https://github.com/user-attachments/assets/b79d34b6-48f7-41c5-84bc-5c425d9a3b7e">
<img width="855" alt="Screenshot 2" src="https://github.com/user-attachments/assets/a1fb1692-8423-4b1d-b09c-1fedfe6f815c">
<img width="982" alt="Screenshot 3" src="https://github.com/user-attachments/assets/6c884056-d936-48a7-a520-14d8299282af">
<img width="894" alt="Screenshot 4" src="https://github.com/user-attachments/assets/fee8d1b5-31c5-4eba-9fe7-f1708d8f3ff6">

### Expected Behavior

To get detailed assessment of code review.

### Steps To Reproduce

Run this command inside the root folder of the local repo - 
databricks labs ucx lint-local-code

### Cloud

AWS

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by nfx** [comment]
for those who implement - create an empty migration index when an exception occurs
