### ISSUE TITLE
[BUG]: Unable to update UCX/reinstall UCX /run UCX commands in Databricks CLI

### ISSUE THREAD

**Issue by DomCookie** [databrickslabs/ucx#2223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
PS C:\UC_Linting\uc_linting_helper_tool> databricks labs install ucx
Traceback (most recent call last):
  File "C:\Users\DominicCooke\.databricks\labs\ucx\lib\src\databricks\labs\ucx\install.py", line 27, in <module>
    from databricks.labs.lsql.dashboards import DashboardMetadata, Dashboards
  File "C:\Users\DominicCooke\.databricks\labs\ucx\state\venv\Lib\site-packages\databricks\labs\lsql\dashboards.py", line 305, in <module>
    @dataclass
     ^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\dataclasses.py", line 1275, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\dataclasses.py", line 1265, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\dataclasses.py", line 994, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\dataclasses.py", line 852, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'databricks.labs.lsql.lakeview.model.Position'> for field _position is not allowed: use default_factory
Error: installer: exit status 1
```

### Expected Behavior

![image](https://github.com/user-attachments/assets/ba61dc80-9293-46a4-bdcc-d33d4023e67c)

### Steps To Reproduce

Run "databricks labs install ucx" on databricks CLI (Databricks CLI v0.223.1), having connected to a specific Databricks workspace. 
OR, running "databricks labs ucx lint-local-code" --> Same Error. 

### Cloud

Azure

### Operating System

Windows

### Version

latest via Databricks CLI

**Comment by asnare** [comment]
@DomCookie: Did you have a previous version of UCX installed, is this an upgrade?

I'm curious about the versions of (internal) libraries that it has installed. Can you try listing them? I think this will work:
```
C:\Users\DominicCooke\.databricks\labs\ucx\state\venv\Scripts\pip freeze
```

**Comment by asnare** [comment]
The reason I'm interested in the library versions is that a fresh install (linux):
1. works for me;
2. has a line offset of 2 for the code in the backtrace, indicating a different library version:

> Traceback (most recent call last):
>   File "C:\Users\DominicCooke\.databricks\labs\ucx\lib\src\databricks\labs\ucx\install.py", line 27, in <module>
>     from databricks.labs.lsql.dashboards import DashboardMetadata, Dashboards
>   File "C:\Users\DominicCooke\.databricks\labs\ucx\state\venv\Lib\site-packages\databricks\labs\lsql\dashboards.py", line 305, in <module>
>     @dataclass
>      ^^^^^^^^^

**Comment by DomCookie** [comment]
Yes i did, have a previous version of DB CLI, i was running "databricks labs ucx lint-local-code" on my Workspace on ucx v0.28.3, since i updated to v0.30.0 i have experienced this error. I have not used any other tools on the CLI other than ucx. I'll give it a fresh install now and see if it still persists.

**Comment by sagpra** [comment]
Hi, I'm also facing issue in Mac

**Comment by JCZuurmond** [comment]
Fixing this in the cli: https://github.com/databricks/cli/pull/1624

**Comment by JCZuurmond** [comment]
Workaround until new Datbricks cli release:

1. Delete the old ucx manually: `rm -rf ~/.databricks/labs/ucx`
2. Install the latest ucx version: `databricks labs install ucx`

**Comment by nfx** [comment]
Please upgrade CLI to v0.224.1 https://github.com/databricks/cli/pull/1627

**Comment by JCZuurmond** [comment]
Verified that this works with the changes from: https://github.com/databricks/cli/pull/1624. Please let us know if the issue persists
