### ISSUE TITLE
[FEATURE]: More comprehensive view of different table storage patterns.

### ISSUE THREAD

**Issue by souravbaner-da** [databrickslabs/ucx#2237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

UCX Assessment should provide a more comprehensive view of different table storage patterns, which can be used as input for Catalog Design on the cx side.

### Proposed Solution

UCX Assessment should provide a more comprehensive view of different table storage patterns, which can be used as input for Catalog Design on the cx side.

**Comment by nfx** [comment]
@souravbaner-da would this widget help? https://github.com/databrickslabs/ucx/commit/c89ba692177b6762cc6c6ae9dfa34586b2a86874
