### ISSUE TITLE
Make CrawlerBase more resilient

### ISSUE THREAD

**Issue by FastLee** [databrickslabs/ucx#226]
- CrawlerBase persistence can't handle special characters
- CrawlerBase persistence can't handle big data sets

**Comment by nfx** [comment]
> CrawlerBase persistence can't handle big data sets

Please define "big"?

**Comment by nfx** [comment]
> CrawlerBase persistence can't handle special characters

These are two separate issues. Please also be concrete in the bug report

**Comment by FastLee** [comment]
10K Records or more

**Comment by nfx** [comment]
okay, that's `StatementExecutionBackend`, will issue a fix shortly.
