### ISSUE TITLE
Handle failure restart ability of code

### ISSUE THREAD

**Issue by HariGS-DB** [databrickslabs/ucx#23]
Meaning: start clean with the upgrade process, measure where we are with the upgrade compared to ideal state.

Applies to everything:

- [ ] group migration
- [ ] DDL migration
- [ ] assessment

**Comment by nfx** [comment]
@HariGS-DB please expand the description of the ticket

**Comment by HariGS-DB** [comment]
@nfx This is issue is similar to https://github.com/databrickslabs/ucx/issues/84
and https://github.com/databrickslabs/ucx/issues/38 may be we could merge these to one?

**Comment by nfx** [comment]
not enough information, need specific tickets
