### ISSUE TITLE
Running jobs out of order does not give a clear error message

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#232]
When running `migrate groups` before `assessment` finished successfully, the user gets `[TABLE_OR_VIEW_NOT_FOUND] The table or view hive_metastore.ucx.permissions cannot be found.`, even though the error message should have been different.

**Comment by HariGS-DB** [comment]
@nfx Could you give more details here . By migrate groups do we mean the 002-apply-permissions-to-backup-groups?
