### ISSUE TITLE
When Running for Migrating specific groups the inventorize_permissions() runs for all users

### ISSUE THREAD

**Issue by dipankarkush-db** [databrickslabs/ucx#233]
When running for specific group the inventorize permission runs for every user and group, even tough the users do not belong to the group. This is not allowing to test the process for a quick run or even for use cases when someone wants to just migrate few groups. Especially it asks for the groups and that creates a notion that the process is only going to run for the specific group.

**Comment by nfx** [comment]
We have to crawl the entire workspace, as we don't have any APIs to get permissions for a single group
