### ISSUE TITLE
[BUG]: `create-missing-principals`, `create-uber-principal`, `migrate-credentials` commands have to cleanup/resumability

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#2337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`create-missing-principals`, `create-uber-principal`, `migrate-credentials` commands create residue roles/policies/etc.

### Expected Behavior

Whenever one of these commands fails, we have to cleanup any residue created by those commands. 

### Linked issues
Split into:
- [ ] #2358
- [ ] #2360
- [ ] #2362

**Comment by JCZuurmond** [comment]
Split the bug out into three bugs, this bug is resolved by resolving those bugs, keeping this issue open for tracking purposes
