### ISSUE TITLE
[FEATURE]: Account group and workspace group members sync

### ISSUE THREAD

**Issue by anishkanth-db** [databrickslabs/ucx#2366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

The same workspace group name is used across DEV, UAT, and PROD workspaces. As per the client's request, there should be a single account group assigned to all environment workspaces. If the group already exists in the account, its members should be synced with the PROD workspace group.

### Proposed Solution

A new functionality is needed: If the account group already exists with the same name as the workspace group, sync its members with the workspace group.

**Comment by nfx** [comment]
@anishkanth-db make sure to run the group migration workflow - we remap workspace groups to account groups and their permissions https://github.com/databrickslabs/ucx?tab=readme-ov-file#group-migration-workflow
