### ISSUE TITLE
[BUG]: I would like to lint local code, locally, literally

### ISSUE THREAD

**Issue by rwforest** [databrickslabs/ucx#2378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I try to run `databricks labs ucx lint-local-code`, it will try to hit a Datarbricks instance via profile. If I don't setup my profile or my token is invalid, it would throw an error:

(.venv) yipman@jasons-mbp-2 flight_delay % databricks labs ucx lint-local-code
Which file or directory do you want to lint? (default: /Users/yipman/Downloads/flight_delay/flight_delay): 
00:09:06  INFO [d.l.u.framework.utils] Invoking command: ['pip', '--disable-pip-version-check', 'install', '-r', '/Users/yipman/Downloads/flight_delay/flight_delay/requirements.txt', '-t', '/private/var/folders/fz/zkvh37qx3kdcv_8w1sw8kckm0000gn/T/ucx-_qoz88sx']
00:10:26  INFO [d.l.u.framework.utils] Invoking command: ['pip', '--disable-pip-version-check', 'install', '-r', '/Users/yipman/Downloads/flight_delay/flight_delay/requirements.txt', '-t', '/private/var/folders/fz/zkvh37qx3kdcv_8w1sw8kckm0000gn/T/ucx-_qoz88sx']
00:10:41  INFO [d.l.u.framework.utils] Invoking command: ['pip', '--disable-pip-version-check', 'install', '-r', '/Users/yipman/Downloads/flight_delay/flight_delay/requirements.txt', '-t', '/private/var/folders/fz/zkvh37qx3kdcv_8w1sw8kckm0000gn/T/ucx-_qoz88sx']
00:10:55 ERROR [d.l.ucx.lint-local-code] PermissionDenied: Invalid access token. Config: host=https://adb-xxxxxxxxx.azuredatabricks.net, token=***, auth_type=pat. Env: DATABRICKS_HOST, DATABRICKS_TOKEN

### Expected Behavior

This command should not attempt to make any external connections and just lint the code locally as the command name suggested.

### Steps To Reproduce

(.venv) yipman@jasons-mbp-2 flight_delay % databricks labs ucx lint-local-code
Which file or directory do you want to lint? (default: /Users/yipman/Downloads/flight_delay/flight_delay): 
00:09:06  INFO [d.l.u.framework.utils] Invoking command: ['pip', '--disable-pip-version-check', 'install', '-r', '/Users/yipman/Downloads/flight_delay/flight_delay/requirements.txt', '-t', '/private/var/folders/fz/zkvh37qx3kdcv_8w1sw8kckm0000gn/T/ucx-_qoz88sx']
00:10:26  INFO [d.l.u.framework.utils] Invoking command: ['pip', '--disable-pip-version-check', 'install', '-r', '/Users/yipman/Downloads/flight_delay/flight_delay/requirements.txt', '-t', '/private/var/folders/fz/zkvh37qx3kdcv_8w1sw8kckm0000gn/T/ucx-_qoz88sx']
00:10:41  INFO [d.l.u.framework.utils] Invoking command: ['pip', '--disable-pip-version-check', 'install', '-r', '/Users/yipman/Downloads/flight_delay/flight_delay/requirements.txt', '-t', '/private/var/folders/fz/zkvh37qx3kdcv_8w1sw8kckm0000gn/T/ucx-_qoz88sx']
00:10:55 ERROR [d.l.ucx.lint-local-code] PermissionDenied: Invalid access token. Config: host=https://adb-xxxxxx.azuredatabricks.net, token=***, auth_type=pat. Env: DATABRICKS_HOST, DATABRICKS_TOKEN

### Cloud

Azure

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by ericvergnaud** [comment]
@rwforest thanks for this. Are you able to share the `requirements.txt` file that seems to be triggering the issue ?

**Comment by rwforest** [comment]
(.venv) ***@***.*** flight_delay % cat requirements.txt
mlflow==2.7.1
numpy>=1.23.0
pandas==1.5.3
scikit-learn>=1.1.1
matplotlib>=3.5.2
pillow>=10.0.1
Jinja2==3.0.3
pyspark~=3.3.0
pytz~=2022.2.1
pytest>=7.1.2

**Comment by nfx** [comment]
@rwforest you have to use a valid Databricks CLI auth profile to install UCX and to use this command

**Comment by rwforest** [comment]
I know.. I was just saying can we just do it locally without connecting to
any Databricks? If it's a hard requirement then I will live with it

**Comment by ericvergnaud** [comment]
UCX requires access to infrastructure. Closing as `won't fix`
