### ISSUE TITLE
[TECH DEBT] Update the signature of `_is_migrated` function to only get table names as input

### ISSUE THREAD

**Issue by aminmovahed-db** [databrickslabs/ucx#2397]
On one hand, I would like this method to have the following signature: `_is_migrated(self, table: Table) -> bool`. To me that makes more sense, it is "better" OO programming and it is probably more future proof (what if we want to include the catalog at some point).

On the other hand, I do not think you have to change it because: i) the `index.is_migrated` has the same signature, so it is better to be consitent now, log this as a (small) tech debt issue and do refactoring in a separate PR. (We prefer to separate refactoring from feature implementation.) and ii) it is a hidden method, therefore we can refactor the signature without worrying about changing the public API

_Originally posted by @JCZuurmond in https://github.com/databrickslabs/ucx/pull/2205#discussion_r1706541771_

**Comment by JCZuurmond** [comment]
@aminmovahed-db : could you link the code location and update the first comment to follow our template issue structure?
