### ISSUE TITLE
[BUG]: Clickable link printed by `lint-local-code` does not work when file contains leading numbers

### ISSUE THREAD

**Issue by JCZuurmond** [databrickslabs/ucx#2408]
### Current Behavior

Clickable link printed by `lint-local-code` does not work when file contains 

### Expected Behavior

Link should work

### Steps to reproduce

1. Clone: https://github.com/databricks-industry-solutions/segmentation
2. Run lint-local-code on the project
3. Note links to files with leading numbers

**Comment by JCZuurmond** [comment]
Probably something that we should not fix

**Comment by FastLee** [comment]
Is there a simple way to escape the file name?
