### ISSUE TITLE
[FEATURE]: Add a tracker for jobs migrated / unmigrated to UC

### ISSUE THREAD

**Issue by william-conti** [databrickslabs/ucx#2411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

With the addition of system tables support in UCX, we can tell at the account level all jobs that must be migrated per workspace and the percentage of them that has been migrated to UC. 

This dashboard will help central teams when doing UC migrations at large organizations, example below:

<img width="1197" alt="Capture d’écran 2024-08-13 à 09 45 41" src="https://github.com/user-attachments/assets/d9043dcf-9581-4754-aef8-7bd9eb278d4e">

### Proposed Solution

At the workspace local, we can leverage API calls to know this.
For cross workspaces tracking, we can leverage system tables.

**Comment by nfx** [comment]
to be handled by migration-progress dashboard
