### ISSUE TITLE
[BUG]: External location with S3A prefix create a conflict when attempting to create roles

### ISSUE THREAD

**Issue by FastLee** [databrickslabs/ucx#2413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If an external location with S3A bucket is discovered it is not matched properly for a role that is created in the create missing principals step.

### Steps To Reproduce

1. In sandbox create HMS tables with an S3A location reference.

### Cloud

AWS

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by nfx** [comment]
use `LocationTrie` and this potentially should provide a better foundation

**Comment by JCZuurmond** [comment]
I do not have access to the AWS sandbox
