### ISSUE TITLE
[BUG]: `MINUS` keyword is not recognized during `migrate-table` 

### ISSUE THREAD

**Issue by renardeinside** [databrickslabs/ucx#2451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

See the log:

```
9:59:09 DEBUG [databricks] {MainThread} Task crash details
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/sqlglot/parser.py", line 1466, in raise_error
    raise error
sqlglot.errors.ParseError: Expecting ). Line 29, Col: 5.
  field IN (1,2,3)
[4mMINUS [0m
SELECT
```

### Expected Behavior

Minus is supported

### Steps To Reproduce

Run the migrate-table task with a notebook with `MINUS` sql statement.

### Cloud

Azure

### Operating System

macOS

### Version

latest via Databricks CLI

### Relevant log output

```shell
See above
```

**Comment by ericvergnaud** [comment]
Issue reproduced lates sqlglot. Filed bug with them https://github.com/tobymao/sqlglot/issues/3970

**Comment by ericvergnaud** [comment]
Seems the issue is already fixed, pending release: https://github.com/tobymao/sqlglot/pull/3932
