### ISSUE TITLE
[BUG]: table migration job fails with DBUtilsCore.mounts() is not whitelisted

### ISSUE THREAD

**Issue by aowen5000** [databrickslabs/ucx#2498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- Table migration job running in DBR 15.4 and shared cluster fails with table migration job fails with DBUtilsCore.mounts() is not whitelisted error

- Table migration job running in DBR 15.4 and single user cluster fails with Table migration job running in DBR 15.4 and shared cluster fails with

- Table migration job running in DBR 14.3 and shared cluster fails with no error in log4j

### Expected Behavior

Job succeeds with no manual intervention

### Steps To Reproduce

Execute table migration with CLI
after job fails remove cluster policy and run with different cluster configs: 14.3 shared and 15.4 single user

### Cloud

AWS

### Operating System

macOS

### Version

latest via Databricks CLI

### Relevant log output

works on no-isolation clusters. table migration workflow should rely on `ucx.mounts` table and not make a call to `dbutils.fs.mounts()` from table migration cluster
<img width="1478" alt="image" src="https://github.com/user-attachments/assets/4b60f946-52c2-48b0-933d-47bb924d9e8b">

**Comment by JCZuurmond** [comment]
Moving sdk bug to here: https://github.com/databricks/databricks-sdk-py/issues/718

**Comment by JCZuurmond** [comment]
@aowen5000 : We to have a look at this issue. Did you run the assessment before running the migration? The `dbutils.fs.mount` is only used in one place, which should only be called during the assessment

**Comment by JCZuurmond** [comment]
@maruppel [reported](https://github.com/databricks/databricks-sdk-py/issues/718#issuecomment-2315811989) the issue occurred after running the assessment. This suggests that the `migrate-tables` workflow is not able to access the ucx inventory or that the mounts table in the inventory is empty. 

@maruppel: Could you verify that you can access the ucx inventory database? Could you also verify if the its `mounts` table contains any records? If not, should it be empty? If it does contains records, do you have an idea why the `table-migrate` workflow cannot reach the inventory database? For example, are you using an external hive metastore which requires a policy to access it?

**Comment by nfx** [comment]
works on no-isolation clusters. table migration workflow should rely on `ucx.mounts` table and not make a call to `dbutils.fs.mounts()` from table migration cluster
<img width="1478" alt="image" src="https://github.com/user-attachments/assets/4b60f946-52c2-48b0-933d-47bb924d9e8b">
