### ISSUE TITLE
[FEATURE]: Gracefully Handle Cascading View Dependencies

### ISSUE THREAD

**Issue by daveokeeffe-db** [databrickslabs/ucx#2518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

When using the migrate-table function, if an invalid table reference is encountered, the migrate-table function halts completely.

Some users have a long series of cascading views (views that depend on other views) and they can't easily untangle the dependencies apart. The migrate-table function should move forward and migrate everything it can, skipping the objects it can not.

Example error:
`ValueError: Invalid table references are preventing migration: {ViewToMigrate(src=Table(catalog='hive_metastore', database='cur_rom_operations', name='v_dim_tag', object_type='VIEW', table_format='UNKNOWN', location=None, view_text='SELECT \n  TAG_NAME_BK\n  , TAG_DESCRIPTION\n  ,\tTAG_UNITS\n  , TAG_FORMULA\n  ,\tTAG_SOURCE\n  ,\tTAG_TYPE\n  ,\tTAG_CLASS_NAME\n  ,\tTAG_ID_BK\n  ,\tASSET_HIERARCHY \n  ,\tASSET_DESCRIPTION\n  ,\tASSET_CONFIG_STRING\nFROM (\n  SELECT ROW_NUMBER() OVER (\n        PARTITION BY TAG_NAME_BK\n        ORDER BY TAG_NAME_BK\n     ) row_num,\n     *\n  FROM (\n    SELECT \n     pit.NAME\tAS\tTAG_NAME_BK\n    ,pit.DESCRIPTION\tAS\tTAG_DESCRIPTION\n    ,pit.ENGUNITS\tAS\tTAG_UNITS\n    ,pit.EXDESC\tAS\tTAG_FORMULA\n    ,pit.POINTSOURCE\tAS\tTAG_SOURCE\n    ,pit.POINTTYPE\tAS\tTAG_TYPE\n    ,pit.PTCLASSNAME\tAS\tTAG_CLASS_NAME\n    ,pit.POINTID\tAS\tTAG_ID_BK\n    ,paf.PARENT\tAS\tASSET_HIERARCHY \n    ,paf.DESCRIPTION\tAS\tASSET_DESCRIPTION\n    ,paf.ATTRIBUTECONFIGSTRING\tAS\tASSET_CONFIG_STRING\n    FROM raw_rom_pi.pitagmetadata pit\n      LEFT JOIN cur_rom_operations.V_PIAFMETADATA paf\n      ON pit.Name = paf.TAG_NAME \n  ) temp\n) final\nWHERE row_num = 1\nAND TAG_NAME_BK is not null', upgraded_to=None, storage_properties='[serialization.format=1]', is_partitioned=False), rule=Rule(workspace_name='workspace-6955339884354075', cata`

### Proposed Solution
The migrate-table function should catch the ValueError exception and move to the next object in the list if it can't be migrated. That way, all the first-level views get created, and the process can be repeated to get to the second-level views.

**Comment by JCZuurmond** [comment]
Resolved in #2499, please update ucx to resolve the issue
