### ISSUE TITLE
[BUG]: databricks labs install ucx a dependency error occurred

### ISSUE THREAD

**Issue by qimumu9406** [databrickslabs/ucx#2527]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I execute the command: databricks labs install ucx on my local mac, I get the following error：

`(base) qimumu@qimumudeMini ~ % databricks labs install ucx --debug     
12:06:28  INFO start pid=49933 version=0.227.0 args="databricks, labs, install, ucx, --debug"
12:06:28 DEBUG Latest ucx version is: v0.34.0 pid=49933
12:06:28 DEBUG Reading labs.yml@v0.34.0 from databrickslabs/ucx pid=49933
12:06:29 DEBUG Loading login configuration from: /Users/qimumu/.databricks/labs/ucx/config/login.json pid=49933
12:06:29 DEBUG Loading DEFAULT profile from /Users/qimumu/.databrickscfg pid=49933 sdk=true
12:06:29 DEBUG Login is configured via environment variables pid=49933
12:06:29 DEBUG Resolved login: Config: host=***, token=***, config_file=/Users/qimumu/.databrickscfg pid=49933 sdk=true
Using workspace profile: ***
12:07:43 DEBUG Writing auth configuration to: /Users/qimumu/.databricks/labs/ucx/config/login.json pid=49933
⣾ Cleaning up previous installation if necessary12:07:43 DEBUG Downloading zipball for v0.34.0 from databrickslabs/ucx pid=49933
⣷ Downloading and unpacking zipball for v0.34.012:08:05 DEBUG Unpacking zipball to: /Users/qimumu/.databricks/labs/ucx/lib pid=49933
⣾ Detecting all installed Python interpreters on the system12:08:05 DEBUG /opt/homebrew/bin is world-writeable (-rwxrwxrwx), skipping for security reasons pid=49933
12:08:05 DEBUG /opt/homebrew/sbin is world-writeable (-rwxrwxrwx), skipping for security reasons pid=49933
12:08:05 DEBUG cannot resolve symlink for /usr/local/bin/python:  pid=49933
12:08:05 DEBUG found 12 potential alternative Python versions in $PATH pid=49933
12:08:05 DEBUG running: /opt/anaconda3/bin/python3.12 --version pid=49933
12:08:05 DEBUG /opt/anaconda3/bin/python3.12 --version: Python 3.12.4 pid=49933
12:08:05 DEBUG running: /opt/anaconda3/bin/python.app --version pid=49933
⣽ Detecting all installed Python interpreters on the system12:08:06 DEBUG /opt/anaconda3/bin/python.app --version: Python 3.12.0 pid=49933
12:08:06 DEBUG running: /opt/anaconda3/bin/pythonw --version pid=49933
12:08:06 DEBUG /opt/anaconda3/bin/pythonw --version: Python 3.12.0 pid=49933
12:08:06 DEBUG running: /System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7 --version pid=49933
12:08:06 DEBUG /System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7 --version:  pid=49933
12:08:06 DEBUG /System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7 --version: stub from Windows Store pid=49933
12:08:06 DEBUG running: /usr/bin/python3 --version pid=49933
⣻ Detecting all installed Python interpreters on the system12:08:06 DEBUG /usr/bin/python3 --version: Python 3.8.2 pid=49933
12:08:06 DEBUG running: /System/Library/Frameworks/Python.framework/Versions/2.7/bin/pythonw2.7 --version pid=49933
12:08:06 DEBUG /System/Library/Frameworks/Python.framework/Versions/2.7/bin/pythonw2.7 --version:  pid=49933
12:08:06 DEBUG /System/Library/Frameworks/Python.framework/Versions/2.7/bin/pythonw2.7 --version: stub from Windows Store pid=49933
12:08:06 DEBUG Detected Python v3.12.0 at: /opt/anaconda3/bin/python.app pid=49933
12:08:06 DEBUG Creating Python Virtual Environment at: /Users/qimumu/.databricks/labs/ucx/state/venv pid=49933
12:08:06 DEBUG running: /opt/anaconda3/bin/python.app -m venv /Users/qimumu/.databricks/labs/ucx/state/venv pid=49933
⣷ Creating Virtual Environment with Python v3.12.012:08:08 DEBUG Installing Python dependencies for: /Users/qimumu/.databricks/labs/ucx/lib pid=49933
12:08:08 DEBUG running: /Users/qimumu/.databricks/labs/ucx/state/venv/bin/python3 -m pip install --upgrade --upgrade-strategy eager . pid=49933
/Users/qimumu/.databricks/labs/ucx/state/venv/bin/python3: No module named pip`

### Expected Behavior

Successfully executed databricks labs install ucx

### Steps To Reproduce

- databricks cli version：v0.227.0
- execute command：databricks labs install ucx

### Cloud

AWS

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by ericvergnaud** [comment]
This probably relates to a python installation issue. 
Can you try running `python3 -m pip` ? 
It should display something like:
```
someuser@somemachine ~ % python3 -m pip

Usage:   
  /usr/local/opt/python@3.12/bin/python3.12 -m pip <command> [options]

Commands:
  install                     Install packages.
  download                    Download packages.
```
If not, reinstall python and try again ?

**Comment by qimumu9406** [comment]
@ericvergnaud  Thanks for your reply.I'm able to run successfully: python3 -m pip,but don't run databricks labs install ucx.
<img width="1411" alt="image" src="https://github.com/user-attachments/assets/a0969d44-36fd-44a5-a7d6-3ba4d3e6fdb1">

**Comment by qimumu9406** [comment]
I have solved this problem, I think it is the local python environment version that causes.
