### ISSUE TITLE
[TECH DEBT]: Use type for lineage

### ISSUE THREAD

**Issue by ericvergnaud** [databrickslabs/ucx#2550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

Current implementation relies on str for lineage. We want something more structured.

### Proposed Solution

Use a dataclass such as 
```
@dataclass
class Link:
    object_type: str
    object_id: str
```

**Comment by nfx** [comment]
fixed in https://github.com/databrickslabs/ucx/commit/f8cdc22030750424fa0b0988eadb8d7d6d3370c7
