### ISSUE TITLE
[FEATURE] Create a `ucx` catalog via a cli-command

### ISSUE THREAD

**Issue by JCZuurmond** [databrickslabs/ucx#2571]
Add a cli command `create-ucx-catalog` to create a catalog called `ucx` that is available (for read and write) to **all** workspaces

**Comment by asnare** [comment]
This also needs to be part of the `assign-metastore` command. The idea is that we want this (and #2572) to happen as soon as possible once a metastore has been attached, and the `assign-metastore` command is the most convenient place to ensure that this happens.

Currently some customers will be (externally) assigning the metastore, so as part of this we will need to:

 - Update the `assign-metastore` command to ensure that it's a no-op if a metastore has already been assigned to the workspace (or all in the collection).
 - Update the documentation to mention that this is a mandatory step in the migration.

**Comment by asnare** [comment]
Another requirement, given the metastore can be shared across multiple workspaces is that the catalog may already exist: this is anticipated, and shouldn't be an error.
