### ISSUE TITLE
[BUG]: TASK "assess azure sp" fails with 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by danielm-db** [databrickslabs/ucx#2581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Assessment task "assess azure sp" fails with 'str' object has no attribute 'get' 

![image](https://github.com/user-attachments/assets/2aa3af27-423b-4b81-8eba-1469627fb015)

### Cloud

Azure

### Operating System

Windows

### Version

latest via Databricks CLI

**Comment by JCZuurmond** [comment]
@danielm-db : Thanks for opening. Would you be able to share the Spark configuration(s)? Maybe you have a hunch which one is causing the issue.
