### ISSUE TITLE
[TECH DEBT] `VerifyHasMetastore` attributes are not used

### ISSUE THREAD

**Issue by JCZuurmond** [databrickslabs/ucx#2593]
The following attributes are set in `verify_metastore` method, but never used: https://github.com/databrickslabs/ucx/blob/6a6f2f4dd2f3c37878dd3596a0ed202859afa650/src/databricks/labs/ucx/hive_metastore/verification.py#L11-L13. We can remove them (but maybe we won't).

**Comment by nfx** [comment]
won'tfix
