### ISSUE TITLE
[BUG]: View migration fails to resolve/include aliases in view create resulting in column does not exist

### ISSUE THREAD

**Issue by pritishpai** [databrickslabs/ucx#2661]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

Views should be migrated successfully

### Steps To Reproduce

Failed in the customer environment where the view depends on tables that are referred with alias in the the CREATE VIEW.

### Cloud

AWS

### Operating System

Windows

### Version

latest via Databricks CLI

**Comment by pritishpai** [comment]
sqlglot does not seem to be resolving aliases correctly

**Comment by JCZuurmond** [comment]
@pritishpai : Could you include a query for which this is failing?

**Comment by pritishpai** [comment]
I added a simple alias query and an integration test while I was debugging the issue.
https://github.com/databrickslabs/ucx/blob/fix/issue_2661/tests/integration/hive_metastore/test_migrate.py#L352
