### ISSUE TITLE
[BUG]: Nightly CI cannot create issues

### ISSUE THREAD

**Issue by JCZuurmond** [databrickslabs/ucx#2768]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Nightly CI cannot create issues due to issue contents being to big

### Expected Behavior

Nightly CI should create Github issues when integration tests fail

### Steps To Reproduce

See log output

### Cloud

Azure

### Operating System

Linux

### Version

latest via Databricks CLI

### Relevant log output

```shell
See [here](https://github.com/databrickslabs/ucx/actions/runs/11099739658/job/30834444906):


 Error: failed: create issue: new issue: Validation Failed. See https://docs.github.com/rest/issues/issues#create-an-issue
Error: $GITHUB_STEP_SUMMARY upload aborted, supports content up to a size of 1024k, got 7463k. For more information see: https://docs.github.com/actions/using-workflows/workflow-commands-for-github-actions#adding-a-markdown-summary
```
```

**Comment by nfx** [comment]
fixed in acceptance/v0.3.0
