### ISSUE TITLE
Test failure: `test_running_real_migration_progress_job`

### ISSUE THREAD

**Issue by JCZuurmond** [databrickslabs/ucx#2769]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Integration test failure

### Expected Behavior

Test should not fail

### Steps To Reproduce

See logs

### Cloud

Azure

### Operating System

macOS

### Version

latest via Databricks CLI

### Relevant log output

```shell
See [logs here](https://github.com/databrickslabs/ucx/actions/runs/11099739658/job/30834444906)
```

**Comment by JCZuurmond** [comment]
@asnare : This failed with a timeout. I am considering to introduce a test database plus table and run the assessment only for that database instead of all databases - which could be a lot

**Comment by JCZuurmond** [comment]
Failed again today

**Comment by nfx** [comment]
this test is too long (22m) and should not run assessment workflow

**Comment by JCZuurmond** [comment]
Ran for 11 minutes last night [✅ test_running_real_migration_progress_job (11m0.164s)](https://github.com/databrickslabs/ucx/actions/runs/11267778304/job/31333471539)

**Comment by JCZuurmond** [comment]
> ... not run assessment workflow

@asnare : Could you incorporate that in #2743? It becomes even more relevant when writing snapshots to the history log.
