### ISSUE TITLE
Encountering an error when running ./install.sh

### ISSUE THREAD

**Issue by sureshd-8451** [databrickslabs/ucx#281]
Encountered an error when running ./install.sh on windows machine.  Please helps us resolve the issue.  

s210302@CIN18796 MINGW64 /c/8451/Azure/ucx (main)
$ python --version
Python 3.11.5

s210302@CIN18796 MINGW64 /c/8451/Azure/ucx (main)
$ ./install.sh
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
[i] found Python  -> /c/Program Files/WindowsApps/Microsoft.DesktopAppInstaller_1.20.2201.0_x64__8wekyb3d8bbwe/AppInstallerPythonRedirector.exe
[i] latest python is /c/Program
./install.sh: line 49: /c/Program: No such file or directory
./install.sh: line 51: /tmp/tmp.gs9yGLM2pJ/bin/activate: No such file or directory
[+] making sure we have the latest pip version
./install.sh: line 61: /tmp/tmp.gs9yGLM2pJ/bin/python: No such file or directory
[+] installing dependencies within ephemeral Virtualenv: /tmp/tmp.gs9yGLM2pJ
./install.sh: line 65: /tmp/tmp.gs9yGLM2pJ/bin/python: No such file or directory
./install.sh: line 69: /tmp/tmp.gs9yGLM2pJ/bin/python: No such file or directory

**Comment by nfx** [comment]
We definitely do not test this on windows (yet). Could you file a PR with the fix?

The script actually looks for "python3", not the "python", which usually means outdated v2.7

You can debug the bash script by adding the "set -x" and rerunning it again 

----

@pietern this is why I was making that labs installer PR - to centralize Python discovery in CLI :)

**Comment by larsgeorge-db** [comment]
@sureshd-8451 could you try the linked PR?

**Comment by larsgeorge-db** [comment]
@nfx should we check for a minimal Python version?

**Comment by nfx** [comment]
We do, but I'm not sure how much fixes we should put into this script 😜

**Comment by nfx** [comment]
@sureshd-8451 how did you install the "python" binary? Is it coming by default like that in WSL?

**Comment by nfx** [comment]
@sureshd-8451 As a workaround, make sure that "python3" executable is available (or symlinked) to a $PATH

**Comment by sureshd-8451** [comment]
I am using python3.   It is in the path as you see below.  

$ python --version
Python 3.11.5
$ echo $PATH
/c/8451/Azure/Databricks/databricks-cli-uc/myenv/Scripts:/c/8451/Azure/Databricks/databricks-cli-uc/myenv/Scripts:/c/Users/s210302/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/s210302/bin:/c/Users/s210302/AppData/Local/Programs/Python/Python311:/c/Program Files/Eclipse Adoptium/jdk-11.0.16.101-hotspot/bin:/c/ProgramData/Anaconda3:/c/ProgramData/Anaconda3/Library/mingw-w64/bin:/c/ProgramData/Anaconda3/Library/usr/bin:/c/ProgramData/Anaconda3/Library/bin:/c/ProgramData/Anaconda3/Scripts:/c/Program Files (x86)/Microsoft SDKs/Azure/CLI2/wbin:/c/oracle/product/12.2.0/client_64bit:/c/oracle/product/12.2.0/client_64bit/bin:/c/Program Files (x86)/Sand:/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/WINDOWS/System32/OpenSSH:/c/Program Files (x86)/PuTTY:/c/Program Files (x86)/Microsoft SQL Server/150/DTS/Binn:/c/users/s210302/dsk_local/me_scripts:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/WINDOWS/System32/OpenSSH:/c/MongoDB/mongodb-shell-windows-x86_64-4.4.4/mongodb-win32-x86_64-windows-4.4.4/bin:/c/Program Files/Microsoft VS Code/bin:/c/Program Files/Terraform:/cmd:/c/Users/s210302/'OneDrive - 
8451'/DevarakondaPDrive/Documents/84.51/'Database Support'/Azure/Databricks/unravel:/c/Users/s210302/AppData/Local/Programs/Python/Python311/Scripts:/c/Users/s210302/AppData/Local/Programs/Python/Python311:/c/Users/s210302/AppData/Local/Microsoft/WindowsApps:/c/Program Files/JetBrains/PyCharm 2021.2.1/bin:/c/Users/s210302/AppData/Local/GitHubDesktop/bin:/usr/bin/vendor_perl:/usr/bin/core_perl:/c/Users/s210302/.local/bin:/c/Users/s210302/bin:/c/Users/s210302/.local/bin:/c/Users/s210302/bin

**Comment by nfx** [comment]
Yes, you are using Python 3.11.5, but the binary name is "python" and NOT "python3":

> $ python --version

Currently, the script only looks for "python3", not "python".

Does it come like that in the default Windows Subsystem for Linux installation?

**Comment by sureshd-8451** [comment]
I am not using WSL, but bash on VS code as you see in the attached image.   I have installed the python from "https://www.python.org/downloads/windows/"


<img width="1270" alt="vscode_bash" src="https://github.com/databrickslabs/ucx/assets/94718959/a7146669-fd9b-48c7-bd70-bdb933ecd1ba">

**Comment by sureshd-8451** [comment]
<img width="630" alt="image" src="https://github.com/databrickslabs/ucx/assets/94718959/6b472bdb-6f8b-41f2-958d-cf1d4efd2aad">

**Comment by larsgeorge-db** [comment]
The issue seems to be calling `realpath` and it returning something that does not work for us.

```
➜  ~ realpath $(which python3)
/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/bin/python3.11
➜  ~ which python3            
/opt/homebrew/bin/python3
```

We could just verify the return value of `realpath` still points to a `python` executable, or we could simply do the call to `--version` and if it fails, skip the binary.

This goes along with the other issue, where `--version` is not returning a two-part version string.

**Comment by larsgeorge-db** [comment]
This is caused seemingly by a Windows "feature" call Application Execution Aliases, see https://www.makeuseof.com/app-execution-aliases-guide/ for example. These are shell exe's that act as place holders to for example print a message asking you to install the tool you are trying to invoke.

I am going forward with the approach to skip all binaries that cannot return a proper version string.

**Comment by larsgeorge-db** [comment]
And for reference, you are using _Git Shell_ when using VSCode without a configured WSL and when not using Powershell. It appears as `bash` in the list of terminals and the prompt has `MINGW64` in it.

**Comment by nfx** [comment]
@larsgeorge-db make sure to comment your findings on https://github.com/databricks/cli/pull/805 to solve this problem in the mid-term

**Comment by larsgeorge-db** [comment]
![Pasted image 20230927113650](https://github.com/databrickslabs/ucx/assets/136075433/c3ff484d-97b9-4269-ae3f-f306e267ba00)

Got it to work in Windows, tested Mac, still works as well.

**Comment by larsgeorge-db** [comment]
Still need to handle the App Execution Alias situation.

**Comment by larsgeorge-db** [comment]
![Pasted image 20230927122513](https://github.com/databrickslabs/ucx/assets/136075433/8614e8c3-162f-4963-8df7-3d05dba18bb7)

![Pasted image 20230927122516](https://github.com/databrickslabs/ucx/assets/136075433/904774fc-e1b7-4211-8dad-62dcebf6057c)
