### ISSUE TITLE
[BUG]: False Warning when using UC /Volumes

### ISSUE THREAD

**Issue by bicaluv** [databrickslabs/ucx#2850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I get the following **false warning** for UC Volumes based path to files which makes the cell unreadable.   

> The use of default dbfs: references is deprecated.  

See picture:  
<img width="711" alt="image" src="https://github.com/user-attachments/assets/c1014baa-2a59-4842-abf1-386e75fbdaa0">  

The given path notation is correct, according to the Databricks documentation.

### Expected Behavior

Not getting warnings for correct path usage.

### Steps To Reproduce

Using the following python code with serverless env:  
```
df = (
   spark.readStream.format('cloudFiles')
   .option('cloudFiles.format', 'csv')
   .option('cloudFiles.schemaLocation', '/Volumes/playground/test/schemas/')
   .option('header', 'true')
   .option('compression', 'gzip')
   .load('/Volumes/playground/test/demo_data/')
)
```

### Cloud

Azure

### Operating System

Windows

### Version

latest via Databricks CLI

**Comment by ericvergnaud** [comment]
@bicaluv may I ask which exact version of `ucx` you are using ? I'm not able to reproduce the issue with the `latest` version

**Comment by bicaluv** [comment]
Not sure. How can one check?

**Comment by ericvergnaud** [comment]
run `databricks labs installed`
