### ISSUE TITLE
[BUG]: UCX Assessment contains issues / warnings related to UCX

### ISSUE THREAD

**Issue by gchandra10** [databrickslabs/ucx#2870]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

UCX assessment report contains warnings & issues related to UCX jobs and clusters.

Example: 
Cluster type not supported : LEGACY_TABLE_ACL” for 3 resources.  
Upon digging further, it's reported by the TACL job cluster. 

Example 2:
UCX  tables showing up in Table inventory.

### Expected Behavior

Assessment not to report on UCX related issues.

### Cloud

Azure

### Operating System

Windows

### Version

latest via Databricks CLI

**Comment by nfx** [comment]
@gchandra10 how `Cluster type not supported : LEGACY_TABLE_ACL` did appear? we're ignoring job clusters and in the production deployment we rely only on job clusters. https://github.com/databrickslabs/ucx/blob/main/src/databricks/labs/ucx/assessment/clusters.py#L156-L158
