### ISSUE TITLE
[BUG]: assess_workflow failing with "Parsing Python code failed"

### ISSUE THREAD

**Issue by antoniopinheirofilho** [databrickslabs/ucx#2882]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

assess_workflow fails with several "Parsing Python code failed" errors

### Expected Behavior

assess_workflow should not fail. Instead, it should flag the code/files that it can't parse

i think we need to pass absolute paths to API: `/Repos/NBA_PROD/nba-data-load-scripts/real-time/../../nba-common-scripts/nba_common_functions` -> `/Repos/NBA_PROD/nba-common-scripts/nba_common_functions`

### Cloud

Azure

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by ericvergnaud** [comment]
@antoniopinheirofilho would you be able to share the failing notebook ? (presumably `/Repos/NBA_PREPROD/nba-data-load-scripts/i360-table-refresh-monitoring/../../nba-common-scripts/nba_common_functions`)

**Comment by nfx** [comment]
@ericvergnaud i think we need to pass absolute paths to API: `/Repos/NBA_PROD/nba-data-load-scripts/real-time/../../nba-common-scripts/nba_common_functions` -> `/Repos/NBA_PROD/nba-common-scripts/nba_common_functions`

**Comment by antoniopinheirofilho** [comment]
@ericvergnaud it appears that the path you mentioned doesn't exist.

@nfx here is the content of the "assess_workflow.log" file:

18:45:42 DEBUG [databricks.labs.ucx.framework.crawlers] {MainThread} [hive_metastore.ucx.directfs_in_paths] found 55 new records for directfs_in_paths
18:45:46 DEBUG [databricks.labs.ucx.framework.crawlers] {MainThread} [hive_metastore.ucx.used_tables_in_paths] found 1755 new records for used_tables_in_paths
18:45:50 ERROR [databricks.labs.ucx] {MainThread} Execute `databricks workspace export //Applications/ucx/logs/assessment/run-854607653748637-0/assess_workflows.log` locally to troubleshoot with more details. Detected 478 failures: AstroidSyntaxError: Parsing Python code failed:
cannot use starred expression here (<unknown>, line 76), AstroidSyntaxError: Parsing Python code failed:
invalid syntax (<unknown>, line 1), AstroidSyntaxError: Parsing Python code failed:
unexpected indent (<unknown>, line 5), AstroidSyntaxError: Parsing Python code failed:
unterminated string literal (detected at line 17) (<unknown>, line 17), AttributeError: 'UsedTable' object has no attribute 'table', BadRequest: unable to parse response. This is likely a bug in the Databricks SDK for Python or the underlying API. Please report this issue with the following debugging information to the SDK issue tracker at https://github.com/databricks/databricks-sdk-go/issues. Request log:```GET /api/2.0/workspace/get-status?path=/Repos/NBA_PREPROD/nba-data-load-scripts/i360-table-refresh-monitoring/../../nba-common-scripts/nba_common_functions
> * User-Agent: ucx/0.39.0 databricks-sdk-py/0.34.0 python/3.11.0rc1 os/linux auth/runtime blueprint/0.9.0 ucx/0.39.0 lsql/0.12.1 cmd/assessment runtime/15.4
> * Accept-Encoding: gzip, deflate
> * Accept: application/json
> * Connection: keep-alive
> * Authorization: Bearer dkea05613f1ce7a6fda969d8b727430a509f
< 400 Bad Request
< 400 Bad Request
< Invalid request path```, BadRequest: unable to parse response. This is likely a bug in the Databricks SDK for Python or the underlying API. Please report this issue with the following debugging information to the SDK issue tracker at https://github.com/databricks/databricks-sdk-go/issues. Request log:```GET /api/2.0/workspace/get-status?path=/Repos/NBA_PROD/nba-data-load-scripts/real-time/../../nba-common-scripts/nba_common_functions
> * User-Agent: ucx/0.39.0 databricks-sdk-py/0.34.0 python/3.11.0rc1 os/linux auth/runtime blueprint/0.9.0 ucx/0.39.0 lsql/0.12.1 cmd/assessment runtime/15.4
> * Accept-Encoding: gzip, deflate
> * Accept: application/json
> * Connection: keep-alive
> * Authorization: Bearer dkea05613f1ce7a6fda969d8b727430a509f
< 400 Bad Request
< 400 Bad Request
< Invalid request path```, BadRequest: unable to parse response. This is likely a bug in the Databricks SDK for Python or the underlying API. Please report this issue with the following debugging information to the SDK issue tracker at https://github.com/databricks/databricks-sdk-go/issues. Request log:```GET /api/2.0/workspace/get-status?path=/Repos/NBA_PROD/nba-data-load-scripts/real-time/../../nba-common-scripts/nba_common_variables+$v_nba_i360_env_name=$v_nba_i360_env_name
> * User-Agent: ucx/0.39.0 databricks-sdk-py/0.34.0 python/3.11.0rc1 os/linux auth/runtime blueprint/0.9.0 ucx/0.39.0 lsql/0.12.1 cmd/assessment runtime/15.4
> * Accept-Encoding: gzip, deflate
> * Accept: application/json
> * Connection: keep-alive
> * Authorization: Bearer dkea05613f1ce7a6fda969d8b727430a509f
< 400 Bad Request
< 400 Bad Request
< Invalid request path```, BadRequest: unable to parse response. This is likely a bug in the Databricks SDK for Python or the underlying API. Please report this issue with the following debugging information to the SDK issue tracker at https://github.com/databricks/databricks-sdk-go/issues. Request log:```GET /api/2.0/workspace/get-status?path=/Repos/[mohan.taneja4@t-mobile.com/DSH_SoftwareCareCalls/Notebooks/../common/reusable.py](http://mohan.taneja4@t-mobile.com/DSH_SoftwareCareCalls/common/reusable.py)
> * User-Agent: ucx/0.39.0 databricks-sdk-py/0.34.0 python/3.11.0rc1 os/linux auth/runtime blueprint/0.9.0 ucx/0.39.0 lsql/0.12.1 cmd/assessment runtime/15.4
> * Accept-Encoding: gzip, deflate
> * Accept: application/json
> * Connection: keep-alive
> * Authorization: Bearer dkea05613f1ce7a6fda969d8b727430a509f
< 400 Bad Request
< 400 Bad Request
< Invalid request path```, BadRequest: unable to parse response. This is likely a bug in the Databricks SDK for Python or the underlying API. Please report this issue with the following debugging information to the SDK issue tracker at https://github.com/databricks/databricks-sdk-go/issues. Request log:```GET /api/2.0/workspace/get-status?path=/Repos/[roli.bhargava2@t-mobile.com/nba-data-load-scripts/real-time/../../nba-common-scripts/nba_common_functions](http://roli.bhargava2@t-mobile.com/nba-common-scripts/nba_common_functions)
> * User-Agent: ucx/0.39.0 databricks-sdk-py/0.34.0 python/3.11.0rc1 os/linux auth/runtime blueprint/0.9.0 ucx/0.39.0 lsql/0.12.1 cmd/assessment runtime/15.4
> * Accept-Encoding: gzip, deflate
> * Accept: application/json
> * Connection: keep-alive
> * Authorization: Bearer dkea05613f1ce7a6fda969d8b727430a509f
< 400 Bad Request
< 400 Bad Request
< Invalid request path```, BadRequest: unable to parse response. This is likely a bug in the Databricks SDK for Python or the underlying API. Please report this issue with the following debugging information to the SDK issue tracker at https://github.com/databricks/databricks-sdk-go/issues. Request log:```GET /api/2.0/workspace/get-status?path=/Users/[ramanjaneyareddy.thirupathi1@t-mobile.com/AMP_DECOMM/code/main/Raman_ML_model_deploy/../z_config_info](http://ramanjaneyareddy.thirupathi1@t-mobile.com/AMP_DECOMM/code/main/z_config_info)
> * User-Agent: ucx/0.39.0 databricks-sdk-py/0.34.0 python/3.11.0rc1 os/linux auth/runtime blueprint/0.9.0 ucx/0.39.0 lsql/0.12.1 cmd/assessment runtime/15.4
> * Accept-Encoding: gzip, deflate
> * Accept: application/json
> * Connection: keep-alive
> * Authorization: Bearer dkea05613f1ce7a6fda969d8b727430a509f
< 400 Bad Request
< 400 Bad Request
< Invalid request path```, BadRequest: unable to parse response. This is likely a bug in the Databricks SDK for Python or the underlying API. Please report this issue with the following debugging information to the SDK issue tracker at https://github.com/databricks/databricks-sdk-go/issues. Request log:```GET /api/2.0/workspace/get-status?path=/Workspace/customer_intent_dev/int_roaming_pending_suspension/../utilities/generic_functions
> * User-Agent: ucx/0.39.0 databricks-sdk-py/0.34.0 python/3.11.0rc1 os/linux auth/runtime blueprint/0.9.0 ucx/0.39.0 lsql/0.12.1 cmd/assessment runtime/15.4
> * Accept-Encoding: gzip, deflate
> * Accept: application/json
> * Connection: keep-alive
> * Authorization: Bearer dkea05613f1ce7a6fda969d8b727430a509f
< 400 Bad Request
< 400 Bad Request
< Invalid request path```, BadRequest: unable to parse response. This is likely a bug in the Databricks SDK for Python or the underlying API. Please report this issue with the following debugging information to the SDK issue tracker at https://github.com/databricks/databricks-sdk-go/issues. Request log:```GET /api/2.0/workspace/get-status?path=/Workspace/customer_intent_dev/pymt_arrngmt/../utilities/generic_functions
> * User-Agent: ucx/0.39.0 databricks-sdk-py/0.34.0 python/3.11.0rc1 os/linux auth/runtime blueprint/0.9.0 ucx/0.39.0 lsql/0.12.1 cmd/assessment runtime/15.4
> * Accept-Encoding: gzip, deflate
> * Accept: application/json
> * Connection: keep-alive
> * Authorization: Bearer dkea05613f1ce7a6fda969d8b727430a509f
< 400 Bad Request
< 400 Bad Request
< Invalid request path```, BadRequest: unable to parse response. This is likely a bug in the Databricks SDK for Python or the underlying API. Please report this issue with the following debugging information to the SDK issue tracker at https://github.com/databricks/databricks-sdk-go/issues. Request log:```GET /api/2.0/workspace/get-status?path=/Workspace/customer_intent_ppd/int_roaming/../utilities/generic_functions
> * User-Agent: ucx/0.39.0 databricks-sdk-py/0.34.0 python/3.11.0rc1 os/linux auth/runtime blueprint/0.9.0 ucx/0.39.0 lsql/0.12.1 cmd/assessment runtime/15.4
> * Accept-Encoding: gzip, deflate
> * Accept: application/json
> * Connection: keep-alive
> * Authorization: Bearer dkea05613f1ce7a6fda969d8b727430a509f
< 400 Bad Request
< 400 Bad Request
< Invalid request path```, BadRequest: unable to parse response. This is likely a bug in the Databricks SDK for Python or the underlying API. Please report this issue with the following debugging information to the SDK issue tracker at https://github.com/databricks/databricks-sdk-go/issues. Request log:```GET /api/2.0/workspace/get-status?path=/Workspace/customer_intent_ppd/pymt_arrngmt_open/../utilities/generic_functions
> * User-Agent: ucx/0.39.0 databricks-sdk-py/0.34.0 python/3.11.0rc1 os/linux auth/runtime blueprint/0.9.0 ucx/0.39.0 lsql/0.12.1 cmd/assessment runtime/15.4
> * Accept-Encoding: gzip, deflate
> * Accept: application/json
> * Connection: keep-alive
> * Authorization: Bearer dkea05613f1ce7a6fda969d8b727430a509f
< 400 Bad Request
< 400 Bad Request
< Invalid request path```, BadRequest: unable to parse response. This is likely a bug in the Databricks SDK for Python or the underlying API. Please report this issue with the following debugging information to the SDK issue tracker at https://github.com/databricks/databricks-sdk-go/issues. Request log:```GET /api/2.0/workspace/get-status?path=/Workspace/i360_customer_graph/identity_resolution/customer_graph/../utilities/z_config_info
> * User-Agent: ucx/0.39.0 databricks-sdk-py/0.34.0 python/3.11.0rc1 os/linux auth/runtime blueprint/0.9.0 ucx/0.39.0 lsql/0.12.1 cmd/assessment runtime/15.4
> * Accept-Encoding: gzip, deflate
> * Accept: application/json
> * Connection: keep-alive
> * Authorization: Bearer dkea05613f1ce7a6fda969d8b727430a509f
< 400 Bad Request
< 400 Bad Request
< Invalid request path```, BadRequest: unable to parse response. This is likely a bug in the Databricks SDK for Python or the underlying API. Please report this issue with the following debugging information to the SDK issue tracker at https://github.com/databricks/databricks-sdk-go/issues. Request log:```GET /api/2.0/workspace/get-status?path=/customer_intent_ppd/int_roaming/../utilities/generic_functions
> * User-Agent: ucx/0.39.0 databricks-sdk-py/0.34.0 python/3.11.0rc1 os/linux auth/runtime blueprint/0.9.0 ucx/0.39.0 lsql/0.12.1 cmd/assessment runtime/15.4
> * Accept-Encoding: gzip, deflate
> * Accept: application/json
> * Connection: keep-alive
> * Authorization: Bearer dkea05613f1ce7a6fda969d8b727430a509f
< 400 Bad Request
< 400 Bad Request
< Invalid request path```, KeyError: (<AssignName.Enum l.21 at 0x7f38c0209790>, None, None, None), KeyError: (<AssignName.self l.1465 at 0x7f376d331810>, None, None, None), KeyError: (<ClassDef.property l.0 at 0x7f38ccf0c490>, None, None, None), KeyError: (<ImportFrom l.55 at 0x7f3871989f90>, 'fspath', <astroid.context.CallContext object at 0x7f37d75a2b80>, <Module.os l.0 at 0x7f38719fbe50>), KeyError: (<Name.object l.69 at 0x7f3739460f90>, None, None, None), OSError: [Errno 95] Operation not supported: '/Workspace/i360/deepio/src_dnd_deepio_lag_check.py', OSError: [Errno 95] Operation not supported: '/Workspace/i360_ris/Job_Monitor/csm_transaction_lag_check.py', ParseError: Invalid expression / Unexpected token. Line 1954, Col: 5.
  XID_OTHERS
from
    bdm_fincrsk_prd_db.fin_crsk_ws_t_sch.astha_tfb_base
WHERE
    TEST_BAN = 0;
    [4mjoin[0m (
        select
            ban_encr,
            product_type prodtype,
            expiration_da, ParseError: Invalid expression / Unexpected token. Line 2, Col: 9.
  landing : dbfs:/mnt/landing/iam/data/iam_profile_data/iam_profile_data_20240710020756.txt
archive [4m:[0m dbfs:/mnt/landing/iam/archive/iam_profile_data/last/iam_profile_data_20240710121523.txt, ParseError: Required keyword: 'this' missing for <class 'sqlglot.expressions.Where'>. Line 21, Col: 2.
     metro.subscriber
          where
            -- LOAD_DTTM > '1900-01-01 00:00:00.000000'
        [4m)[0m x
      where
        rn = 1
        and SUB_STATUS <> 'R'
), ResourceDoesNotExist: Cluster 0109-072453-their634 does not exist, ResourceDoesNotExist: Cluster 0109-074149-email202 does not exist, ResourceDoesNotExist: Cluster 0122-014208-twins822 does not exist, ResourceDoesNotExist: Cluster 0128-181015-unsay450 does not exist, ResourceDoesNotExist: Cluster 0214-045319-81ry8daa does not exist, ResourceDoesNotExist: Cluster 0315-055302-ninth119 does not exist, ResourceDoesNotExist: Cluster 0510-061744-tiger938 does not exist, ResourceDoesNotExist: Cluster 0510-062851-steam954 does not exist, ResourceDoesNotExist: Cluster 0510-063148-mails984 does not exist, ResourceDoesNotExist: Cluster 0808-223424-ante238 does not exist, ResourceDoesNotExist: Cluster 0813-003832-take426 does not exist, ResourceDoesNotExist: Cluster 0924-235835-cons887 does not exist, ResourceDoesNotExist: Cluster 0930-174142-hood950 does not exist, ResourceDoesNotExist: Cluster 1021-010705-qq51xgx3 does not exist, ResourceDoesNotExist: Cluster 1104-164710-rifle803 does not exist, ResourceDoesNotExist: Cluster 1109-182315-xfqh7kym does not exist, ResourceDoesNotExist: Cluster 1118-225929-owbsmhnd does not exist, SystemError: AST constructor recursion depth mismatch (before=93, after=79)
18:45:50 DEBUG [databricks] {MainThread} Task crash details
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/databricks/labs/ucx/runtime.py", line 102, in trigger
    current_task(ctx)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/databricks/labs/ucx/assessment/workflows.py", line 196, in assess_workflows
    ctx.workflow_linter.refresh_report(ctx.sql_backend, ctx.inventory_database)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/databricks/labs/ucx/source_code/jobs.py", line 390, in refresh_report
    raise ManyError(errors)
databricks.labs.blueprint.parallel.ManyError: Detected 478 failures: AstroidSyntaxError: Parsing Python code failed:
cannot use starred expression here (<unknown>, line 76), AstroidSyntaxError: Parsing Python code failed:
invalid syntax (<unknown>, line 1), AstroidSyntaxError: Parsing Python code failed:
unexpected indent (<unknown>, line 5), AstroidSyntaxError: Parsing Python code failed:
unterminated string literal (detected at line 17) (<unknown>, line 17), AttributeError: 'UsedTable' object has no attribute 'table', BadRequest: unable to parse response. This is likely a bug in the Databricks SDK for Python or the underlying API. Please report this issue with the following debugging information to the SDK issue tracker at https://github.com/databricks/databricks-sdk-go/issues. Request log:```GET /api/2.0/workspace/get-status?path=/Repos/NBA_PREPROD/nba-data-load-scripts/i360-table-refresh-monitoring/../../nba-common-scripts/nba_common_functions
> * User-Agent: ucx/0.39.0 databricks-sdk-py/0.34.0 python/3.11.0rc1 os/linux auth/runtime blueprint/0.9.0 ucx/0.39.0 lsql/0.12.1 cmd/assessment runtime/15.4
> * Accept-Encoding: gzip, deflate
> * Accept: application/json
> * Connection: keep-alive
> * Authorization: Bearer dkea05613f1ce7a6fda969d8b727430a509f
< 400 Bad Request
< 400 Bad Request
< Invalid request path```, BadRequest: unable to parse response. This is likely a bug in the Databricks SDK for Python or the underlying API. Please report this issue with the following debugging information to the SDK issue tracker at https://github.com/databricks/databricks-sdk-go/issues. Request log:```GET /api/2.0/workspace/get-status?path=/Repos/NBA_PROD/nba-data-load-scripts/real-time/../../nba-common-scripts/nba_common_functions
> * User-Agent: ucx/0.39.0 databricks-sdk-py/0.34.0 python/3.11.0rc1 os/linux auth/runtime blueprint/0.9.0 ucx/0.39.0 lsql/0.12.1 cmd/assessment runtime/15.4
> * Accept-Encoding: gzip, deflate
> * Accept: application/json
> * Connection: keep-alive
> * Authorization: Bearer dkea05613f1ce7a6fda969d8b727430a509f
< 400 Bad Request
< 400 Bad Request
< Invalid request path```, BadRequest: unable to parse response. This is likely a bug in the Databricks SDK for Python or the underlying API. Please report this issue with the following debugging information to the SDK issue tracker at https://github.com/databricks/databricks-sdk-go/issues. Request log:```GET /api/2.0/workspace/get-status?path=/Repos/NBA_PROD/nba-data-load-scripts/real-time/../../nba-common-scripts/nba_common_variables+$v_nba_i360_env_name=$v_nba_i360_env_name
> * User-Agent: ucx/0.39.0 databricks-sdk-py/0.34.0 python/3.11.0rc1 os/linux auth/runtime blueprint/0.9.0 ucx/0.39.0 lsql/0.12.1 cmd/assessment runtime/15.4
> * Accept-Encoding: gzip, deflate
> * Accept: application/json
> * Connection: keep-alive
> * Authorization: Bearer dkea05613f1ce7a6fda969d8b727430a509f
< 400 Bad Request
< 400 Bad Request
< Invalid request path```, BadRequest: unable to parse response. This is likely a bug in the Databricks SDK for Python or the underlying API. Please report this issue with the following debugging information to the SDK issue tracker at https://github.com/databricks/databricks-sdk-go/issues. Request log:```GET /api/2.0/workspace/get-status?path=/Repos/[mohan.taneja4@t-mobile.com/DSH_SoftwareCareCalls/Notebooks/../common/reusable.py](http://mohan.taneja4@t-mobile.com/DSH_SoftwareCareCalls/common/reusable.py)
> * User-Agent: ucx/0.39.0 databricks-sdk-py/0.34.0 python/3.11.0rc1 os/linux auth/runtime blueprint/0.9.0 ucx/0.39.0 lsql/0.12.1 cmd/assessment runtime/15.4
> * Accept-Encoding: gzip, deflate
> * Accept: application/json
> * Connection: keep-alive
> * Authorization: Bearer dkea05613f1ce7a6fda969d8b727430a509f
< 400 Bad Request
< 400 Bad Request
< Invalid request path```, BadRequest: unable to parse response. This is likely a bug in the Databricks SDK for Python or the underlying API. Please report this issue with the following debugging information to the SDK issue tracker at https://github.com/databricks/databricks-sdk-go/issues. Request log:```GET /api/2.0/workspace/get-status?path=/Repos/[roli.bhargava2@t-mobile.com/nba-data-load-scripts/real-time/../../nba-common-scripts/nba_common_functions](http://roli.bhargava2@t-mobile.com/nba-common-scripts/nba_common_functions)
> * User-Agent: ucx/0.39.0 databricks-sdk-py/0.34.0 python/3.11.0rc1 os/linux auth/runtime blueprint/0.9.0 ucx/0.39.0 lsql/0.12.1 cmd/assessment runtime/15.4
> * Accept-Encoding: gzip, deflate
> * Accept: application/json
> * Connection: keep-alive
> * Authorization: Bearer dkea05613f1ce7a6fda969d8b727430a509f
< 400 Bad Request
< 400 Bad Request
< Invalid request path```, BadRequest: unable to parse response. This is likely a bug in the Databricks SDK for Python or the underlying API. Please report this issue with the following debugging information to the SDK issue tracker at https://github.com/databricks/databricks-sdk-go/issues. Request log:```GET /api/2.0/workspace/get-status?path=/Users/[ramanjaneyareddy.thirupathi1@t-mobile.com/AMP_DECOMM/code/main/Raman_ML_model_deploy/../z_config_info](http://ramanjaneyareddy.thirupathi1@t-mobile.com/AMP_DECOMM/code/main/z_config_info)
> * User-Agent: ucx/0.39.0 databricks-sdk-py/0.34.0 python/3.11.0rc1 os/linux auth/runtime blueprint/0.9.0 ucx/0.39.0 lsql/0.12.1 cmd/assessment runtime/15.4
> * Accept-Encoding: gzip, deflate
> * Accept: application/json
> * Connection: keep-alive
> * Authorization: Bearer dkea05613f1ce7a6fda969d8b727430a509f
< 400 Bad Request
< 400 Bad Request
< Invalid request path```, BadRequest: unable to parse response. This is likely a bug in the Databricks SDK for Python or the underlying API. Please report this issue with the following debugging information to the SDK issue tracker at https://github.com/databricks/databricks-sdk-go/issues. Request log:```GET /api/2.0/workspace/get-status?path=/Workspace/customer_intent_dev/int_roaming_pending_suspension/../utilities/generic_functions
> * User-Agent: ucx/0.39.0 databricks-sdk-py/0.34.0 python/3.11.0rc1 os/linux auth/runtime blueprint/0.9.0 ucx/0.39.0 lsql/0.12.1 cmd/assessment runtime/15.4
> * Accept-Encoding: gzip, deflate
> * Accept: application/json
> * Connection: keep-alive
> * Authorization: Bearer dkea05613f1ce7a6fda969d8b727430a509f
< 400 Bad Request
< 400 Bad Request
< Invalid request path```, BadRequest: unable to parse response. This is likely a bug in the Databricks SDK for Python or the underlying API. Please report this issue with the following debugging information to the SDK issue tracker at https://github.com/databricks/databricks-sdk-go/issues. Request log:```GET /api/2.0/workspace/get-status?path=/Workspace/customer_intent_dev/pymt_arrngmt/../utilities/generic_functions
> * User-Agent: ucx/0.39.0 databricks-sdk-py/0.34.0 python/3.11.0rc1 os/linux auth/runtime blueprint/0.9.0 ucx/0.39.0 lsql/0.12.1 cmd/assessment runtime/15.4
> * Accept-Encoding: gzip, deflate
> * Accept: application/json
> * Connection: keep-alive
> * Authorization: Bearer dkea05613f1ce7a6fda969d8b727430a509f
< 400 Bad Request
< 400 Bad Request
< Invalid request path```, BadRequest: unable to parse response. This is likely a bug in the Databricks SDK for Python or the underlying API. Please report this issue with the following debugging information to the SDK issue tracker at https://github.com/databricks/databricks-sdk-go/issues. Request log:```GET /api/2.0/workspace/get-status?path=/Workspace/customer_intent_ppd/int_roaming/../utilities/generic_functions
> * User-Agent: ucx/0.39.0 databricks-sdk-py/0.34.0 python/3.11.0rc1 os/linux auth/runtime blueprint/0.9.0 ucx/0.39.0 lsql/0.12.1 cmd/assessment runtime/15.4
> * Accept-Encoding: gzip, deflate
> * Accept: application/json
> * Connection: keep-alive
> * Authorization: Bearer dkea05613f1ce7a6fda969d8b727430a509f
< 400 Bad Request
< 400 Bad Request
< Invalid request path```, BadRequest: unable to parse response. This is likely a bug in the Databricks SDK for Python or the underlying API. Please report this issue with the following debugging information to the SDK issue tracker at https://github.com/databricks/databricks-sdk-go/issues. Request log:```GET /api/2.0/workspace/get-status?path=/Workspace/customer_intent_ppd/pymt_arrngmt_open/../utilities/generic_functions
> * User-Agent: ucx/0.39.0 databricks-sdk-py/0.34.0 python/3.11.0rc1 os/linux auth/runtime blueprint/0.9.0 ucx/0.39.0 lsql/0.12.1 cmd/assessment runtime/15.4
> * Accept-Encoding: gzip, deflate
> * Accept: application/json
> * Connection: keep-alive
> * Authorization: Bearer dkea05613f1ce7a6fda969d8b727430a509f
< 400 Bad Request
< 400 Bad Request
< Invalid request path```, BadRequest: unable to parse response. This is likely a bug in the Databricks SDK for Python or the underlying API. Please report this issue with the following debugging information to the SDK issue tracker at https://github.com/databricks/databricks-sdk-go/issues. Request log:```GET /api/2.0/workspace/get-status?path=/Workspace/i360_customer_graph/identity_resolution/customer_graph/../utilities/z_config_info
> * User-Agent: ucx/0.39.0 databricks-sdk-py/0.34.0 python/3.11.0rc1 os/linux auth/runtime blueprint/0.9.0 ucx/0.39.0 lsql/0.12.1 cmd/assessment runtime/15.4
> * Accept-Encoding: gzip, deflate
> * Accept: application/json
> * Connection: keep-alive
> * Authorization: Bearer dkea05613f1ce7a6fda969d8b727430a509f
< 400 Bad Request
< 400 Bad Request
< Invalid request path```, BadRequest: unable to parse response. This is likely a bug in the Databricks SDK for Python or the underlying API. Please report this issue with the following debugging information to the SDK issue tracker at https://github.com/databricks/databricks-sdk-go/issues. Request log:```GET /api/2.0/workspace/get-status?path=/customer_intent_ppd/int_roaming/../utilities/generic_functions
> * User-Agent: ucx/0.39.0 databricks-sdk-py/0.34.0 python/3.11.0rc1 os/linux auth/runtime blueprint/0.9.0 ucx/0.39.0 lsql/0.12.1 cmd/assessment runtime/15.4
> * Accept-Encoding: gzip, deflate
> * Accept: application/json
> * Connection: keep-alive
> * Authorization: Bearer dkea05613f1ce7a6fda969d8b727430a509f
< 400 Bad Request
< 400 Bad Request
< Invalid request path```, KeyError: (<AssignName.Enum l.21 at 0x7f38c0209790>, None, None, None), KeyError: (<AssignName.self l.1465 at 0x7f376d331810>, None, None, None), KeyError: (<ClassDef.property l.0 at 0x7f38ccf0c490>, None, None, None), KeyError: (<ImportFrom l.55 at 0x7f3871989f90>, 'fspath', <astroid.context.CallContext object at 0x7f37d75a2b80>, <Module.os l.0 at 0x7f38719fbe50>), KeyError: (<Name.object l.69 at 0x7f3739460f90>, None, None, None), OSError: [Errno 95] Operation not supported: '/Workspace/i360/deepio/src_dnd_deepio_lag_check.py', OSError: [Errno 95] Operation not supported: '/Workspace/i360_ris/Job_Monitor/csm_transaction_lag_check.py', ParseError: Invalid expression / Unexpected token. Line 1954, Col: 5.
  XID_OTHERS
from
    bdm_fincrsk_prd_db.fin_crsk_ws_t_sch.astha_tfb_base
WHERE
    TEST_BAN = 0;
    [4mjoin[0m (
        select
            ban_encr,
            product_type prodtype,
            expiration_da, ParseError: Invalid expression / Unexpected token. Line 2, Col: 9.
  landing : dbfs:/mnt/landing/iam/data/iam_profile_data/iam_profile_data_20240710020756.txt
archive [4m:[0m dbfs:/mnt/landing/iam/archive/iam_profile_data/last/iam_profile_data_20240710121523.txt, ParseError: Required keyword: 'this' missing for <class 'sqlglot.expressions.Where'>. Line 21, Col: 2.
     metro.subscriber
          where
            -- LOAD_DTTM > '1900-01-01 00:00:00.000000'
        [4m)[0m x
      where
        rn = 1
        and SUB_STATUS <> 'R'
), ResourceDoesNotExist: Cluster 0109-072453-their634 does not exist, ResourceDoesNotExist: Cluster 0109-074149-email202 does not exist, ResourceDoesNotExist: Cluster 0122-014208-twins822 does not exist, ResourceDoesNotExist: Cluster 0128-181015-unsay450 does not exist, ResourceDoesNotExist: Cluster 0214-045319-81ry8daa does not exist, ResourceDoesNotExist: Cluster 0315-055302-ninth119 does not exist, ResourceDoesNotExist: Cluster 0510-061744-tiger938 does not exist, ResourceDoesNotExist: Cluster 0510-062851-steam954 does not exist, ResourceDoesNotExist: Cluster 0510-063148-mails984 does not exist, ResourceDoesNotExist: Cluster 0808-223424-ante238 does not exist, ResourceDoesNotExist: Cluster 0813-003832-take426 does not exist, ResourceDoesNotExist: Cluster 0924-235835-cons887 does not exist, ResourceDoesNotExist: Cluster 0930-174142-hood950 does not exist, ResourceDoesNotExist: Cluster 1021-010705-qq51xgx3 does not exist, ResourceDoesNotExist: Cluster 1104-164710-rifle803 does not exist, ResourceDoesNotExist: Cluster 1109-182315-xfqh7kym does not exist, ResourceDoesNotExist: Cluster 1118-225929-owbsmhnd does not exist, SystemError: AST constructor recursion depth mismatch (before=93, after=79)
