### ISSUE TITLE
[BUG]: Change in UC Catalog Ownership to Hive Metastore Schema Owner After Executing UCX Table Migration workflow.

### ISSUE THREAD

**Issue by lmallepaddi** [databrickslabs/ucx#2890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

NFCU created a UC catalog with an SPN as the owner, managed by Terraform. After running the table migration workflow in UCX, the ownership of the UC catalog changes from the SPN to the owner of the recently migrated Hive metastore schema. Since these schemas are owned by human users, the UC catalog ownership is shifting to them. This issue has been replicated multiple times, and screenshots have been collected for reference, raising significant security concerns. They are currently using version 0.38.0 of UCX.

### Expected Behavior

After executing the UCX table migration, the UC catalog's ownership should remain with the Service Principal Name (SPN) that created it rather than the recent Hive Metastore schema owner. 

### Steps To Reproduce

1)Create a catalog using a Service Principal (in the DevOps pipeline), with the SPN as the catalog owner.
2)Set up a Hive metastore schema and table, assigning ownership to a human user (this ownership is visible from a UC-enabled cluster but not from a non-UC-enabled cluster).
3)Execute the UCX assessment workflow.
4)Update the table_mappings.csv file with the schema and table created in step 2.
5)Run the UCX table migration workflow.
6)Observe the ownership of the UC catalog change from the SPN to the owner of the schema created in step 2.

UCX version used: 0.38 

Other details:
1) Customer couldn't **Create Uber principal.** The tables with mount point references were migrated without issue.
2) Table Access control workspace setting is set to "off" 

### Cloud

Azure

### Operating System

Linux

### Version

via install.sh

**Comment by ericvergnaud** [comment]
Hi,
thanks for this.
We're struggling a bit to reproduce the issue...
We create a catalog with an owner (different from the current user).
We also create a schema and a table in the `hive_metastore`, and table mapping rules.
We then run the `table-migrate` workflow.
This does not affect the ownership of the catalog...
What are we missing ?

**Comment by lmallepaddi** [comment]
Hi @ericvergnaud  This was replicated on the customer environment. Not sure if there are any other environment settings that are causing this. I can schedule some time with the customer to go over this issue with you.
