### ISSUE TITLE
[BUG]: `UsedTable` incorrectly sets `is_read` for `spark.range(10).saveAsTable("a.b")`

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#2893]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`spark.range(10).saveAsTable("a.b")` presents table `a.b` with `is_read=True` and it has to be false

### Cloud

AWS

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by ericvergnaud** [comment]
Not really a bug, as stated in https://github.com/databrickslabs/ucx/pull/2772 this requires a dedicated PR
