### ISSUE TITLE
[FEATURE]: Support linting of git-hosted notebook tasks on jobs

### ISSUE THREAD

**Issue by asnare** [databrickslabs/ucx#2922]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

When a job task should run a notebook, the `notebook_task.source` indicates whether the path is a workspace path or should be located via the git-source configured in the job settings. 

Currently we always treat the path on a notebook task as a workspace paths, which fails if it's a path relative to the git-source.

### Proposed Solution

- [X] In the short-term: Notebook tasks whose path is relative to a git source should be flagged as not (yet) supported. Currently not detecting this leads to many downstream errors that are confusing and make it difficult to understand what the problem is.  
  #2924.
- [ ] In the long-term: we should support linting these as well.

### Additional Context

One of the downstream errors that we currently see is attempts to download workspace paths without a leading slash (`/`). (Such relative paths are invalid workspace paths.)

~[Here](https://github.com/databrickslabs/ucx/blob/dc6d9c76fcbbd2932dc0c51e834ace477421969d/src/databricks/labs/ucx/source_code/jobs.py#L217) is where we (currently) do not distinguish between workspace and git-source paths.~ (Fixed in #2924.)

**Comment by nfx** [comment]
we do support linting git repos with `lint-local-code` command. git integration works the way that only the owner of the git token can access the repo and no the administrator.
