### ISSUE TITLE
[BUG]: Assessment raises warnings on feature-tables /root and password permissions

### ISSUE THREAD

**Issue by william-conti** [databrickslabs/ucx#2925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The assessment is throwing a strange log output on the failures table:

![image (2)](https://github.com/user-attachments/assets/f294f55c-16c6-440e-8d8a-c952c7391c91)

This may indicate that the endpoints for feature-tables and passwords are not accessible anymore
https://github.com/databrickslabs/ucx/blob/main/src/databricks/labs/ucx/workspace_access/generic.py#L461-L471

### Cloud

AWS

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by gchandra10** [comment]
Ran UCX 0.41.0 on Azure WS. Need some clarity on what exactly the message meant. Was that something the customer removed or changed, that UCX is not able to get access to? Additional context to the message will help us understand it better.

**Comment by nfx** [comment]
Thank you for the feature request! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.
