### ISSUE TITLE
[BUG]: `create-catalog-schemas` does not apply possible group renaming when applying grants

### ISSUE THREAD

**Issue by JCZuurmond** [databrickslabs/ucx#2934]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we migrate grants during `create-catalog-schemas` command: https://github.com/databrickslabs/ucx/blob/38bd88b3d26b9e944bf6ce04868bddb54145bb00/src/databricks/labs/ucx/hive_metastore/catalog_schema.py#L61-L62

We do not take group renaming into account as in `MigrateGrants` 

https://github.com/databrickslabs/ucx/blob/38bd88b3d26b9e944bf6ce04868bddb54145bb00/src/databricks/labs/ucx/hive_metastore/grants.py#L778

Meaning the command might fail when groups are renamed when moving workspace level groups to account level.

### Expected Behavior

The group renaming should be applied when migrating grants in the `create-catalogs-schemas` (or anywhere for that matter). I suggest to reuse the `MigrateGrants` in the `create-catalog-schemas` logic.

### Steps To Reproduce

N.A.

### Cloud

Azure

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by sreekanthmunigati** [comment]
Here is the sequence of steps so far executed:
1)Customer Installed 0.35 version and after assessment run, group migration was done successfully but did NOT run the last step of the group migration which is running "remove-workspace-local-backup-groups". 
2)Customer continued with Table migration pre-requisites and as part of the Step 2.4: Create "Uber Principal" they were facing issues and we suggested them to install the latest version and latest version that time 0.38 also facing issues with running assessment itself (failed these tasks : assess_workflows run, assess_dashboards run) , so customer uninstalled and re-installed ucx again ( version 0.41 ) and ran the assessment again (again failed these tasks : assess_workflows run, assess_dashboards run) . 
3)As Uber Principal command is still failing , we suggested them to create manually -- so we manually created Uber Principal and continued with Table migration pre-requisites which is Step 2.5 Create Catalogs and Schemas , as part of that command we faced above issue mentioned on this bug.
