### ISSUE TITLE
[BUG]: `Language RUN not supported yet!`

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#2977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

fails

### Expected Behavior

`%run path/to/notebook` must be treated as an edge to a notebook

### Cloud

AWS

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by ericvergnaud** [comment]
Not sure what is meant by 'fail'. It doesn't fail. We lint the notebook being run. The current log is info for the dev team, it's not a failure. Is the expectation to NOT log the fact that we don't lint RUN cells themselves ?
