### ISSUE TITLE
[BUG]: create-catalogs-schemas command is granting permissions to internal workspace principal which is "users"

### ISSUE THREAD

**Issue by sreekanthmunigati** [databrickslabs/ucx#2986]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

As part of Table migration pre-requisites when we run the create-catalogs-schemas command , internally after creating the catalogs and schemas it is applying the existing permissions , as part of these grants it also granting to internal workspace principal which is "users" 

### Expected Behavior

This command should not apply grants to internal workspace principal "users" 

### Steps To Reproduce

1. Install  UCX 0.44 
2. Run the assessment 
3. Complete the group migration 
4. Follow the table migration pre-requisites and run the create-catalogs-schemas 

### Cloud

AWS

### Operating System

macOS

### Version

latest via Databricks CLI

### Relevant log output

```shell
16:25:36 DEBUG [d.l.lsql.core] Executing SQL statement: GRANT USE SCHEMA ON DATABASE `catalog`.`schema` TO `users`
16:25:36 DEBUG [databricks.sdk] POST /api/2.0/sql/statements/
> {
>  "format": "JSON_ARRAY",
>  "statement": "GRANT USE SCHEMA ON DATABASE `catalog`.`schema` TO `users`",
>  "warehouse_id": "xx"
> }
< 200 OK
< {
<  "statement_id": "01ef8b33-a2cb-182d-84c8-10288bd74f00",
<  "status": {
<   "error": {
<    "error_code": "BAD_REQUEST",
<    "message": "[RequestId=8bd10349-1d9b-4897-9990-e13015aeb9f8 ErrorClass=PRINCIPAL_DOES_NOT_EXIST] Could not f... (29 more bytes)"
<   },
<   "state": "FAILED"
<  }
< } (edited)
```

**Comment by JCZuurmond** [comment]
I expect that we should also skip admins group

**Comment by JCZuurmond** [comment]
It looks like we skip the `admins` group already: https://github.com/databrickslabs/ucx/blob/669b136cdef5027a0018712b5e211ef592cb5cae/src/databricks/labs/ucx/hive_metastore/grants.py#L679-L681
