### ISSUE TITLE
[FEATURE]: Ownership support for workspace paths, including notebooks

### ISSUE THREAD

**Issue by asnare** [databrickslabs/ucx#3003]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

We need to be able to determine the owner of workspace paths, such as notebooks. This is needed to associate a user with a resource, such as a notebook or python script.

### Proposed Solution

It's unclear how to use the SDK to determine the owner of a path that matches what the UI shows. However we should be able to use the permissions APIs to determine a user that has `CAN_MANAGE` on the path. If nothing better can be found, that user can be considered the owner.

### Additional Context

In PR #2761 we introduced a framework for determining the owners of objects. However the initial implementation does not determine a direct owner for workspace paths, meaning the fallback of a workspace or account administrator is used instead.

**Comment by nfx** [comment]
fixed in https://github.com/databrickslabs/ucx/pull/3047
