### ISSUE TITLE
Create mapping document from HMS tables to UC tables.

### ISSUE THREAD

**Issue by FastLee** [databrickslabs/ucx#304]
Create a "databases" table as part of the assessment.
This table will be used to track database migrations and be used to configure database targets for migration. 

| Column Name | Type | Description | Default Value |
| -------------- | ----- | ------------ |----|
| database | string | Original schema of the table | |
| upgrade_assessment | int | 0-Manual<br/>1-In Place<br/>2-CTAS<br/>3-Mixed| |
| target_catalog | string | Name of the Target Catalog | ucx_<workspace_id> |
| target_datbase | string | Name of the Target Database | original database name |
| workspace_id | string | A workspace ID of the HMS (Optional) | |
| views | int | 0-No Views <br/> 1-Views present | |
| upgrade_status | int | 0-Not Upgraded <br/> 1-Failed Upgrade <br/> 2-Partial Upgrade <br/> 3-Full Upgrade | 0 |
| upgrade_messages | string | Json with a list of all the upgrade errors. | empty |

**Comment by nfx** [comment]
@FastLee this configuration cannot be a table, because we don't have a way to edit/add/validate it from UI. But I see the important points on some of the logic. let's discuss them - 

1. what creates `upgrade_assessment`?
2. what defines the `target_catalog`? what is the source? which process?
3. why do we need `target_datbase`? why can't it be the original database name?
4. why do we need `upgrade_status` and `upgrade_messages`?

**Comment by FastLee** [comment]
1. The assessment process
2. It defaults to a default catalog for the migration, manually overriden.
3. If we want to redirect
4. To report back from the database migration step. And rerun as needed.

**Comment by FastLee** [comment]
Let's consider a notebook with UI to allow admins to update this table.

**Comment by nfx** [comment]
Let's close this issue in favor of resolving the https://github.com/databrickslabs/ucx/pull/307.

**Comment by FastLee** [comment]
I'm reopening this discussion. As we addressed the process in #307 we need to address this issue to make progress on table migrations.

**Comment by FastLee** [comment]
I would suggest a following.
We create a default mapping for the HMS.
By default all the databases and tables are mapped to a single catalog.
You can override the mapping at the HMS level/Database/Table.
We should annotate just the overrides.
The Structure Should be something like that:
| Element | Target | Notes|
| ---- | ---- | ---- |
| \<Root\> | UCX_Dev | Default mapping |
| Sales | Sales_Dev.Sales | Mapping to a different catalog |
| Production_Yield | Production.Yield | Overriding the catalog and the database name |
| Production_Yield.YOY_Yield | Production.Yield.YOY | Overriding the catalog database and table name |
| Playground | \<Skip\> | Marking a resource to be skipped |

The installer will create a configuration file with a single entry for the workspace. We will create a notebook that will provide a simple interface to override entries.
