### ISSUE TITLE
Handle Removing a warehouse after the install

### ISSUE THREAD

**Issue by FastLee** [databrickslabs/ucx#308]
Removing a warehouse after the install causes the jobs to fail.
We need to provide a clear error and allow users to edit the configuration file easily after the initial install.

**Comment by nfx** [comment]
Not clear issue, please include steps to reproduce

**Comment by FastLee** [comment]
Steps to reproduce

1.  Install UCX on a workspace.
2. Remove the warehouse you referenced in the installation and is referenced in the config.yml

**Comment by nfx** [comment]
So the last step fails, right?.. I'm afraid we have no control over error messages, as dashboard refresh task is handled by the platform.

Add it to "Known Issues" document
