### ISSUE TITLE
Groups migration fails if a local group is not found on the account level, when we explicitly select that group in config

### ISSUE THREAD

**Issue by mwojtyczka** [databrickslabs/ucx#312]
I run the tool with selected group. One of the group did not exist in the account. The tool failed and stopped.

Enclosed stacktrace and standard output.
[stacktrace.txt](https://github.com/databrickslabs/ucx/files/12746443/stacktrace.txt)

**Comment by nfx** [comment]
At the moment, it's the expected behavior. Run with auto:true with groups config

**Comment by mwojtyczka** [comment]
It would be better if the tool just log the issue without failing.

**Comment by mwojtyczka** [comment]
Why? We would just skip this particular group and continue running for other group. 
Does that issue also exist if we run it for all groups?

**Comment by nfx** [comment]
to properly support this, we have to be able to re-run the group migration step

**Comment by zpappa** [comment]
Agree with @nfx - this should be idempotently runnable.
