### ISSUE TITLE
If a view uses a function, we need to expose whether or not that function CAN be migrated

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#315]
If a view uses a function, we need to expose whether or not that function CAN be migrated.

_Originally posted by @zpappa in https://github.com/databrickslabs/ucx/pull/307#discussion_r1339110661_

**Comment by pohlposition** [comment]
Are we even inventorying all functions?  If not, that can be part of this issue.

**Comment by nfx** [comment]
fixed in https://github.com/databrickslabs/ucx/issues/1610
