### ISSUE TITLE
Fetching workspace name inside of a workspace

### ISSUE THREAD

**Issue by william-conti** [databrickslabs/ucx#318]
We need a proper way to fetch the workspace name in order to easily specify the target catalog.

On AWS, we can do it by using:

`dbutils.notebook.entry_point.getDbutils().notebook().getContext().browserHostName().toString()`
This will return: workpace-name.cloud.databricks.com

[Reference on SO](https://stackoverflow.com/questions/70932930/how-to-get-workspace-name-inside-a-python-notebook-in-databricks)

In Azure, the above command doesn't work and returns the workspace ID, which is not convenient for catalog names

**Comment by pohlposition** [comment]
The only place I'm aware of in the API to retrieve the workspace_id is in the metastore assignment for the workspace (which will only exist after a metastore has been assigned to a workspace)
https://docs.databricks.com/api/workspace/metastores/current

**Comment by nfx** [comment]
we can get the workspace ID from SDK as well. but still - it's not a human-readable name. after a bunch of internal threads, I can certify there are no supported ways, nor there are hacks to retrieve this
