### ISSUE TITLE
Install a global init script to collect HMS lineage for a few weeks

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#324]

**Comment by pohlposition** [comment]
This seems like relatively low-effort, and urgent in the sense that the sooner we deliver; the sooner we have this assessment data to use downstream.

**Comment by pohlposition** [comment]
Script is defined here:
go/hms/lineage

**Comment by nfx** [comment]
At which step should we install the global init script? During assessment or during installation?

**Comment by dipankarkush-db** [comment]
We would also need to add the spark config to SQL WH config. @nfx
