### ISSUE TITLE
[BUG]: Tables not updated when re-running assessment

### ISSUE THREAD

**Issue by malig2001** [databrickslabs/ucx#3274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After the first run of the assessment, we cleaned up our workspace (deleted managed tables and unneeded schemas) and ran the assessment again, but the dashboard still shows the already deleted tables + schemas.

### Expected Behavior

After running the assessment, it should update all data and delete already deleted schemas + tables.

### Cloud

Azure

### Operating System

Windows

### Version

latest via Databricks CLI

**Comment by nfx** [comment]
assessment is not supposed to be run more than once per installation. Run the `migration-progress` workflow to repeatedly scan the hive metastore after the initial assessment is done. Dashboards will pick data up from there.
