### ISSUE TITLE
Compute size of `MANAGED` tables on DBFS root

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#330]
Add a task to assessment workflow right after `crawl_tables` to compute table size:

# + show tblproperties db.table
spark._jsparkSession.table("db.table").queryExecution().analyzed().stats().sizeInBytes()

**Comment by pohlposition** [comment]
This table size will come in handy when users decide what they want to do with these tables.

Small tables can easily be upgraded to UC
Large tables may reside where they lay for a long time.  After we release HMS Federation, there may not be a need to upgrade them.

**Comment by nfx** [comment]
when hms federation is out?

**Comment by pohlposition** [comment]
Q4
