### ISSUE TITLE
Migrate views

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#331]
1. Make a "best effort" attempt to upgrade view
1. Create a view in the new location
1. Upgrade table reference to the new tables (based on the `upgraded_to` table property)
1. Handle nested views
1. Handle or highlight other cases (functions/storage references/ETC)
1. Create an exception list with views failures
1. Topologically sort all views, as there might be cross-dependencies

Upstream dependencies:
- https://github.com/databrickslabs/ucx/issues/670

Related issues:
- https://github.com/databrickslabs/ucx/issues/315

**Comment by zpappa** [comment]
Add in ordering for nested views
