### ISSUE TITLE
Allow running assessment on a group of workspaces.

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#336]

**Comment by pohlposition** [comment]
Is this a dependency for other issues?  If so, which ones?

This can be a nice feature, but we shouldn't assume it will be possible for all customers to run such a thing at the account level.  Likewise, we should assume that additional workspaces will be created during the course of an upgrade; and therefore need to be assessed as well.

**Comment by zpappa** [comment]
Let's deprioritize this for now.

But let's ensure that we include workspace_id in every table so that this becomes possible in the future.

**Comment by nfx** [comment]
closing in favor of https://github.com/databrickslabs/ucx/issues/674
