### ISSUE TITLE
[BUG]: Error while installing UCX 0.47.0 (LakeviewAPI.create() got an unexpected keyword argument 'parent_path')

### ISSUE THREAD

**Issue by raghurampeddi-db** [databrickslabs/ucx#3381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While installing UCX 0.47.0 version, I got the below error. Dashboards are not created.
```
TypeError: LakeviewAPI.create() got an unexpected keyword argument 'parent_path'
21:52:37 ERROR [d.l.blueprint.parallel][installing_dashboards_1] installing
```

### Expected Behavior

Dashboards are supposed to be created.

### Cloud

AWS

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by Trifa01** [comment]
I have the same issue on the **UCX v0.50.0** with **Databricks Cli v0.223.2**
