### ISSUE TITLE
Return inventory of objects to be migrated per Group

### ISSUE THREAD

**Issue by amywang718** [databrickslabs/ucx#34]
If there's a huge list of groups to migrate, let's run through the objects and return the number of objects associated with each group that needs to be migrated. Useful if some groups have very few objects and be quick to migrate.

Also would be useful for tests and validation.

Requires https://github.com/databrickslabs/ucx/issues/241

**Comment by nfx** [comment]
To design this in scope of working with multiple workspaces within account

**Comment by nfx** [comment]
Following up - is this issue still relevant?

**Comment by nfx** [comment]
with the new permission migration backend we won't need it. hence, this issue won't be worked on.
