### ISSUE TITLE
[BUG]: Python wheel with name databricks_labs_ucx could not be find while running ucx assessment job using v 0.51.0

### ISSUE THREAD

**Issue by r-naidu** [databrickslabs/ucx#3404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

ucx installation was successful but all the taks are failing on running the workflow for ucx assessment 

### Expected Behavior

the assessment should have gone through as the dependent library wheel file is added to the compute, the logs says, it copied the file from workspace->Application->uxc->wheel but unable to install it on the compute used while executing the task

### Cloud

AWS

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by JCZuurmond** [comment]
@r-naidu : Are you using an external Hive metastore? You mentioned this issue started with the DBR 16, they bumped the JDK version which might cause issue with older Hive metastores (https://docs.databricks.com/en/release-notes/runtime/16.0.html#breaking-change-jdk-17-is-now-the-default)

We have seen this issue before when the cluster was not able to install UCX or its dependencies. That might be the case too.

**Comment by r-naidu** [comment]
By changing the DBR version on cluster policy, the issue got resolved. Btw, how does it matter if its an external metastore or DBX Metastore?

**Comment by JCZuurmond** [comment]
You might require (Java) software to connect to your exHMS, thus the change in runtime can have influence on that software due to the version bump

**Comment by JCZuurmond** [comment]
@r-naidu : I expect that the external HMS does not support the latest DBR, something I cannot confirm unfortunately. @r-naidu : Please reach out to confirm that, closing the ticket for now
