### ISSUE TITLE
Upgrade fails the Assessment Report

### ISSUE THREAD

**Issue by pohlposition** [databrickslabs/ucx#348]
I installed release 0.1.1

I deleted the .ucx folder
I deleted the workflows
I deleted the dashboards
I did NOT delete the tables in the ucx database

I installed release 0.2.0
I ran the "assessment run" workflow

All of the tasks completed successfully, except for the final "assessment_report" task

The "External Locations" widget failed with:
**[TABLE_OR_VIEW_NOT_FOUND] The table or view `hive_metastore`.`ucx`.`external_locations` cannot be found. Verify the spelling and correctness of the schema and catalog. If you did not qualify the name with a schema, verify the current_schema() output, or qualify the name with the correct schema and catalog. To tolerate the error on drop use DROP VIEW IF EXISTS or DROP TABLE IF EXISTS.; line 4, pos 5**

<img width="906" alt="Screenshot 2023-09-29 at 2 03 56 PM" src="https://github.com/databrickslabs/ucx/assets/11743282/fe4d3ddc-2876-4cea-9c0e-69a7d074b868">

**Comment by pohlposition** [comment]
I think this might be because my fresh workspace that I'm running this in doesn't have any mount points.  The "guess_external_locations" passed just fine.  It could also be that I don't have any external tables in my HMS, just managed tables.  This is the DEBUG output from "guess_external_locations"

19:14 DEBUG [d.l.ucx.framework.crawlers] [hive_metastore.ucx.external_locations] fetching external_locations inventory
19:14 DEBUG [d.l.ucx.framework.crawlers] [spark][fetch] SELECT * FROM ucx.external_locations
19:14 DEBUG [d.l.ucx.framework.crawlers] [hive_metastore.ucx.external_locations] crawling new batch for external_locations
19:14 DEBUG [d.l.ucx.framework.crawlers] [spark][fetch] SELECT location FROM ucx.tables WHERE location IS NOT NULL
19:14 DEBUG [d.l.ucx.framework.crawlers] [hive_metastore.ucx.mounts] fetching mounts inventory
19:14 DEBUG [d.l.ucx.framework.crawlers] [spark][fetch] SELECT * FROM ucx.mounts

**Comment by AbhiDatabricks** [comment]
For me Access_clusters run fails with AnalysisException: You are trying to read a Delta table `spark_catalog`.`ucx`.`clusters` that does not have any columns.

Write some new data with the option `mergeSchema = true` to be able to read the table.
---------------------------------------------------------------------------

**Comment by FastLee** [comment]
The "StatementExecutionBackend" implementation of SaveTable requires at least one element in the rows list.

        if len(rows) == 0:
            return

        klass = rows[0].__class__

If "rows" is empty, no table will be created.

**Comment by nfx** [comment]
Okay, so we need to pre-create the schema for every single table. It's easily done - we just need a mapping between dataclass and table name.

@FastLee can you add that?

**Comment by FastLee** [comment]
Done!!!

**Comment by nfx** [comment]
Btw, if we have the installer require the SQL warehouse, then we can pre-create the database during the installation process itself. It may take additional minutes when warehouse is not running and gets started

**Comment by FastLee** [comment]
Take a look at my implementation. Let me know if I completely botched it.

**Comment by nfx** [comment]
@FastLee Implementation is fine, few minor comments

**Comment by dmoore247** [comment]
I just hit this error with `ucx 0.3.0`
