### ISSUE TITLE
Report on ADLSv1 and Azure Blob Storage as `EXTERNAL` table sources don't work with UC

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#355]
modify the queries for assessment report:

1. https://github.com/databrickslabs/ucx/blob/main/src/databricks/labs/ucx/assessment/queries/database_summary.sql
2. https://github.com/databrickslabs/ucx/blob/main/src/databricks/labs/ucx/assessment/queries/external_locations.sql
3. https://github.com/databrickslabs/ucx/blob/main/src/databricks/labs/ucx/assessment/queries/all_tables.sql

**Comment by nfx** [comment]
We only support `abfss://` storage paths and `wasbs://` and `adl://` are not allowed according to @dipankarkush-db, please check with other people as well

**Comment by nfx** [comment]
@dipankarkush-db please also explain how to differentiate ADLS gen1 & blob storage from ADLS gen2 urls

**Comment by dipankarkush-db** [comment]
Look at the first Note section [here](https://learn.microsoft.com/en-us/azure/databricks/storage/azure-storage). 

```Note

The legacy Windows Azure Storage Blob driver (WASB) has been deprecated. ABFS has numerous benefits over WASB. See [Azure documentation on ABFS](https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-abfs-driver). For documentation for working with the legacy WASB driver, see [Connect to Azure Blob Storage with WASB (legacy)](https://learn.microsoft.com/en-us/azure/databricks/archive/storage/wasb-blob).
Azure has announced the pending retirement of [Azure Data Lake Storage Gen1](https://learn.microsoft.com/en-us/azure/data-lake-store/data-lake-store-overview). Azure Databricks recommends migrating all data from Azure Data Lake Storage Gen1 to Azure Data Lake Storage Gen2. If you have not yet migrated, see [Accessing Azure Data Lake Storage Gen1 from Azure Databricks](https://learn.microsoft.com/en-us/azure/databricks/archive/storage/azure-datalake).
```

For blob storage using _wasbs_ driver  we have to look for is "wasbs://" - https://learn.microsoft.com/en-us/azure/databricks/archive/storage/wasb-blob

For ADLS gen 1 the protocol we have to look for is "adl://" - https://learn.microsoft.com/en-us/azure/databricks/archive/storage/azure-datalake

**Comment by larsgeorge-db** [comment]
So the `location` contains the scheme we need to handle, what should we flag this as? `INCOMPATIBLE_STORAGE` or similar?
 
<img width="812" alt="image" src="https://github.com/databrickslabs/ucx/assets/136075433/ae344b76-e480-4814-8792-0b6bd4ebbb60">

**Comment by larsgeorge-db** [comment]
> modify the queries for assessment report:
> 
> 1. https://github.com/databrickslabs/ucx/blob/main/src/databricks/labs/ucx/assessment/queries/database_summary.sql
> 2. https://github.com/databrickslabs/ucx/blob/main/src/databricks/labs/ucx/assessment/queries/external_locations.sql
> 3. https://github.com/databrickslabs/ucx/blob/main/src/databricks/labs/ucx/assessment/queries/all_tables.sql

@nfx I am unclear why #2 is needing a change, you mean we add a `WHERE` clause that filters out the incompatible types based on the `storage` column value I suggested above?

**Comment by dipankarkush-db** [comment]
assessment report saying incompatible storage is all we need i suppose. The upgrade has to happen as a separate process. Thanks!

**Comment by FastLee** [comment]
Should we add "failures" field as we have on other assets?

**Comment by FastLee** [comment]
We can also include it in the report.

**Comment by larsgeorge-db** [comment]
@FastLee @dipankarkush-db this is an interesting discussion, as in, how much do we _recompute_ in each step, and how much do we inject into the inventory when it is build? Some as Liran is pointing out is already adding this as an extra field during the assessment run. Yet the initial tables scan does not add anything. Should we? Is the `location` (plus maybe others like `object_type`) the only field that determines something, or are there more columns needed to prepare for later steps to take action?

**Comment by larsgeorge-db** [comment]
<img width="876" alt="image" src="https://github.com/databrickslabs/ucx/assets/136075433/021ec2c1-8f30-43a4-8bcb-f221c3698961">

**Comment by larsgeorge-db** [comment]
Actually using `UNSUPPORTED` now.

**Comment by larsgeorge-db** [comment]
<img width="923" alt="image" src="https://github.com/databrickslabs/ucx/assets/136075433/0db3c41c-01a2-4918-94b0-306104dd5616">

**Comment by larsgeorge-db** [comment]
I added `unsupported` also into the DB summary query and then added some logic to show this in the `upgrade` column.
