### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by Sanket-Mehta** [databrickslabs/ucx#368]
Hi Team, I tried installing the tool via command line after installing Databricks CLI. I'm attaching the screenshots of the error message here. Unable to make any sense of what's causing the issue! 

Could you check and help. 

Thanks!
<img width="956" alt="image" src="https://github.com/databrickslabs/ucx/assets/145981453/af087cdb-e187-479b-a559-6ccc8b8f9f4f">
![image](https://github.com/databrickslabs/ucx/assets/145981453/c492a2cc-1f6c-4e8b-8c3e-bd2bfe79401d)

**Comment by nfx** [comment]
hi @Sanket-Mehta , the errors stack traces (javascript) are irrelevant to UCX (python)
