### ISSUE TITLE
Report for building Inventory with Groups and Associated ACLs for all workspace object

### ISSUE THREAD

**Issue by pradeepravi87** [databrickslabs/ucx#37]
Currently, the inventory building exercise is very much manual where we need to ask the customer about groups & associated permissions, no of workspace objects & associated ACLs, what is being provisioned by SCIM, what is provisioned manually etc. This exercise is time-consuming and most of the time the customer wouldn't be able to give accurate details if the workspace scale is bigger. The other problem is the collision of group names in different workspaces, so when we migrate on the account level it leads to confusion, knowing this collision advance will help the customers to take business/process decisions in advance

Here the proposal is to build the inventory in an automated way for every workspace entity & their associated ACLs and the workspace local group collision, so we would know roughly how many API calls we would be making to do a ballpark calculation on how long the migration utility will take to complete the migration & we can also use the same to fine-tune the cluster/HMS pool connections/exponential backoff values t

**Comment by nfx** [comment]
it's already done
