### ISSUE TITLE
Add Table Migration Progress Chart to a dashboard

### ISSUE THREAD

**Issue by FastLee** [databrickslabs/ucx#377]
Add support for pie charts and include a widget for table migration progress.
This will then be used for all the other migration elements.

**Comment by larsgeorge-db** [comment]
I can add the support for Pie charts, but where do we get the progress value from? What query does retrieve that? @FastLee

**Comment by nfx** [comment]
can't it be a % counter?

**Comment by nfx** [comment]
duplicate of https://github.com/databrickslabs/ucx/issues/652
