### ISSUE TITLE
`crawl_permissions` takes too long to run on a large workspace

### ISSUE THREAD

**Issue by dmoore247** [databrickslabs/ucx#380]
In testing the assessment job on a large (3000+ user workspace) `crawl_permissions` takes over 8 hours to run. This job has not run to completion for this workspace, starting with ucx 0.2.0, also on ucx 0.3.0

Suggest... 
a. make it run faster (more threads)
b. do less work
c. make it do save checkpoints and re-start from where it last failed.

**Comment by nfx** [comment]
we cannot defy the laws of physics with networking...

**Comment by nfx** [comment]
This would make migration of local groups impossible

**Comment by dmoore247** [comment]
@nfx The api runs at 4-50 requests per second. The API is pretty slow on a good day (>1 second each call)

I just noticed, we default parallelism to 8 but number of vCPUs per driver/worker is 2 so we're over subscribed.

**Comment by nfx** [comment]
@dmoore247 Python Global Interpreter Lock doesn't have any effect on IO, so CPU oversubscription concerns are not applicable here
