### ISSUE TITLE
feature: Run the assessment dashboard workflow if *any* upstream task succeeds

### ISSUE THREAD

**Issue by dmoore247** [databrickslabs/ucx#381]
Related #380, in case of failure of individual assessment tasks, do run the final dashboard. 
This enhancement requires one change to the assessment dag.

**Comment by dmoore247** [comment]
@nfx feel free to assign to me.

**Comment by nfx** [comment]
@dmoore247 propose your changes in a PR and attach a screenshot of the DAG

**Comment by FastLee** [comment]
I'm not sure. You can always run it manually. It brings awareness of the failure.

**Comment by nfx** [comment]
@dmoore247 does the job fail if one of the middle tasks fails?

**Comment by dmoore247** [comment]
@nfx prior to proposed change, the `crawl_permsions` task fails, failing the whole job.

**Comment by nfx** [comment]
@dmoore247 and after the proposed change?

**Comment by nfx** [comment]
this issue won't be worked on.
