### ISSUE TITLE
crawl_permissions fails: `DatabricksError: Workspace X exceeded the concurrent limit of 20 requests.`

### ISSUE THREAD

**Issue by dmoore247** [databrickslabs/ucx#401]
During the workspace analysis, crawl permissions fails with a concurrent limit of 20 exceeded.

release: `0.3.0`
<img width="1107" alt="image" src="https://github.com/databrickslabs/ucx/assets/1122251/02f804c0-058f-4943-960e-ac27d7385fb0">

Notice that the crawl starts out at 50 rps and slows to 5 rps.

**Comment by nfx** [comment]
50rps -> 5rps is not noticeable via screenshot

**Comment by nfx** [comment]
Fixed in v0.6.0
