### ISSUE TITLE
Record errors from `parallel.Threads` in `$inventory.failures`, so that it's possible to report on that

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#406]
Modify these places: https://github.com/search?q=repo%3Adatabrickslabs%2Fucx%20%22https%3A%2F%2Fgithub.com%2Fdatabrickslabs%2Fucx%2Fissues%2F406%22&type=code
to persist errors in a `$inventory.failure`
to display on a dashboards

**Comment by zpappa** [comment]
To be discussed

Needs refinement

**Comment by pohlposition** [comment]
Serge says it's closed :)
