### ISSUE TITLE
workspace_start_path is ignored during workspace listing

### ISSUE THREAD

**Issue by william-conti** [databrickslabs/ucx#427]
When a user set `workspace_start_path` in `config.yml` it is completly ignored by WorkspaceListing and it scans all the user paths. 

![image](https://github.com/databrickslabs/ucx/assets/107417584/6d63392a-c448-424e-915a-1cb615a73f40)

**Comment by larsgeorge-db** [comment]
@pritishpai could you open a PR for just this fix (and not dropping a dependency) please?

**Comment by nfx** [comment]
fixed in https://github.com/databrickslabs/ucx/commit/1d6377e2b48cca1e566d71b2b5cf71a4933ae7da
