### ISSUE TITLE
Notebook task logging

### ISSUE THREAD

**Issue by FastLee** [databrickslabs/ucx#434]
Create file based logging for notebook tasks.
Create a notebook to set a file based logger for notebook tasks.
Include this notebook with every notebook.
Use the provided parameters
(config, run_id, workflow) to place the log files in the same folder as all the other tasks.
Add some logging to the table crawler scala code.

**Comment by nfx** [comment]
why we need this? we want to keep scala code limited to existing single notebook. there's no testing for it.

**Comment by nfx** [comment]
we already have logging support for python tasks, see debug notebook.
