### ISSUE TITLE
'is_delta' column on the dashborad query showing "no" for all delta tables

### ISSUE THREAD

**Issue by tamilselvanveeramani** [databrickslabs/ucx#438]
'is_delta' column on the dashborad query showing "no" for all delta tables. is it expected ? what's the significance of this field ? as 'Format' is already showing the data format in the table

<img width="940" alt="image" src="https://github.com/databrickslabs/ucx/assets/93284829/12fc61dd-4843-4228-b228-758ace9fa4c5">

**Comment by william-conti** [comment]
@larsgeorge-db From the git history it looks like you've added this column in the dashboard, could you please elaborate ?

**Comment by larsgeorge-db** [comment]
I did not, the query always contained this field. @FastLee created this query initially.
