### ISSUE TITLE
feature: handle `s3fs` library, `s3fs.S3FileSystem` calls

### ISSUE THREAD

**Issue by dmoore247** [databrickslabs/ucx#443]
One pattern I've seen is users using s3fs to access files on S3 buckets.
The the assessment tools, job migration tools, notebook migration tools should flag on this library.
Recommended upgrade strategy is to migrate to UC Volumes.

# Proposed solution

yield Deprecation for all `s3fs` imports

**Comment by dmoore247** [comment]
In fact, the databricks.pixels solution accelerator uses this pattern to access Dicom files :) I'm working with the author ( me ) to migrate it.

**Comment by nfx** [comment]
Why do you need to call api from UDF?

**Comment by pohlposition** [comment]
there's likely more boto out there than s3fs
