### ISSUE TITLE
Workspace Listing Fails: AttributeError: 'NoneType' object has no attribute 'name'

### ISSUE THREAD

**Issue by dipankarkush-db** [databrickslabs/ucx#463]
Here is the stack trace 

`14:29:03 DEBUG [databricks.labs.ucx.workspace_access.listing] {ThreadPoolExecutor-0_0} Listed /Users/222@databricks.com/06-test-bed/LLMs/123@databricks.com/databricks-tpc-di/src/tools/datagen/pdgf/logs, found 0 sub-directories and 0 other objects
14:29:03 DEBUG [databricks.sdk] {ThreadPoolExecutor-0_1} GET /api/2.0/workspace/list?path=/Users/eee@databricks.com/06-test-bed/LLMs/333@databricks.com/databricks-tpc-di/src/tools/datagen/pdgf/dicts
< 200 OK
< {
<   "objects": [
<     {
<       "object_id": 810787046043000,
<       "object_type": "DIRECTORY",
<       "path": "/Users/444@databricks.com/06-test-bed/LLMs/555@databricks.com/databricks-... (41 more bytes)"
<     },
<     "... (1 additional elements)"
<   ]
< }
14:29:03 DEBUG [databricks.labs.ucx.workspace_access.listing] {ThreadPoolExecutor-0_1} Listed /Users/666@databricks.com/06-test-bed/LLMs/777@databricks.com/databricks-tpc-di/src/tools/datagen/pdgf/dicts, found 2 sub-directories and 0 other objects
14:29:03 DEBUG [databricks.sdk] {ThreadPoolExecutor-0_4} GET /api/2.0/workspace/list?path=/Users/121@databricks.com/06-test-bed/LLMs/222@databricks.com/databricks-tpc-di/src/tools/datagen/pdgf/dicts/pseudoTextGenerator
< 200 OK
< {}
14:29:03 DEBUG [databricks.labs.ucx.workspace_access.listing] {ThreadPoolExecutor-0_4} Listed /Users/222@databricks.com/06-test-bed/LLMs/333@databricks.com/databricks-tpc-di/src/tools/datagen/pdgf/dicts/pseudoTextGenerator, found 0 sub-directories and 0 other objects
14:29:03 DEBUG [databricks.sdk] {ThreadPoolExecutor-0_6} GET /api/2.0/workspace/list?path=/Users/ehwfhweh@databricks.com/06-test-bed/LLMs/uqwhdqw@databricks.com/databricks-tpc-di/src/tools/datagen/pdgf/dicts/tpc-e
< 200 OK
< {}
14:29:03 DEBUG [databricks.labs.ucx.workspace_access.listing] {ThreadPoolExecutor-0_6} Listed /Users/eee@databricks.com/06-test-bed/LLMs/vvv@databricks.com/databricks-tpc-di/src/tools/datagen/pdgf/dicts/tpc-e, found 0 sub-directories and 0 other objects
14:29:03 INFO [databricks.labs.ucx.workspace_access.listing] {MainThread} Recursive WorkspaceFS listing finished at 2023-10-16 14:29:03.815173. Total time taken for workspace listing: 0:04:21.947137
14:29:03 INFO [databricks.labs.ucx.workspace_access.listing] {MainThread} Made 7950 workspace listing calls, collected 27009 objects (7949 dirs and 19060 other objects), rps: 30.347/sec
14:29:03 ERROR [databricks.labs.ucx] {MainThread} Task crashed. Execute `databricks workspace export /Users/eee@databricks.com/.ucx/logs/assessment/run-171829288683725/workspace_listing.log` locally to troubleshoot with more details. 'NoneType' object has no attribute 'name'
14:29:03 DEBUG [databricks] {MainThread} Task crash details
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/tasks.py", line 149, in trigger
    current_task.fn(cfg)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/runtime.py", line 180, in workspace_listing
    crawler.snapshot()
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/generic.py", line 252, in snapshot
    return self._snapshot(self._try_fetch, self._crawl)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/crawlers.py", line 244, in _snapshot
    loaded_records = list(loader())
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/generic.py", line 249, in _crawl
    yield WorkspaceObjectInfo(_object.object_type.name, str(_object.object_id), _object.path, _object.language)
AttributeError: 'NoneType' object has no attribute 'name'
`

**Comment by wistreng** [comment]
Is there any fix for this?

**Comment by nfx** [comment]
fixed in https://github.com/databrickslabs/ucx/commit/50301a6884d77bd244820c4f30a6a66038d03bce
