### ISSUE TITLE
Assessment workflow failing

### ISSUE THREAD

**Issue by nayeemuddinmoin-db** [databrickslabs/ucx#465]
I am trying to run UCX assessment workflow in one of the test workspaces that I have created in Azure Databricks.
It is failing in workspace_listing task. I am attaching the log file.

[workspace_listing.log](https://github.com/databrickslabs/ucx/files/12927198/workspace_listing.log)

**Comment by jschuller** [comment]
Facing the same issue as reported in the attached log file

**Comment by sk7788775** [comment]
Facing the same issue as mentioned in the attached log file

**Comment by nfx** [comment]
this one is fixed in https://github.com/databrickslabs/ucx/commit/50301a6884d77bd244820c4f30a6a66038d03bce
