### ISSUE TITLE
Error during installation of latest version right after new release cut: Original error is: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by skantzidis** [databrickslabs/ucx#476]
Running on python 3.10.12.
Reverted back to 0.4.0 release version and was able to install this successfully.

~/ucx$ ./install.sh
[i] found Python 3.10.12 -> /usr/bin/python3.10
[i] found Python 3.10.12 -> /usr/bin/python3.10
[i] latest python is /usr/bin/python3.10
[i] installing venv into: /tmp/tmp.z1aOR1MWLT
[+] making sure we have the latest pip version
[+] installing dependencies within ephemeral Virtualenv: /tmp/tmp.z1aOR1MWLT
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/eclaveria/ucx/src/databricks/labs/ucx/install.py", line 700, in <module>
    installer.run()
  File "/home/eclaveria/ucx/src/databricks/labs/ucx/install.py", line 101, in run
    logger.info(f"Installing UCX v{self._version}")
  File "/home/eclaveria/ucx/src/databricks/labs/ucx/install.py", line 622, in _version
    raise OSError(msg) from None
OSError: Cannot determine unreleased version. Please report this error message that you see on https://github.com/databrickslabs/ucx/issues/new. Meanwhile, download, unpack, and install the latest released version from https://github.com/databrickslabs/ucx/releases. Original error is: 'NoneType' object has no attribute 'split'

**Comment by mirhendi** [comment]
I have same issue as well

**Comment by nfx** [comment]
Try now. Made a dummy commit, that should get you v0.5.1+1xxxxx installable through current main branch.

**Comment by mirhendi** [comment]
Fixed :) thank you

**Comment by nfx** [comment]
@skantzidis @mirhendi Does it work when you download a zip from releases and install it from there?

**Comment by skantzidis** [comment]
I assumed that the 0.5.0 release was broken as well, so I downloaded and installed 0.4.0 release successfully. 
I'll check the 0.5.0 release from releases as well to see if that works too. Thanks for prompt response.

**Comment by mirhendi** [comment]
Tested with the zip file and it's working fine as well

**Comment by nfx** [comment]
There's a small bug in the code that determines if the installation is from unreleased version or not. Perhaps we should remove it.

In general, main branch is now requiring all integration tests to pass, so it's generally safe to install just the latest.

Soon we'll have installation driven by Databricks CLI, so things will become easier

**Comment by nfx** [comment]
bug is fixed
