### ISSUE TITLE
Failure in “workspace_listing” task.

### ISSUE THREAD

**Issue by nikhilmish-db** [databrickslabs/ucx#478]
Job run URL: [Run 417698178508897 of REMOVED
 

org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 16.0 failed 1 times, most recent failure: Lost task 1.0 in stage 16.0 (TID 46) (172.19.45.104 executor driver): net.razorvine.pickle.PickleException: expected zero arguments for construction of ClassDict (for databricks.sdk.service.workspace.Language). This happens when an unsupported/unregistered class is being unpickled that requires construction arguments. Fix it by registering a custom IObjectConstructor for this class.

**Comment by nfx** [comment]
@nikhilmish-db Why do you post links to internal environments? Remove immediately

**Comment by nfx** [comment]
This is fixed in v0.5.0, please update.
