### ISSUE TITLE
Assessment job fails with Can't find a cluster policy with id: XXX

### ISSUE THREAD

**Issue by mwojtyczka** [databrickslabs/ucx#483]
The assessment job (assess_azure_service_principals run) fails with error: DatabricksError: Can't find a cluster policy with id: 3063AE1FA3002298.

**Comment by nfx** [comment]
Make it a warning then, not exception. Policy might have been deleted

**Comment by nfx** [comment]
@mwojtyczka Make a PR

**Comment by mwojtyczka** [comment]
will do
