### ISSUE TITLE
Install fails to write to dbfs:/ Workspace FS isn't enough to run the jobs

### ISSUE THREAD

**Issue by dmoore247** [databrickslabs/ucx#493]
At customer site, `dbfs:/` is blocked due to bucket policies. Writing the the /Workspace/Users/<email>/.ucx works.
The installer fails on the `dbfs:/` write. Jobs don't run off of the workspace FS.

We're blocked on the installer, trying to manually create the job from JSON and manually load the `.whl` file into an interactive cluster as a work around.

**Comment by dmoore247** [comment]
Solution hint: 
Because Interactive clusters support loading `.whl` files from WorkspaceFS, add interactive cluster (overrides) to `class WorkspaceConfig`. Update configuration and installer.  Overrides are used in integration testing today.

**Comment by nfx** [comment]
Also skip writing to dbfs when cluster overrides are active
