### ISSUE TITLE
Make Installer Prompts Optional

### ISSUE THREAD

**Issue by pohlposition** [databrickslabs/ucx#494]
Right now the installer requires user to answer several prompts.

It would be good if there was an option to ignore / override the prompts so that the installer could be run in a batch manner.

**Comment by nfx** [comment]
Let's do this only for upgrading mode of the installer.

**Comment by FastLee** [comment]
I know that the installer code support this behavior. I agree that may be usefull. Specifically if we want to script he install process.

**Comment by nfx** [comment]
already the case for v0.6.0
