### ISSUE TITLE
Add rate limit for get or create backup group to avoid failures

### ISSUE THREAD

**Issue by mwojtyczka** [databrickslabs/ucx#495]
The change introduced in [PR 453](https://github.com/databrickslabs/ucx/pull/453) should be reverted. Without this limit the creation of backup groups fails often.

**Comment by nfx** [comment]
@mwojtyczka please file ES tickets at platform/SDK to be doing HTTP429 status properly

**Comment by mwojtyczka** [comment]
how this is going to help? Retrying won't really help if we try to fire too many requests.

**Comment by mwojtyczka** [comment]
Fixed with [PR 500](https://github.com/databrickslabs/ucx/pull/500)
