### ISSUE TITLE
assess_jobs and assess_pipelines failing with error - pyspark.errors.exceptions.base.PySparkValueError: [CANNOT_BE_NONE] Argument `obj` can not be None.

### ISSUE THREAD

**Issue by amandeep-db** [databrickslabs/ucx#497]
While running the assessment workflow for one of the customer (Deere), we are getting failures for the tasks - “assess jobs” and “assess pipelines” with error - pyspark.errors.exceptions.base.PySparkValueError: [CANNOT_BE_NONE] Argument `obj` can not be None.

In the attached logs, we can see that the respective items are correctly fetched but the issue is occurring while creating the dataframe for saving those in the underlying table - https://github.com/databrickslabs/ucx/blob/main/src/databricks/labs/ucx/framework/crawlers.py#L135
But in the prior step i.e. https://github.com/databrickslabs/ucx/blob/main/src/databricks/labs/ucx/framework/crawlers.py#L129 we are already filtering the None type rows.

Slack conversation with Serge. ([Link](https://databricks.slack.com/archives/C05BEQ6GMN2/p1698089742904729))

Please refer the log files below for debugging and details regarding the error:

[assess_jobs.log](https://github.com/databrickslabs/ucx/files/13122027/assess_jobs.log)
[assess_pipelines.log](https://github.com/databrickslabs/ucx/files/13122028/assess_pipelines.log)

**Comment by william-conti** [comment]
Fixed in https://github.com/databrickslabs/ucx/commit/ebf66ad2226ffb56814c60d48201ca8395f43448
