### ISSUE TITLE
Workspace listing failure - KeyError: 'object_type'

### ISSUE THREAD

**Issue by jia-li-fl** [databrickslabs/ucx#521]
workspace_listing task fails with stacktrace below

19:27:39 INFO [databricks.labs.ucx.workspace_access.listing] {MainThread} Recursive WorkspaceFS listing finished at 2023-10-27 19:27:39.888857. Total time taken for workspace listing: 0:00:30.155382
19:27:39 ERROR [databricks.labs.ucx] {MainThread} Task crashed. Execute `databricks workspace export /Users/person@org/.ucx/logs/assessment/run-#######/workspace_listing.log` locally to troubleshoot with more details. 'object_type'
19:27:39 DEBUG [databricks] {MainThread} Task crash details
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/tasks.py", line 149, in trigger
    current_task.fn(cfg)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/runtime.py", line 292, in workspace_listing
    crawler.snapshot()
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/generic.py", line 260, in snapshot
    return self._snapshot(self._try_fetch, self._crawl)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/crawlers.py", line 229, in _snapshot
    loaded_records = list(loader())
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/generic.py", line 253, in _crawl
    object_type=raw["object_type"],
KeyError: 'object_type'

**Comment by Sanket-Mehta** [comment]
Hi Team, I'm also getting this same error despite using a PAT which has privileges to list the workspaces present within the account. (I've used REST API & SDK before to list workspaces!)

Also, do advise if we should raise a separate issue for this. Thanks!!

Below is the trace of error with info as well for reference:

```
KeyError: 'object_type'
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File ~/.ipykernel/1333/command--1-2074101964:18
     15 entry = [ep for ep in metadata.distribution("databricks_labs_ucx").entry_points if ep.name == "runtime"]
     16 if entry:
     17   # Load and execute the entrypoint, assumes no parameters
---> 18   entry[0].load()()
     19 else:
     20   import databricks_labs_ucx

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/runtime.py:445, in main(*argv)
    443 if len(argv) == 0:
    444     argv = sys.argv
--> 445 trigger(*argv)

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/tasks.py:149, in trigger(*argv)
    146         f.write(f"[run #{workflow_run_id}](/#job/{job_id}/run/{workflow_run_id})\n")
    148 try:
--> 149     current_task.fn(cfg)
    150 except BaseException as error:
    151     log_file_for_cli = str(log_file).lstrip("/Workspace")

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/runtime.py:292, in workspace_listing(cfg)
    288 ws = WorkspaceClient(config=cfg.to_databricks_config())
    289 crawler = WorkspaceListing(
    290     ws, RuntimeBackend(), cfg.inventory_database, num_threads=cfg.num_threads, start_path=cfg.workspace_start_path
    291 )
--> 292 crawler.snapshot()

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/generic.py:260, in WorkspaceListing.snapshot(self)
    259 def snapshot(self) -> list[WorkspaceObjectInfo]:
--> 260     return self._snapshot(self._try_fetch, self._crawl)

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/crawlers.py:229, in CrawlerBase._snapshot(self, fetcher, loader)
    227         raise err
    228 logger.debug(f"[{self._full_name}] crawling new batch for {self._table}")
--> 229 loaded_records = list(loader())
    230 self._append_records(loaded_records)
    231 return loaded_records

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/generic.py:253, in WorkspaceListing._crawl(self)
    250     continue
    251 raw = obj.as_dict()
    252 yield WorkspaceObjectInfo(
--> 253     object_type=raw["object_type"],
    254     object_id=str(raw["object_id"]),
    255     path=raw["path"],
    256     language=raw.get("language", None),
    257 )



KeyError: 'object_type'
UCX v0.5.0
Scans the workspace for workspace objects. It recursively list all sub directories
and compiles a list of directories, notebooks, files, repos and libraries in the workspace.

It uses multi-threading to parallelize the listing process to speed up execution on big workspaces.
It accepts starting path as the parameter defaulted to the root path '/'.
09:07  INFO [d.labs.ucx] After job finishes, see debug logs at /Workspace/Users/user@orgemail.com/.ucx/logs/assessment/run-7389056353990/workspace_listing.log

UCX v0.5.0
Scans the workspace for workspace objects. It recursively list all sub directories
and compiles a list of directories, notebooks, files, repos and libraries in the workspace.

It uses multi-threading to parallelize the listing process to speed up execution on big workspaces.
It accepts starting path as the parameter defaulted to the root path '/'.
09:07  INFO [d.labs.ucx] After job finishes, see debug logs at /Workspace/Users/user@orgemail.com/.ucx/logs/assessment/run-7389056353990/workspace_listing.log
09:07  INFO [d.l.u.workspace_access.listing] Recursive WorkspaceFS listing started at 2023-10-27 09:07:58.205758
09:07  INFO [d.l.u.workspace_access.listing] Made 10 workspace listing calls, collected 65 objects (50 dirs and 15 other objects), rps: 8.989/sec
09:07  INFO [d.l.u.workspace_access.listing] Made 20 workspace listing calls, collected 83 objects (52 dirs and 31 other objects), rps: 17.266/sec
09:07  INFO [d.l.u.workspace_access.listing] Made 30 workspace listing calls, collected 143 objects (65 dirs and 78 other objects), rps: 25.101/sec
09:07  INFO [d.l.u.workspace_access.listing] Made 40 workspace listing calls, collected 149 objects (68 dirs and 81 other objects), rps: 32.214/sec
09:07  INFO [d.l.u.workspace_access.listing] Made 50 workspace listing calls, collected 154 objects (71 dirs and 83 other objects), rps: 38.385/sec
09:08  INFO [d.l.u.workspace_access.listing] Made 60 workspace listing calls, collected 187 objects (84 dirs and 103 other objects), rps: 23.649/sec
09:08  INFO [d.l.u.workspace_access.listing] Made 70 workspace listing calls, collected 220 objects (92 dirs and 128 other objects), rps: 26.354/sec
09:08  INFO [d.l.u.workspace_access.listing] Made 80 workspace listing calls, collected 265 objects (99 dirs and 166 other objects), rps: 28.705/sec
09:08  INFO [d.l.u.workspace_access.listing] Made 90 workspace listing calls, collected 299 objects (107 dirs and 192 other objects), rps: 30.721/sec
09:08  INFO [d.l.u.workspace_access.listing] Made 100 workspace listing calls, collected 314 objects (108 dirs and 206 other objects), rps: 32.776/sec
09:08  INFO [d.l.u.workspace_access.listing] Recursive WorkspaceFS listing finished at 2023-10-27 09:08:01.929567. Total time taken for workspace listing: 0:00:03.724110
09:08 ERROR [d.labs.ucx] Task crashed. Execute `databricks workspace export /Users/user@orgemail.com/.ucx/logs/assessment/run-7389056353990/workspace_listing.log` locally to troubleshoot with more details. 'object_type'
```

**Comment by FastLee** [comment]
Can you provide us the databricks workspace export /Users/person@org/.ucx/logs/assessment/run-#######/workspace_listing.log file for the failed run?

**Comment by jia-li-fl** [comment]
What is the databricks workspace export file? Is it the "workspace_listing.log" file?

**Comment by Sanket-Mehta** [comment]
Team, for me I just went through the workspace_listing.log file and it seems that while it was able to list everything recursively and same is visible in the logs, however at the end I can see an error quoting 'task crashed'. I am checking with my team here for sharing the log file as it contains few confidential information.

However I am sharing the final error trace for reference:

 `09:08:01 INFO [databricks.labs.ucx.workspace_access.listing] {MainThread} Recursive WorkspaceFS listing finished at 2023-10-27 09:08:01.929567. Total time taken for workspace listing: 0:00:03.724110
09:08:01 ERROR [databricks.labs.ucx] {MainThread} Task crashed. Execute `databricks workspace export /Users/user@orgemail.com/.ucx/logs/assessment/run-7389056353990/workspace_listing.log` locally to troubleshoot with more details. 'object_type'
09:08:01 DEBUG [databricks] {MainThread} Task crash details
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/tasks.py", line 149, in trigger
    current_task.fn(cfg)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/runtime.py", line 292, in workspace_listing
    crawler.snapshot()
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/generic.py", line 260, in snapshot
    return self._snapshot(self._try_fetch, self._crawl)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/crawlers.py", line 229, in _snapshot
    loaded_records = list(loader())
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/generic.py", line 253, in _crawl
    object_type=raw["object_type"],
KeyError: 'object_type'`

Do let me know if it helps. Thanks! 

@FastLee

**Comment by dipankarkush-db** [comment]
> What is the databricks workspace export file? Is it the "workspace_listing.log" file?

Yes that file in workspace under the .ucx/logs/run-NNNNNN folder.

**Comment by jia-li-fl** [comment]
Is the workspace_listing.log file required? My log file has almost 11,000 lines with a lot of sensitive/confidential information.

**Comment by Sanket-Mehta** [comment]
Team, should I just raise another issue making it susceptible to be marked as duplicate later?? Although, this issue was raised by @jia-li-fl, I did provide few info up there. 

Will you be able to help? Thanks!!!

@FastLee @pohlposition @dipankarkush-db @nfx
