### ISSUE TITLE
jobs assessment task is erroring out while executing the workflow

### ISSUE THREAD

**Issue by vasanvs-db** [databrickslabs/ucx#524]
![image](https://github.com/databrickslabs/ucx/assets/108321900/03597d21-0bf9-4e43-9bac-1295f5022678)
![image](https://github.com/databrickslabs/ucx/assets/108321900/0ff412c2-eeb1-4265-bec7-f629a7d1cad6)

**Comment by william-conti** [comment]
Can you show the version that you used ? This issue is fixed by using the main branch (v0.5.1)

**Comment by nfx** [comment]
Duplicate of #503
