### ISSUE TITLE
Show databricks host(s) being used by install.sh.

### ISSUE THREAD

**Issue by dmoore247** [databrickslabs/ucx#531]
While running install.sh I notice that it doesn't provide feedback as to where the install is going. This is critical piece of information to ensure the environment isn't configured incorrectly.

**Comment by dmoore247** [comment]
If this is an upgrade, one does receive a warning with the environment, however for a fresh install, no such info is provided.

**Comment by nfx** [comment]
Thank you for the feature request! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.

**Comment by nfx** [comment]
Done
