### ISSUE TITLE
Job Clusters created on AWS should use auto-az

### ISSUE THREAD

**Issue by dmoore247** [databrickslabs/ucx#533]
I have jobs failing because they are running in AZs with limited or no availability of vm types being used.
The `zone_id` should equal `auto` in the job cluster configuration (`"zone_id": "auto",`)

**Comment by dmoore247** [comment]
User may see
```run failed with error message
 Cluster 9999-999999-z4wp51nk was terminated while waiting on it to be ready: Cluster 9999-999999-z4wp51nk is in unexpected state Terminated: AWS_UNSUPPORTED_FAILURE(CLOUD_FAILURE): aws_api_error_code:Unsupported,aws_error_message:Your requested instance type (m5d.large) is not supported in your requested Availability Zone (us-east-1e). Please retry your request by not specifying an Availability Zone or choosing us-east-1a, us-east-1b, us-east-1c, us-east-1d, us-east-1f..
 ```

**Comment by nfx** [comment]
Thank you for the feature request! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.

The change required is in the installer
