### ISSUE TITLE
Make rate limits configurable

### ISSUE THREAD

**Issue by mwojtyczka** [databrickslabs/ucx#535]
For bigger customers, we need to increase the API limits to be able to migrate faster. Currently, the rate limits (@rate_limited) are hardcoded. We need to be able to adjust them.

**Comment by nfx** [comment]
Thank you for the feature request! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.

**Comment by nfx** [comment]
Following up - is this issue still relevant?

**Comment by nfx** [comment]
closing issue as not relevant
