### ISSUE TITLE
Add version info when logs are created

### ISSUE THREAD

**Issue by larsgeorge-db** [databrickslabs/ucx#539]
Right now the log contain only a basic info message. But we need to know also what version of UCX that was. Add a line that prints this (and maybe other pertinent information, like the current user ID etc.):

```
21:09:32 INFO [databricks.labs.ucx] {MainThread} After job finishes, see debug logs at /Workspace/Users/**redacted**/.ucx/logs/assessment/run-769913644437118/workspace_listing.log
21:09:33 DEBUG [databricks.sdk] {MainThread} /root/.databrickscfg does not exist
21:09:33 DEBUG [databricks.sdk] {MainThread} Attempting to configure auth: pat
21:09:33 DEBUG [databricks.sdk] {MainThread} Attempting to configure auth: basic
21:09:33 DEBUG [databricks.sdk] {MainThread} Attempting to configure auth: metadata-service
...
```

**Comment by The5cheduler** [comment]
Hey @larsgeorge-db ,  If I understood it correctly, need to add current version of ucx while generating log?
What will be good starting point for me find where log is getting generated from?

**Comment by nfx** [comment]
The version should be in the standard output of a job run already, though not yet the logs. Tasks.py should be the place to modify

**Comment by larsgeorge-db** [comment]
Yes, see here https://github.com/databrickslabs/ucx/blob/main/src/databricks/labs/ucx/framework/tasks.py#L137

**Comment by The5cheduler** [comment]
Thank you both, @nfx and @larsgeorge-db , 
I am trying to reproduce logs, how can I do that?
I read through some documentation and could not find how can I reproduce logs.

**Comment by nfx** [comment]
Just run a workflow and see the logs created in the home directory

**Comment by The5cheduler** [comment]
Hey @nfx , I tried looking into workflows, I was not able to run it.
could you please include steps that I can possibly follow to run the workflow?
