### ISSUE TITLE
"Failure Summary" dashboard improvements

### ISSUE THREAD

**Issue by dmoore247** [databrickslabs/ucx#543]
1. Position summary at the top of the dashboard, right under counter boxes.
2. Change "Failure" to another word representative of items requiring more (manual?) work.
3. Add Descriptive box above
4. Transform into a manual / automated dashlet, contrast the numbers with the total for the category (or add dashlet with the counter example (e.g. delta table vs. non delta tables)
5. Add Database summary count(s) with upgrade paths (aggregate Database summary which is more of a table summary by database)
6. Add external Location summary count
7. Mountpoint Summary
8. Cluster summary counts
9. Job summary
10. Pipeline Summary
11. Init script summary

**Comment by nfx** [comment]
It looks like the issue is solved
