### ISSUE TITLE
External Location query dashlet returns multiple 'jdbc:/' which isn't useful

### ISSUE THREAD

**Issue by dmoore247** [databrickslabs/ucx#545]
Investigate and fix. Better result would have connection details (host) or not include this.

**Comment by dmoore247** [comment]
Also note, there were lots of duplicates, so let's dedupe the collections.

The `external_locations` table doesn't provide provenance information to track this down.
One theory of how this happened, an external table was created that points to a JDBC data source.

https://community.cloudera.com/t5/Community-Articles/How-to-integrate-Spark-with-Hive-nbsp-JdbcStorageHandler-in/ta-p/315929
```sql
CREATE EXTERNAL TABLE employee
(
  id BIGINT,
  name STRING,
  age INT,
  salary DOUBLE
)
STORED BY 'org.apache.hive.storage.jdbc.JdbcStorageHandler'
TBLPROPERTIES (
    "hive.sql.database.type" = "MYSQL",
    "hive.sql.jdbc.driver" = "com.mysql.jdbc.Driver",
    "hive.sql.jdbc.url" = "jdbc:mysql://localhost/test",
    "hive.sql.dbcp.username" = "username",
    "hive.sql.dbcp.password" = "password",
    "hive.sql.table" = "EMPLOYEE",
    "hive.sql.dbcp.maxActive" = "1"
);

**Comment by pritishpai** [comment]
Found the possible cause while recreating the issue. The UCX tool fetches the 'location' from the table properties while for an external location with jdbc, the host information is stored in 'storage properties'.

Fix would involve fetching storage properties while crawling tables and concatenating it in the external location dashlet.

<img width="1054" alt="image" src="https://github.com/databrickslabs/ucx/assets/136742693/9fe115ad-c342-419d-804d-cb45505fba0c">
