### ISSUE TITLE
Sync Nested AD Groups

### ISSUE THREAD

**Issue by pohlposition** [databrickslabs/ucx#550]
Some customers use nested AD groups and it has been requested to synchronize those with the groups in databricks as per this blog by @dipankarkush-db  and Abhishek Pratap

https://community.databricks.com/t5/technical-blog/how-to-sync-nested-azure-ad-groups-to-databricks/ba-p/44007

There's additional detail on this located at go/aad/nested

**Comment by nfx** [comment]
@pohlposition SCIM sync of nested AAD groups is out of scope for UCX. It has to be a top-level project instead. And most likely written in GoLang, for stability reasons.

**Comment by nfx** [comment]
@pohlposition i'm always hearing a lot of complaints from customers related to SCIM sync being a big pain and there are 2000 different hacky scripts available out there. I've think we need to roll out 2001'st in https://github.com/databrickslabs/group-flow and have it easy installable. [this blog](https://community.databricks.com/t5/technical-blog/how-to-sync-nested-azure-ad-groups-to-databricks/ba-p/44007) is a hack and is difficult to setup. go/aad/nested is still a hack

**Comment by pohlposition** [comment]
Sounds reasonable.  I wasn't aware of the group-flow effort

**Comment by nfx** [comment]
@pohlposition Well, I've created it just yesterday to prevent supporting difficult-to-setup hacks. As far as I'm aware, native implementation is not planned for the near future, so we need to make this the default non-native setup.
