### ISSUE TITLE
replace_workspace_groups_with_account_groups crashes if the groups is not found

### ISSUE THREAD

**Issue by fannijako** [databrickslabs/ucx#553]
The 03-replace_workspace_groups_with_account_groups job fails if the workspace group that it tries to delete is not existing. Due to the behaviour it is not possible to recover (with a job restart) on this error. A check is missing, which checks whether the group exists, before it tries to delete it.

Log from customer:
08:47:20 INFO [databricks.labs.ucx.workspace_access.groups] {MainThread} Deleting the workspace-level group idm2bcd_dssi03prod_vts_read with id 162842259944930
08:48:20 DEBUG [databricks.sdk] {MainThread} DELETE /api/2.0/preview/scim/v2/Groups/162842259944930
< 500 Internal Server Error
< {
<   "detail": "Max retries exhausted with RPC com.databricks.api.proto.users.GetAllUserIdsInGroup, max retry co... (6 more bytes)",
<   "schemas": [
<     "urn:ietf:params:scim:api:messages:2.0:Error"
<   ],
<   "status": "500"
< }
08:48:20 DEBUG [databricks.sdk] {MainThread} Retrying: DatabricksError is allowed to retry (sleeping ~1s)
08:48:21 INFO [databricks.labs.ucx.workspace_access.groups] {MainThread} Deleting the workspace-level group idm2bcd_dssi03prod_vts_read with id 162842259944930
08:48:21 DEBUG [databricks.sdk] {MainThread} DELETE /api/2.0/preview/scim/v2/Groups/162842259944930
< 404 Not Found
< {
<   "detail": "Group with id 162842259944930 not found.",
<   "schemas": [
<     "urn:ietf:params:scim:api:messages:2.0:Error"
<   ],
<   "status": "404"
< }

Tool tries to recover from it and fails after 20 minutes.

**Comment by pohlposition** [comment]
Once we have Group Rename API, this issue goes away.

**Comment by nfx** [comment]
Please upgrade to the latest version. It seems that the version you're referring is too old.
