### ISSUE TITLE
Backup group created without members after an internal server error

### ISSUE THREAD

**Issue by fannijako** [databrickslabs/ucx#555]
When an internal server error occurs, the backup group is created without members. The tool tries to recreate the backup group and fails the workflow.

Details:

`16:20:35 INFO [databricks.labs.ucx.workspace_access.groups] {MainThread} Creating backup group db-temp-idm2bcd_dssi03prod_millingdrilling_read
16:20:37 DEBUG [databricks.sdk] {MainThread} POST /api/2.0/preview/scim/v2/Groups
> {
>   "displayName": "db-temp-idm2bcd_dssi03prod_millingdrilling_read",
>   "members": [
>     {
>       "display": "*****",
>       "value": "**REDACTED**"
>     }
>   ],
>   "meta": {
>     "resourceType": "WorkspaceGroup"
>   }
> }
< 500 Internal Server Error
< {
<   "detail": "Failed to update members of group db-temp-idm2bcd_dssi03prod_millingdrilling_read",
<   "schemas": [
<     "urn:ietf:params:scim:api:messages:2.0:Error"
<   ],
<   "status": "500"
< }
16:20:37 DEBUG [databricks.sdk] {MainThread} Retrying: DatabricksError is allowed to retry (sleeping ~1s)
16:20:39 INFO [databricks.labs.ucx.workspace_access.groups] {MainThread} Creating backup group db-temp-idm2bcd_dssi03prod_millingdrilling_read
16:20:39 DEBUG [databricks.sdk] {MainThread} POST /api/2.0/preview/scim/v2/Groups
> {
>   "displayName": "db-temp-idm2bcd_dssi03prod_millingdrilling_read",
>   "members": [
>     {
>       "display": "*****",
>       "value": "**REDACTED**"
>     }
>   ],
>   "meta": {
>     "resourceType": "WorkspaceGroup"
>   }
> }
< 409 Conflict
< {
<   "detail": "Group with name db-temp-idm2bcd_dssi03prod_millingdrilling_read already exists.",
<   "schemas": [
<     "urn:ietf:params:scim:api:messages:2.0:Error"
<   ],
<   "status": "409"
< }
16:20:39 DEBUG [databricks.sdk] {MainThread} Retrying: DatabricksError is allowed to retry (sleeping ~2s)`

Related to: https://github.com/databrickslabs/ucx/issues/553

**Comment by nfx** [comment]
This is the platform issue

**Comment by nfx** [comment]
Please upgrade to the latest version. It seems that the version you're referring is too old.
