### ISSUE TITLE
Is this toolkit meant to handle table migration? Looking a the `hive_metastore.tables.TablesMigrate` class

### ISSUE THREAD

**Issue by jamiegl** [databrickslabs/ucx#560]
Was just looking at [`hive_metastore.tables.TablesMigrate`](https://github.com/databrickslabs/ucx/blob/ac7b8bb28fd6e993bc2cae42eabcd9b35cca196e/src/databricks/labs/ucx/hive_metastore/tables.py#L164) (and some of the members of the `Table` dataclass that generate migration SQL) and I'm trying to understand if automated table migration is actually part of this toolkit, if its something that is upcoming or if `TablesMigrate` is just a utility for users to make their own migration jobs with? I don't see it referenced anywhere apart from in tests.

I see in the [docs](https://github.com/databrickslabs/ucx/blob/main/docs/table_upgrade.md) it describes considerations for migrating tables, but it is unclear if is describing a process that `ucx` provides or if its suggesting a migration approach to the user for them to implement themselves.

I feel like the documentation could use a little more clarity here.

**Comment by nfx** [comment]
@jamiegl it is on the roadmap, but the feature implementation is not yet there. you can follow this board for more details: https://github.com/orgs/databrickslabs/projects/13
