### ISSUE TITLE
Startup--Should we run all the jobs at the beginning or just assessment?

### ISSUE THREAD

**Issue by jkayes** [databrickslabs/ucx#567]
The README.py is not clear about which Jobs to run immediately after installation. It says:

Go to the [assessment dashboard](https://e2-demo-field-eng.cloud.databricks.com/sql/dashboards/d6cc62ef-d71a-41e9-acd9-4bed390db016) after running the jobs.

All of them?

The non-Assessment ones have titles that sound like they'll actually make changes.

Neither of the READMEs really make clear what these jobs actually do.

**Comment by nfx** [comment]
Assessment is the first job that you have to run. Please read the readme notebook created in your homedir

**Comment by nfx** [comment]
Following up - is this issue still relevant?
