### ISSUE TITLE
Update README.md to accurately reflect Python version requirements

### ISSUE THREAD

**Issue by timstan-db** [databrickslabs/ucx#568]
The `README.md` currently says "Make sure you have Python 3.10 (or greater)". However the `install.sh` script fails if the Python version is < 3.10.6. Please update this to be accurate. 

Error message we received:

> ERROR: Package 'databricks-labs-ucx' requires a different Python: 3.10.4 not in '>=3.10.6'

**Comment by nfx** [comment]
Thank you for the feature request! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.
