### ISSUE TITLE
Improve README mentioning supported OSs

### ISSUE THREAD

**Issue by rodrigoimprota-db** [databrickslabs/ucx#577]
Noticed that in the interactive tutorial is mentioned that it's supported only MacOS, Linux and WSL on Windows but it's not mentioned anywhere on the README doc.

**Comment by nfx** [comment]
Thank you for the feature request! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.

**Comment by nfx** [comment]
Already implemented
