### ISSUE TITLE
Move metastore

### ISSUE THREAD

**Issue by dsfrederic-cgk** [databrickslabs/ucx#578]
Can this tool also migrate Databricks Unity Catalog Metastores? 

I don't see it mentioned

**Comment by nfx** [comment]
What is the usecase?

**Comment by pohlposition** [comment]
> What is the usecase?

+1 - where would you want to move it and why?

**Comment by dsfrederic-cgk** [comment]
I want to move it to a different storage account in Azure.

**Comment by nfx** [comment]
Thank you for the feature request! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.
