### ISSUE TITLE
No Support for HMS In Postgres & Workflow job cannot run on user-provided cluster 

### ISSUE THREAD

**Issue by afsana-afzal** [databrickslabs/ucx#581]
UCX does not currently support HMS in postgres and workflow job cannot run on user-provided cluster. Customer is using init scripts to connect to the external Postgresql-HMS, those scripts are in ADLS.

**Comment by nfx** [comment]
@afsana-afzal the workspace has to get metastore configuration into a cluster policy, otherwise UCX won't be able to recognize it.

**Comment by FastLee** [comment]
@afsana-afzal please follow the instructions here: https://github.com/databrickslabs/ucx/blob/main/docs/external_hms_glue.md
Report back if that doesn't work for you.

**Comment by nfx** [comment]
closed as per @FastLee  comment
