### ISSUE TITLE
Add Features to Assessment

### ISSUE THREAD

**Issue by pohlposition** [databrickslabs/ucx#589]
We should add a crawler to the assessment for Feature Store features.

This code has already been written by the field and just needs to be ported over.

An example can be found at go/uc/scripts (row 27)
"1. Assess Workspace Objects - Including MLFlow Models, Table NumFiles / SizeInBytes"

**Comment by nfx** [comment]
features don't have SDK, ML team has to add it first

**Comment by nfx** [comment]
it's not a good first issue, as features have no support in python SDK
