### ISSUE TITLE
Add Table Size to Assessment

### ISSUE THREAD

**Issue by pohlposition** [databrickslabs/ucx#590]
The Assessment captures data on Tables, but not the size of the table.  This information would be useful to determine the recommended upgrade path (CLONE vs FEDERATION).

The field has already written some code for this.  It would need to be incorporated.  An example can be found at go/uc/scripts (row 27) "1. Assess Workspace Objects - Including MLFlow Models, Table NumFiles / SizeInBytes"

**Comment by prajin-29** [comment]
![image](https://github.com/databrickslabs/ucx/assets/127273819/4ffab87b-1c3d-4138-93bd-3937e6969c06)

Table size already added in the dashboard under Table Types. Please find the above screen shot.
