### ISSUE TITLE
Add `mypy` into build process w/ databricks-sdk typings to guard quality further

### ISSUE THREAD

**Issue by dmoore247** [databrickslabs/ucx#619]
[Mypy](https://mypy.readthedocs.io/en/stable/) is a static type checking can flag None object dereferences, the root cause of #618 and other issues born out from the integration testing.

Mypy is used extensively in other python projects such as `sqlglot`.

**Comment by nfx** [comment]
Relevant PRs:
- https://github.com/databrickslabs/ucx/pull/696
- https://github.com/databrickslabs/ucx/pull/697
