### ISSUE TITLE
Assessment job failing on version 0.6.1

### ISSUE THREAD

**Issue by andres-zuniga** [databrickslabs/ucx#620]
Hello team,

I've been testing UCX in a personal environment. I have tried running the assessment job multiple times, and every time, I get the following errors:

> DeltaCommitRejectException: rejected by server 26 times, most recent error: HTTP request failed with status: HTTP/1.1 401 Unauthorized

 on the "crawl_tables" task.

> [Errno 1] Operation not permitted: ’/Workspace/Users/[andres.zuniga@databricks.com](mailto:andres.zuniga@databricks.com)/.ucx/config.yml’

 on the "crawl_mounts" task as well as clusters, init scripts, jobs, pipelines, and groups tasks.

Based on the errors, I assume this is related to permission, but I'm the admin of the metastore and the workspace, and I have all privileges on the hive_metastore.

A couple of weeks back, I tested this using the 0.5.0 version with a similar environment, and it worked perfectly, but now it's failing with these errors.

I'm also attaching a .zip file with the exported HTML of the 401 error.

I haven't tested with the 0.6.0 or 0.5.0 version, but I can try if necessary.

**Comment by nfx** [comment]
@andres-zuniga I think it's most likely related to platform issues. Please attach log files as a link to gist.github.com

**Comment by andres-zuniga** [comment]
Apologies @nfx , here is the gist: https://gist.github.com/andres-zuniga/db225370b052c96bd38b982ba50cd1ab

**Comment by nfx** [comment]
@andres-zuniga this is a platform issue and has nothing to do with UCX, please take it up the delta team channels.
