### ISSUE TITLE
Mount Point crawler lists /Volume with four variations which is confusing

### ISSUE THREAD

**Issue by dmoore247** [databrickslabs/ucx#622]
In the Mount Point crawler, how do we end up with four spellings for Volume ?
I think we should clean this up in UCX and escalate to platform.
We can also enhance this view with a action/recommendation column.

/ | DatabricksRoot |  
-- | -- | --
/Volume | DbfsReserved |  
/Volumes | UnityCatalogVolumes |  
/databricks-datasets | databricks-datasets |  
/databricks-results | databricks-results |  
/databricks/mlflow-registry | databricks/mlflow-registry |  
/databricks/mlflow-tracking | databricks/mlflow-tracking |  
/volume | DbfsReserved |  
/volumes | DbfsReserved

**Comment by nfx** [comment]
Thank you for the feature request! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.

**Comment by dipankarkush-db** [comment]
closed by https://github.com/databrickslabs/ucx/pull/779
