### ISSUE TITLE
Installation flow query/issue

### ISSUE THREAD

**Issue by Sanket-Mehta** [databrickslabs/ucx#624]
Hi Team,

In the installation flow, we have one step where one is asked to either select to create a new SQL Warehouse or chose an existing SQL Warehouse to run the dashboard queries. This lists out the warehouses it detects in the workspace provided access to via URL & PAT.

We have been trying UCX since v0.5.0 in different internal workspaces and observed something w.r.t this step:

"If we somehow specify or chose a warehouse which doesn't get started due to any reason whatsoever, we can't rely on just modifying the config.yml later and hope for it to reflect correct warehouse to run queries & dashboard in later Assessment job run."

Is it possible to get the warehouse step again when one tries to re-install using `./install.sh` command after installing UCX, or is there any design consideration at place which we as users have to be aware of?

Thanks!!!

**Comment by nfx** [comment]
Thank you for the feature request! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.

**Comment by FastLee** [comment]
You can rerun install.sh again and the dashboard will be updated.
No need to rerun the workflow.

**Comment by Sanket-Mehta** [comment]
Hi @FastLee, actually it isn't about the dashboard refresh. It is about the option to select the SQL Warehouse doesn't come up in re-running install.sh!

Please check the description again! Thanks!

As @nfx mentioned, we'll try to create a PR for this as this is a workflow enhancement in our opinion. Thanks!!
