### ISSUE TITLE
Add pagination when listing workspace groups 

### ISSUE THREAD

**Issue by william-conti** [databrickslabs/ucx#625]
In groups.py, there are multiple calls made on group listing that returns multiple attributes ("id,displayName,meta,members,roles,entitlements" as a minimum)

This call often raises a timeout when there is large amount of groups in the Workspace, this is because each calls returns the entire groups and a lot of attributes.

TODO:

- Identify all ws.groups.list calls that are possibly unsafe
- Add count and start_index to each call to ws.groups.list ([doc](https://databricks-sdk-py.readthedocs.io/en/latest/workspace/groups.html#GroupsAPI.list))
- The number should be a balance between reliability and performance (ie:50 as a starting point)
- Ideally, this number can be modified in the configuration file
- Add an integration test by provisioning 1000 groups

**Comment by nfx** [comment]
Groups/users/spns are paginated on the SDK level as of v0.13.0 with 100 groups per page, please verify local environment and bump the dependencies.
