### ISSUE TITLE
Avoid getting members with SCIM list calls

### ISSUE THREAD

**Issue by xinjiezhen-db** [databrickslabs/ucx#638]
members as a group attribute can NOT be paginated as part of SCIM core RFCs. Since this is potentially an unbounded request if the members list is ever desired it'd be slightly better to retrieve that as part of a GET call instead of any list calls to reduce the response size as much as possible.

e.g.
https://github.com/databrickslabs/group-flow/blob/7819c08e0d990f223b3bafb641743b64689f96a7/account/databricks.go#L16

better to call list with "attributes=id,displayName" first, and loop through the list to get members.

**Comment by andrascsillag-db** [comment]
thanks for the input @xinjiezhen-db 
Are there other group attributes that are not paginated?
So the most efficient way to get these attributes then from your perspective is to call list without these attributes and then call get in a loop?
cc @william-conti

**Comment by xinjiezhen-db** [comment]
> thanks for the input @xinjiezhen-db Are there other group attributes that are not paginated? So the most efficient way to get these attributes then from your perspective is to call list without these attributes and then call get in a loop? cc @william-conti

No attributes can be paginated per core SCIM RFCs. So it's more about whether a multi value attribute can get too large.

For account SCIM `members` are the biggest problem, `groups` can cause problems too especially for large accounts. Workspace SCIM is a different beast and there are `entitlements` and `roles` but that's for another day.

And yes, it would be slightly better to iterate through the list and point get Groups with those attributes to reduce response size and server load, especially for large accounts.

**Comment by nfx** [comment]
Done
