### ISSUE TITLE
Group Migration - Entitlements and Instance Profile are not getting migrated/copied to the account group but works for the backup group

### ISSUE THREAD

**Issue by amandeep-db** [databrickslabs/ucx#645]
For the Group Migration steps post the assessment workflow, we did an end to end testing for migrating an existing workspace local group with ACLs assigned for different objects to the account group.

During the validation we have noticed that the **instance profile** and **entitlements** are not getting migrated to the account group but it does migrate successfully to the backup group. 

**Please refer the attached document with the screenshot for this reported issue.**

Also, **attaching the logs** from both the workflows i.e. _Applying permission to backup groups_ and _Applying permission to account groups_

[apply_permissions_to_account_groups.log](https://github.com/databrickslabs/ucx/files/13481997/apply_permissions_to_account_groups.log)
[apply_permissions_to_backup_groups (2).log](https://github.com/databrickslabs/ucx/files/13481999/apply_permissions_to_backup_groups.2.log)
[Entitlements-InstanceProfiles.docx](https://github.com/databrickslabs/ucx/files/13482000/Entitlements-InstanceProfiles.docx)

**Comment by nfx** [comment]
Fixed in https://github.com/databrickslabs/ucx/commit/63b79555ccf47ac8a37a3fbee8762e59bd738134, the entitlements were matched by external ID for some reason
