### ISSUE TITLE
feature: Build UC migration status dashboard

### ISSUE THREAD

**Issue by dmoore247** [databrickslabs/ucx#652]
Display metrics related to the progress of the UC upgrade process.

- number of UC Catalogs / Schemas / Tables / Views
- number of external locations
- number of credentials
- number of account groups
- and so on.

Bonus
Even better if we can provide % metrics (comparing HMS v UC)
and a timeline chart showing growth towards 100%.
Identify Jobs to be completed (tables not migrated, groups, jobs, ...)

**Comment by nfx** [comment]
closed in https://github.com/databrickslabs/ucx/pull/1507
