### ISSUE TITLE
Create clusters based on policy

### ISSUE THREAD

**Issue by mirhendi** [databrickslabs/ucx#656]

**Comment by pohlposition** [comment]
Can you elaborate a bit more.

Which clusters?  The ones created as part of the Assessment Workflows, the ones created as part of the Group Migration Workflows?  All of them?

What is the underlying reason for the request?  Are you blocked from doing something?

**Comment by mirhendi** [comment]
Assigning policy for all the clusters in the workflow. The benefit is to set custom cluster configurations. For example, my customer is on Azure and they are using external metastore, by assigning the cluster policy with proper configs, the UCX works seamlessly. 

I also created a PR to add this feature.
