### ISSUE TITLE
Add CLI command to repair run of the assessment job

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#658]
- take the InstallState, pick the ID from "assessment" workflow
- start the job
- open a browser window for the started run for user to follow interactively

see `databricks labs ucx workflows` command for the starting pointers. 

You'll need Databricks CLI v0.210.2+ and run `databricks labs ucx install .` in the git checkout of the project.

**Comment by prajin-29** [comment]
@nfx Should we repair run the failed job? I guess we can repair run only the failed tasks and for the second time we need to provide repair run id  for running it again.

Should we re trigger the entire job instead of repair running it?
