### ISSUE TITLE
`test_workspace_access_e2e` hits `[TABLE_OR_VIEW_NOT_FOUND]` Raised errors for each of the $inventory database tables

### ISSUE THREAD

**Issue by dmoore247** [databrickslabs/ucx#662]
While running locally integration `test_workspace_access_e2e` it hits `[TABLE_OR_VIEW_NOT_FOUND]` raised exceptions for each of the $inventory database tables. These exceptions are caught and swallowed :(

The test setup should pre-create these $inventory database tables. 
Also, these errors should be logged even if the code continues.

<img width="1310" alt="image" src="https://github.com/databrickslabs/ucx/assets/1122251/f07018d4-2fc3-433e-8f2f-8f35f692692f">

**Comment by nfx** [comment]
Removed the test and split it to more tests that don't involve db
