### ISSUE TITLE
Assessment job/dashboard reports on tables it creates during the assessment process

### ISSUE THREAD

**Issue by psroome** [databrickslabs/ucx#665]
Appears that 13 tables get created in a schema called 'yes during the assessment job.

Currently, UCX will assess the readiness of these tables to upgrade to UC, which doesn't really make sense.

![Screenshot 2023-12-04 at 11 07 05 AM](https://github.com/databrickslabs/ucx/assets/13142670/4a29bd9e-2736-4936-b802-66a280461e65)

**Comment by prajin-29** [comment]
@nfx these tables are getting created in the inventory database. Should we restrict it from showing it in dashboard? Or should we restrict it from loading into inventory_database.tables?

**Comment by nfx** [comment]
@prajin-29 what is faster to implement?

**Comment by prajin-29** [comment]
@nfx I have raised one PR for the same. I have restricted the database from getting loaded into tables and also from grant details view so that it won't get displayed in assessment dashboard. Can you review once if the approach looks fine.
