### ISSUE TITLE
Add `databricks labs ucx migrate-tables` and a related workflow

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#670]
databricks labs ucx migrate-tables to apply table mapping from CSV file with the following columns: src_workspace_name,dst_catalog,src_schema,dst_schema,src_table,dst_table . Consider the following stages:

**Initial assessment**
We scan all tables, generate an inventory, get all perms, etc. 
We provide a mapping file the customer can customize, but seed the UC table name with something like the workspace name or ID as the catalog.
Customer can choose to modify the mapping or not

**Initial migration**
We use the mapping file to sync tables, apply perms, and persist the mapping data in inventory

**Repeated migration** - this is probably a job that runs on schedule and the user should be instructed to configure accordingly
We use the mapping data in inventory to re-sync any tables, but not re-apply permissions as these probably changed.

Fine-grained:
- https://github.com/databrickslabs/ucx/issues/333

Upstream dependencies:
- https://github.com/databrickslabs/ucx/issues/341
- https://github.com/databrickslabs/ucx/issues/94
- https://github.com/databrickslabs/ucx/issues/100
- https://github.com/databrickslabs/ucx/issues/669

Next quarter:
- https://github.com/databrickslabs/ucx/issues/334
- https://github.com/databrickslabs/ucx/issues/332
- https://github.com/databrickslabs/ucx/issues/319
- https://github.com/databrickslabs/ucx/issues/673

**Comment by FastLee** [comment]
1. We have to make sure that the mapping is validated and no conflicts were found prior to migration.
2. Make sure the external locations required for the migration were created and that the user has created table permissions on these external locations.
