### ISSUE TITLE
Add `databricks labs ucx ensure-assessment-run` command

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#674]
`databricks labs ucx ensure-assessment-run --workspace-profiles profile-one,profile-two,profile-three` to check if assessment workflows did run otherwise start them.

Upstream dependencies:
- https://github.com/databrickslabs/ucx/issues/673

Pick up the state from https://github.com/databrickslabs/ucx/blob/main/src/databricks/labs/ucx/install.py#L1041-L1058

**Comment by FastLee** [comment]
It would be advisable to make UCX be restricted to one instance per workspace.
