### ISSUE TITLE
process to migrate the account group permissions dosent seem to work.

### ISSUE THREAD

**Issue by saurabhshukla-db** [databrickslabs/ucx#685]
I see this line in the logs

23:01:43 DEBUG [databricks.labs.ucx.framework.crawlers] {apply_account_group_permissions_1} [spark][execute] ALTER DATABASE hive_metastore.sal***etb OWNER TO `MC*****A`

But then looking at that object and it still has the temp group assigned.
I don’t see any error message in the logs, but at the end it shows

23:04:11 INFO [databricks.labs.ucx.framework.parallel] {MainThread} Finished 'apply account group permissions' tasks: 95% results available (1117/1179). Took 0:02:27.435875

So seemingly 62 permissions were never done?

**Comment by nfx** [comment]
@saurabhshukla-db there's caching happening on backend. please check again in 30 minutes.
