### ISSUE TITLE
Need List of Dependency Host Names / Regulated Customer Does Not Want to Allow Access to PyPi.org

### ISSUE THREAD

**Issue by rhoubergdb** [databrickslabs/ucx#698]
A regulated customer (investment bank) blocks all web traffic by default and only allows only whitelisted websites. As an SA, I need a list of all dependency source web sites that are needed during UCX install as well as during UCX installation.

The dependency we are currently seeing is PyPi.org (we don't yet know if there are more because the install script halts there). The security team at the bank does not allow access to PyPi.org as it is a known source of malicious code. (https://blog.sonatype.com/top-8-malicious-attacks-recently-found-on-pypi) The bank requires their own devs to use JFrog Artifactory as a safer alternative.

A general description of what the install script is doing would be helpful.

**Comment by rhoubergdb** [comment]
We added PyPi.org to the firewall exceptions. It moved us a bit further (no Pypi.org install blockers). But today's run still had challenges. It seems like something going on with SSL termination (potentially environmental), but I'm not getting enough information in the output to diagnose what is happening when we are getting the errors. So I'm not seeing anything to troubleshoot/request from an environmental standpoint.

Please see attached output from the install.sh execution for more info.

[20231214 - UCX Install.sh result.pdf](https://github.com/databrickslabs/ucx/files/13678561/20231214.-.UCX.Install.sh.result.pdf)

**Comment by nfx** [comment]
@rhoubergdb `install.sh` is no longer supported. we support installations only through Databricks CLI - `databricks labs install ucx`
