### ISSUE TITLE
Add parallel fetching for registered model ID

### ISSUE THREAD

**Issue by arnavjeurkar** [databrickslabs/ucx#701]
At the moment, we're fetching registered model IDs sequentially in the MainThread:

- crawl_permissions.log.2023-12-06_02-40:02:47:20 DEBUG [databricks.sdk] {MainThread} GET /api/2.0/mlflow/registered-models/list?page_token=...
- crawl_permissions.log.2023-12-06_02-40:02:47:20 DEBUG [databricks.sdk] {MainThread} GET /api/2.0/mlflow/databricks/registered-models/get?name=...
- crawl_permissions.log.2023-12-06_02-40:02:47:20 DEBUG [databricks.sdk] {MainThread} GET /api/2.0/mlflow/databricks/registered-models/get?name=....

this results in overly long runtimes for assessment tasks, that go beyond 18 hours. I strongly believe this can be parallelised. Add Threads.parallel call to speed this up.

**This issue is still prevalent after [previous fix which was merged](https://github.com/databrickslabs/ucx/issues/688)**

**Comment by HariGS-DB** [comment]
@arnavjeurkar could you share the full crawl permission log file?

**Comment by nfx** [comment]
@arnavjeurkar the fix is not released yet. And the logs still show the MainThread, which means that you're running the old code
