### ISSUE TITLE
Entitlements are not migrated to the account groups

### ISSUE THREAD

**Issue by william-conti** [databrickslabs/ucx#703]
This bug was fixed but it is now re-introduced in the latest UCX version:

```
17:12:20 DEBUG [databricks.sdk] {apply_account_group_permissions_4} PATCH /api/2.0/preview/scim/v2/Groups/None
> {
>   "Operations": [
>     {
>       "op": "add",
>       "path": "entitlements",
>       "value": "**REDACTED**"
>     }
>   ],
>   "schemas": [
>     "urn:ietf:params:scim:api:messages:2.0:PatchOp"
>   ]
> }
< 404 Not Found
< {
<   "detail": "Group with id None not found.",
<   "schemas": [
<     "urn:ietf:params:scim:api:messages:2.0:Error"
<   ],
<   "status": "404"
< }
```

**Comment by pohlposition** [comment]
This one seems to be a major bug.  Would block anyone who is performing group migration.  We should not cut another release before fixing this one.

**Comment by nfx** [comment]
fixed in https://github.com/databrickslabs/ucx/commit/63b79555ccf47ac8a37a3fbee8762e59bd738134#diff-847a130cc783562e62235ab42ce9f198caa96600e268de69f67a36aed010d39bL23-R61
