### ISSUE TITLE
Display error messages in a single place

### ISSUE THREAD

**Issue by william-conti** [databrickslabs/ucx#706]
If there are any errors at the end of a Task, we must crawl through all the log files to find the errors that has been raised, which is very cumbersome when the task took 8hours and there are 30+ files to analyze one by one.

Ideally we should render all exceptions encountered in the Workflow UI for easier debugging

<img width="1212" alt="Capture d’écran 2023-12-19 à 19 43 13" src="https://github.com/databrickslabs/ucx/assets/107417584/02abb64f-dee2-4697-93a5-fb86f613c921">

**Comment by nfx** [comment]
@william-conti the simplest way is throwing the `ManyError` and failing the task/job - though it has some usability issues. perhaps it's an easy fix
