### ISSUE TITLE
guess_external_location assessment step fails

### ISSUE THREAD

**Issue by FastLee** [databrickslabs/ucx#731]
TypeError: ExternalLocation.__init__() missing 1 required positional argument: 'table_count'
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File ~/.ipykernel/2459/command--1-2530018372:18
     15 entry = [ep for ep in metadata.distribution("databricks_labs_ucx").entry_points if ep.name == "runtime"]
     16 if entry:
     17   # Load and execute the entrypoint, assumes no parameters
---> 18   entry[0].load()()
     19 else:
     20   import databricks_labs_ucx

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/runtime.py:346, in main(*argv)
    344 if len(argv) == 0:
    345     argv = sys.argv
--> 346 trigger(*argv)

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/tasks.py:179, in trigger(*argv)
    176         f.write(f"[run #{workflow_run_id}](/#job/{job_id}/run/{workflow_run_id})\n")
    178 try:
--> 179     current_task.fn(cfg)
    180 except BaseException as error:
    181     log_file_for_cli = str(log_file).lstrip("/Workspace")

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/runtime.py:83, in guess_external_locations(cfg)
     81 ws = WorkspaceClient(config=cfg.to_databricks_config())
     82 crawler = ExternalLocations(ws, RuntimeBackend(), cfg.inventory_database)
---> 83 crawler.snapshot()

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/hive_metastore/locations.py:121, in ExternalLocations.snapshot(self)
    120 def snapshot(self) -> Iterable[ExternalLocation]:
--> 121     return self._snapshot(self._try_fetch, self._external_location_list)

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/crawlers.py:254, in CrawlerBase._snapshot(self, fetcher, loader)
    252 logger.debug(f"[{self._full_name}] fetching {self._table} inventory")
    253 try:
--> 254     cached_results = list(fetcher())
    255     if len(cached_results) > 0:
    256         return cached_results

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/hive_metastore/locations.py:125, in ExternalLocations._try_fetch(self)
    123 def _try_fetch(self) -> Iterable[ExternalLocation]:
    124     for row in self._fetch(f"SELECT * FROM {self._schema}.{self._table}"):
--> 125         yield ExternalLocation(*row)

TypeError: ExternalLocation.__init__() missing 1 required positional argument: 'table_count'

**Comment by HariGS-DB** [comment]
@FastLee This was a change introduced. You would need to run install again to set up the new table schema for external location
