### ISSUE TITLE
Improve Table ACL Process

### ISSUE THREAD

**Issue by HariGS-DB** [databrickslabs/ucx#736]
Currently crawl_grants step scans all the tables for permission of the given group list. If the migration list groups or its member doesnt have 
 - usage permission on the hive_metastore 
 - and usage or owner permission on the schema
 - and is not a workspace admin, 
 
Then there is no need to check table/view permission and it can be skipped for that database which should speed up execution time. In large workspace where teams are segregated by groups and schema created for specific teams, this can largely improve the crawl_grants process

https://docs.databricks.com/en/data-governance/table-acls/object-privileges.html#usage-privilege

**Comment by nfx** [comment]
Why do we need it? Crawling grants creates a backup of the entire hms permissions

**Comment by HariGS-DB** [comment]
Yes grants create the entire permission, but often only few groups are migrated at a time, so the next time groups are migrated, there is no guarantee grants are upto date (if some permissions were changed ), and you end up doing full grants scan anyway. its more usefull where we have large HMS and large groups and migration is done in chunks of groups

**Comment by nfx** [comment]
I still don't get it.

1. Assessment -> snapshot of current permissions 
2. Migrate groups -> reapply permissions for current batch of groups

What do we need more?...

---------

We just need to document the process

**Comment by nfx** [comment]
> Currently crawl_grants step scans all the tables for permission of the given group list

This is incorrect. We crawl all grants
