### ISSUE TITLE
[FEATURE] Aggregation of UCX output of multiple workspaces as CLI command

### ISSUE THREAD

**Issue by DB-Zoe** [databrickslabs/ucx#749]
Some customers have 30+ workspaces and leadership want an overall view of their readiness and current state rather than having 30 separate dashboards.
It would be great to have a way to:
1. aggregate the data
2. Report on the aggregated view

Required to be done in the CLI. It has to work with workspaces that don't have UC enabled yet.

- [ ] Make sure `assessment` was run on every workspace
- [x] Query every workspace and database
- [x] Aggregate all `failures` from `$inventory.objects` view
- [x] Provide TopN failures
- [x] Provide % readiness

Creating a dashboard is out of scope

**Comment by nfx** [comment]
@DB-Zoe would a command-line interface be fine for this? it's the easiest option, as we don't really have a notion of a "master workspace"

**Comment by DB-Zoe** [comment]
We have the options of Tech services or PS on most accounts using UCX so they would be able to support customers with command-line so I think that would be fine!

**Comment by nfx** [comment]
Thank you for the feature request! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.

**Comment by nfx** [comment]
@DB-Zoe what would you like to see in this aggregated report? please be very specific

**Comment by DB-Zoe** [comment]
For a customer we made a table that had the following columns (pulled from the individual dashboards) and this helped us to ascertain which environments to prioritise and report to leadership the current state of the platform:
Workspace name, environment (extracted so no need to add), Number of mounts, number of incompatible clusters, percentage of data that was parquet format, UC enabled flag (conscious that again isn't from UCX), and then the percentage of clusters, jobs, tables and pipelines that were compatible with UC. 
We then used this to show overall compatibility, list the top five workspaces that are most ready and least ready for UC.
