### ISSUE TITLE
UCX Migrate Groups Job Failing

### ISSUE THREAD

**Issue by chelsea-jones-usps** [databrickslabs/ucx#757]
We are attempting to migrate groups via the UCX Migrate groups Job. The third task of this job fails with the following error: ManyError: Detected 332 failures: Timed out after 0:01:00. 
I attached out zipped logs to show the error. 

[stderr--2024-01-04--22-00.zip](https://github.com/databrickslabs/ucx/files/13844078/stderr--2024-01-04--22-00.zip)

**Comment by nfx** [comment]
@chelsea-jones-usps what version are you running?

**Comment by nfx** [comment]
@chelsea-jones-usps uninstall (`databricks labs uninstall ucx`) and install it again from `main` branch - `databricks labs install ucx`. It's fixed in https://github.com/databrickslabs/ucx/commit/260bef3866f1aa17bf4499ca84d8258a040322ea and going to be part of the next release.
