### ISSUE TITLE
User and backup group permissions lost for redash objects after applying group permissions

### ISSUE THREAD

**Issue by mwojtyczka** [databrickslabs/ucx#767]
We apply group permissions for redash objects using POST (there is no PATCH operation available). That means we are replacing all the permissions. Currently, we only collect and apply the permissions for the account groups. Existing permissions for users, backup groups, and other workspace-local groups that don't have corresponding account groups are lost.

**Comment by nfx** [comment]
@mwojtyczka redash has no PUT

 we collect all permissions, aa far as I remember. We just apply the group permissions 


Thank you for the feature request! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.

**Comment by mwojtyczka** [comment]
Yes, we collect all groups but we don't collect users. Making PR for this.
