### ISSUE TITLE
Cannot upgrade or uninstall ucx v0.4

### ISSUE THREAD

**Issue by skantzidis** [databrickslabs/ucx#768]
Error when I attempt to upgrade:

venv310) xxxxxxxxxx@XXXXXXXXXXXXX ucx % databricks labs upgrade ucx  
⣷ Downloading and unpacking zipball for v0.8.0Error: record version: open /Users/xxxxxxxxxx/.databricks/labs/ucx/state/version.json: no such file or directory

Error when I attempt to uninstall:
(venv310) xxxxxxxxxx@XXXXXXXXXXXXX ucx % databricks labs uninstall ucx
20:51:26  INFO [d.l.ucx.install] Deleting UCX v0.8.1+None20240109205126 from https://xxxxxxxxxxxxxx.cloud.databricks.com
20:51:27 ERROR [d.l.ucx.install] Check if /Users/xxxxxxxxxxx/.ucx is present along with /Users/xxxxxxxxxxx/.ucx/config.yml and /Users/xxxxxxxxxxx/.ucx/state.json.

For uninstall attempt the state.json file is missing.

Would appreciate any tips on how to upgrade from 0.4.0 to 0.8.0. Can i manually created missing files or do I need to uninstall manually?

Edit: We have only executed to the assessment workflow to date.

**Comment by nfx** [comment]
@skantzidis v0.4.0 is too old. Remove manually:

- Jobs linked in readme notebook
- dashboards
- .ucx in your home directory
- database created by ucx

And do a fresh install using the CLI
