### ISSUE TITLE
Cannot install ucx ".databrickscfg does not contain account profiles"

### ISSUE THREAD

**Issue by skantzidis** [databrickslabs/ucx#771]
The databricks CLI is installed correctly (Databricks CLI v0.211.0), as I have confirmed that I can run other databricks CLI commands (e.g. databricks clusters list etc etc).

However when I execute this:
(venv310) xxxx@xxxx ucx % databricks labs install ucx
Error: login: ask for account: /Users/xxxx/.databrickscfg does not contain account profiles; please create one first

Or this:

(venv310) xxxx@xxxx ucx % databricks -p DEFAULT labs install ucx 
Error: login: ask for account: /Users/xxxx/.databrickscfg does not contain account profiles; please create one first

the profile does not seem to be recognized.

**Comment by nfx** [comment]
please create an account profile, where you add the account id relevant to your workspace - this will fix it. I'll modify CLI later to be more flexible when account profile is not found.

```
[account-profile]
host       = https://accounts.azuredatabricks.net/
account_id = 000...-
````

**Comment by nfx** [comment]
Fixed in https://github.com/databricks/cli/pull/1128

**Comment by nfx** [comment]
fixed in https://github.com/databricks/cli/commit/deb7e67ad5018bd661d342c1e920fd5b9e084e8c, should be in CLI v0.212.2 or v0.213.0
