### ISSUE TITLE
Debug notebook link won't open with the right location

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#783]
when clicking on `debug notebook` here:
<img width="459" alt="image" src="https://github.com/databrickslabs/ucx/assets/259697/b1b9a516-5dea-4c0f-8361-0b2c747df0d1">
browser can't render the `https://ws.../#workspace/Users/user@domain.com/.ucx/DEBUG.py`

**Comment by larsgeorge-db** [comment]
I just tried this @nfx with the latest `main` version and it works for me, i.e. the link opens the debug notebook. Could you clarify if you are referring to subtlety here I am not seeing?

**Comment by mwojtyczka** [comment]
Same for me, it opens the debug notebook when installing the tool from main.
