### ISSUE TITLE
Cannot repair failed assessment job with `databricks labs ucx repair-run`

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#787]
Repair run is broken, as it cannot repair a failed workflow:
```
$ databricks labs ucx repair-run --step assessment
12:14:25  INFO [databricks.sdk] Using Databricks CLI authentication
12:14:25  INFO [d.labs.ucx] Repair Running assessment Job
12:14:27 ERROR [d.l.ucx.repair-run] AttributeError: 'NoneType' object has no attribute 'value'
```

**Comment by prajin-29** [comment]
@nfx .This will occur only when the result_state of a job run is None. Normally in any Job this status won't be NoneType. This scenario only happens if we are trying to run the repair run immediately before the status get updated to either SUCCESS or FAILURE.

**Comment by nfx** [comment]
@prajin-29 this is a regression, fix it asap.
