### ISSUE TITLE
Misleading dashboard fact: `Assessment Summary - Non-DELTA format: DELTA`

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#788]
The assessment summary widget shows incorrect results: `DELTA` is reported as non-delta

<img width="598" alt="image" src="https://github.com/databrickslabs/ucx/assets/259697/ada1dcb3-62a3-4da0-92d4-f7dad9f0d45b">

**Comment by larsgeorge-db** [comment]
This is fixed with the PR #802 - the comparison was wrong, it checked lowercase while the Scala script now saves the object type and table format values in uppercase.
