### ISSUE TITLE
[FEATURE]: Assessment - Handle mismatch of Hive Metastore and File Storage

### ISSUE THREAD

**Issue by ronguerrero** [databrickslabs/ucx#813]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

The assessment tool errors out when it detects table metadata but the table data no longer exists in cloud storage.  

### Proposed Solution

This can happen when customers delete the table data directly without DROP TABLE.

Ideally these tables will be recorded in the assessment, and hence the customer can manually clean these up.

**Comment by nfx** [comment]
This is fixed on current main branch already. Will be fixed in v0.10.0
