### ISSUE TITLE
[BUG]: Only one issue per cluster was identified during assessment (v0.8.0)

### ISSUE THREAD

**Issue by vtcloud9** [databrickslabs/ucx#818]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

v0.8.0 UCX is stopping scanning further once it identifies an issue on the cluster. 

### Expected Behavior

UCX needs to scan for all the issues in all the clusters belonging to a given workspace and provide a comprehensive list of findings.

### Steps To Reproduce

Install v0.8.0 UCX and run the main assessment job.

### Cloud

Azure

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by dmoore247** [comment]
Only  spark config issue was identified but the interactive clusters had down level DBRs (11.0, 13.0,...). The downlevel dbr issues were not identified in the assessment.

**Comment by dmoore247** [comment]
@FastLee We saw the assessment call out a spark config associated with external metastore. However the DBR Runtime (11, 13.0) of the interactive cluster was not called out in the cluster assessment report.

**Comment by dmoore247** [comment]
@vtcloud9 Per @FastLee DBR 11.x and and down level 13.0 clusters are not considered unsupported for UC. The recommendation of using latest LTS DBR (13.3 LTS) still stands though, just not mandatory.

**Comment by vtcloud9** [comment]
@dmoore247 @FastLee  Thanks for the clarification that DBR 11.x  is a supported version for UC. 

Does it mean UCX scanned for all the issues and it found only issue as it reported?
