### ISSUE TITLE
[FEATURE]: Table counts by storage

### ISSUE THREAD

**Issue by kpkab** [databrickslabs/ucx#828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

Right now the UCX script gives the total number of tables (Total Tables) at the top is great, but a breakdown based on the storage would be helpful:
Total Table count = 1000 (350+150+500)
DBFS Root Table = 350
DBFS Mount = 150
Cloud Storage = 500

Nice to have:
1. Total number Delta tables (per schema)
2. Total number of non-delta tables (per schema)

### Proposed Solution

Along with the total table count - we should have a section where we can see the count of tables based on the storage.

Total Table count = 1000 (350+150+500)
DBFS Root Table = 350
DBFS Mount = 150
Cloud Storage = 500

Nice to have:
1. Total number Delta tables (per schema)
2. Total number of non-delta tables (per schema)

**Comment by nfx** [comment]
Thank you for the feature request! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.
