### ISSUE TITLE
[FEATURE]: View counts

### ISSUE THREAD

**Issue by kpkab** [databrickslabs/ucx#829]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

Along with table count at the top, can we get the total View counts. Now we get the total views from the database summary, but if can see the total number of views at the top. We use the the view counts for estimating the effort involved to move them to UC.

### Proposed Solution

Add a section at the top of the summary dashboard to have the total number of views. If possible (nice to have), view counts per schema.

**Comment by nfx** [comment]
Views are the easiest to auto-migrate, I don't know if we should occupy the dashboard space with this count
