### ISSUE TITLE
[FEATURE]: Count of cluster policy

### ISSUE THREAD

**Issue by kpkab** [databrickslabs/ucx#830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

We need to know the number of cluster policies per workspace, along with the DBR versions. This will help us estimate how many number of cluster policies needs to be updated as part of the migration.

### Proposed Solution

Add a separate section with the list of cluster policies along with their DBR version. this will help us understand the total number of policies available and the number of ones that needs to be updated as part of the migration.

**Comment by nfx** [comment]
How many policies are we talking about? 10? 50? 100?

**Comment by kpkab** [comment]
number of policies depends on the size of the customer. I've seen less than 5 and sometimes more than 15 (never in 50's or 100's).

**Comment by prajin-29** [comment]
@nfx . Should we have a separate column in clusters table to have list of policies. Or can we add CLI command to get the list?
