### ISSUE TITLE
[BUG]: Installation Failure without any actionable message

### ISSUE THREAD

**Issue by Sanket-Mehta** [databrickslabs/ucx#835]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi Team,

I'm running into issues while trying to install v0.10.0 in a workspace where I have admin privileges. Below is the error trace I encountered in 2 different workspaces hosted on Azure.

> 14:26:29 ERROR [d.l.blueprint.parallel][installing_components_2] installing components task failed: [UNRESOLVED_COLUMN.WITH_SUGGESTION] A column, variable, or function parameter with name `udf` cannot be resolved. Did you mean one of the following? [`view`, `table`, `any_file`, `catalog`, `database`].; line 9 pos 13: Traceback (most recent call last):
>   File "C:\Users\SANKET~1\AppData\Local\Temp\tmp.YKAdIkOAkJ\Lib\site-packages\databricks\labs\blueprint\parallel.py", line 134, in inner
>     return func(*args, **kwargs), None
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\SanketMehta\Documents\UC Assessment Tool\ucx-0.10.0\ucx-0.10.0\src\databricks\labs\ucx\install.py", line 220, in _create_database
>     deploy_schema(self._sql_backend, self.current_config.inventory_database)
>   File "C:\Users\SanketMehta\Documents\UC Assessment Tool\ucx-0.10.0\ucx-0.10.0\src\databricks\labs\ucx\install.py", line 163, in deploy_schema
>     deployer.deploy_view("grant_detail", "queries/views/grant_detail.sql")
>   File "C:\Users\SanketMehta\Documents\UC Assessment Tool\ucx-0.10.0\ucx-0.10.0\src\databricks\labs\ucx\framework\crawlers.py", line 325, in deploy_view
>     self._sql_backend.execute(ddl)
>   File "C:\Users\SanketMehta\Documents\UC Assessment Tool\ucx-0.10.0\ucx-0.10.0\src\databricks\labs\ucx\framework\crawlers.py", line 103, in execute
>     self._sql.execute(self._warehouse_id, sql)
>   File "C:\Users\SanketMehta\Documents\UC Assessment Tool\ucx-0.10.0\ucx-0.10.0\src\databricks\labs\ucx\mixins\sql.py", line 173, in execute
>     self._raise_if_needed(status)
>   File "C:\Users\SanketMehta\Documents\UC Assessment Tool\ucx-0.10.0\ucx-0.10.0\src\databricks\labs\ucx\mixins\sql.py", line 133, in _raise_if_needed
>     raise error_class(error_message)
> databricks.sdk.errors.mapping.BadRequest: [UNRESOLVED_COLUMN.WITH_SUGGESTION] A column, variable, or function parameter with name `udf` cannot be resolved. Did you mean one of the following? [`view`, `table`, `any_file`, `catalog`, `database`].; line 9 pos 13

I couldn't find any existing issue for this as well.

Could you help understand more on this.

Thanks!
![image](https://github.com/databrickslabs/ucx/assets/145981453/f17aff8e-0e7e-4897-8ebb-0d5981b49d88)

### Expected Behavior

Installation failure should direct the user to exact step where there's issue. Instead it seems there's an exception being thrown which isn't handled! 

### Cloud

Azure

### Operating System

Windows

### Version

via install.sh

### Relevant log output

```shell
14:26:29 ERROR [d.l.blueprint.parallel][installing_components_2] installing components task failed: [UNRESOLVED_COLUMN.WITH_SUGGESTION] A column, variable, or function parameter with name `udf` cannot be resolved. Did you mean one of the following? [`view`, `table`, `any_file`, `catalog`, `database`].; line 9 pos 13: Traceback (most recent call last):
  File "C:\Users\SANKET~1\AppData\Local\Temp\tmp.YKAdIkOAkJ\Lib\site-packages\databricks\labs\blueprint\parallel.py", line 134, in inner
    return func(*args, **kwargs), None
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SanketMehta\Documents\UC Assessment Tool\ucx-0.10.0\ucx-0.10.0\src\databricks\labs\ucx\install.py", line 220, in _create_database
    deploy_schema(self._sql_backend, self.current_config.inventory_database)
  File "C:\Users\SanketMehta\Documents\UC Assessment Tool\ucx-0.10.0\ucx-0.10.0\src\databricks\labs\ucx\install.py", line 163, in deploy_schema
    deployer.deploy_view("grant_detail", "queries/views/grant_detail.sql")
  File "C:\Users\SanketMehta\Documents\UC Assessment Tool\ucx-0.10.0\ucx-0.10.0\src\databricks\labs\ucx\framework\crawlers.py", line 325, in deploy_view
    self._sql_backend.execute(ddl)
  File "C:\Users\SanketMehta\Documents\UC Assessment Tool\ucx-0.10.0\ucx-0.10.0\src\databricks\labs\ucx\framework\crawlers.py", line 103, in execute
    self._sql.execute(self._warehouse_id, sql)
  File "C:\Users\SanketMehta\Documents\UC Assessment Tool\ucx-0.10.0\ucx-0.10.0\src\databricks\labs\ucx\mixins\sql.py", line 173, in execute
    self._raise_if_needed(status)
  File "C:\Users\SanketMehta\Documents\UC Assessment Tool\ucx-0.10.0\ucx-0.10.0\src\databricks\labs\ucx\mixins\sql.py", line 133, in _raise_if_needed
    raise error_class(error_message)
databricks.sdk.errors.mapping.BadRequest: [UNRESOLVED_COLUMN.WITH_SUGGESTION] A column, variable, or function parameter with name `udf` cannot be resolved. Did you mean one of the following? [`view`, `table`, `any_file`, `catalog`, `database`].; line 9 pos 13
```

**Comment by nfx** [comment]
this should fix the issue:

databricks labs uninstall ucx
databricks labs install ucx

**Comment by Sanket-Mehta** [comment]
Thanks @nfx! 

What happens when someone doesn't have Databricks Labs installed already in this case? 
e.g., I'm running into issues while installing databricks labs, however I'd still want to overcome the issue of existing ucx version conflicting with new version.

Thanks for the help here!
