### ISSUE TITLE
[BUG]: Contrib contains incorrect commands

### ISSUE THREAD

**Issue by renardeinside** [databrickslabs/ucx#850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The contrib documentation contains commands that are based on `unit` environments, e.g.:

> $ hatch run unit:test-cov-report

These commands are outdated and shall be removed from the doc to avoid confusion.

### Expected Behavior

Irrelevant commands removed.

### Steps To Reproduce

Check the contrib docs.

### Cloud

AWS

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by nfx** [comment]
Thank you for the feature request! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.
