### ISSUE TITLE
Add ability to also write log output to a configured file

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#86]
Currently logs are printed to stdout only and it's truncated in the notebook cell. We need a second logging destination for troubleshooting

This problem persists in python wheel tasks as well:

<img width="487" alt="image" src="https://github.com/databricks/ucx/assets/259697/fc038836-bdbc-4224-be07-bce8ddde28e9">

use `{{job_id}}` and `{{run_id}}` and `{{task_key}}` as injected parameters to distinguish the logs.

https://docs.databricks.com/en/workflows/jobs/task-parameter-variables.html

use `try ... finally ...` to ensure the log file is flushed

https://docs.python.org/3/library/logging.handlers.html#filehandler

**Comment by FastLee** [comment]
I would assume that our .ucx folder is a good destination for logging.
