### ISSUE TITLE
[FEATURE]: Add "is_partitioned" field to HMS tables crawler output

### ISSUE THREAD

**Issue by randall-gonzalez-dbx** [databrickslabs/ucx#871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

Special consideration needs to be taken when migrating HMS partitioned tables to UC external table. Currently there is no way to distinguish between HMS partitioned and non-partitioned, based on the output of the assessment.

### Proposed Solution

I see two files tables.py and tables.scala, not sure if both need to be modified or just the scala version.
For the Python version, DESCRIBE EXTENDED outputs partition information if applicable, and could be used to derive is_partitioned.
For the Scala version, the attached piece of code seems to do the trick. I decided not to submit a PR because I am weak in Scala and also this involves a separate function call (getTableMetadata - see the attached notebook) . The notebook also includes two other alternative approaches that did not work.
[test_partitioned.txt](https://github.com/databrickslabs/ucx/files/14131431/test_partitioned.txt)

**Comment by nfx** [comment]
Thank you for the feature request! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.
