### ISSUE TITLE
[FEATURE]: Crawler Rescan Capability

### ISSUE THREAD

**Issue by FastLee** [databrickslabs/ucx#882]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

To rerun a crawler based assessment test a user would have to delete the table and rerun the assessment step.

Related issues:
- https://github.com/databrickslabs/ucx/issues/380
- https://github.com/databrickslabs/ucx/issues/844

### Proposed Solution

Allow user to rerun an assessment step to rescan the source and re populate the assessment table.

**Comment by nfx** [comment]
Closing in favor of https://github.com/databrickslabs/ucx/issues/2074
