### ISSUE TITLE
[FEATURE]: Function Assessment

### ISSUE THREAD

**Issue by FastLee** [databrickslabs/ucx#884]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

Users can create functions in HMS that then can be used as UDFs and in views.
Some of these functions cannot be migrated to UC.

### Proposed Solution

List all the functions and highlight the ones that cannot be migrated to UC or have other restrictions (can run on single user clusters only)

**Comment by nfx** [comment]
@FastLee please explain what needs to be done here like i'm 5-year old
