### ISSUE TITLE
[FEATURE]: Create access connector with managed identity

### ISSUE THREAD

**Issue by HariGS-DB** [databrickslabs/ucx#888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

 - Create access connector with managed identity, one for each storage account
 - ~assign appropriate permission to the identified storage accounts that are to be migrated.~ -> see #1383
 - ~replace existing storage credential with equivalent access connector-managed identity~ -> see #1384

Related issues:
- https://github.com/databrickslabs/ucx/issues/875
- https://github.com/databrickslabs/ucx/issues/339

### Proposed Solution

to be defined

**Comment by JCZuurmond** [comment]
Move "assigning appropiate permissions" into #1383

**Comment by JCZuurmond** [comment]
Moved "replacing storage credentials" into #1384
