### ISSUE TITLE
[FEATURE]: Single UCX Installation per workspace

### ISSUE THREAD

**Issue by FastLee** [databrickslabs/ucx#890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

Each user's UCX installation creates a separate folder. Some tasks, requires the involvement of more than one user which will create a potential issue.

### Proposed Solution

Default installation to the <root folder>/applications/ucx allow the user to override the default and install to the user's folder.

**Comment by nfx** [comment]
duplicate of https://github.com/databrickslabs/ucx/issues/803
