### ISSUE TITLE
[FEATURE]: Create Deterministic Assessment Codes

### ISSUE THREAD

**Issue by FastLee** [databrickslabs/ucx#895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

Currently assessment generates text based issue. We cannot use these to key dependent tasks.

Related issues: 
- https://github.com/databrickslabs/ucx/issues/846
- https://github.com/databrickslabs/ucx/issues/844
- https://github.com/databrickslabs/ucx/issues/810
- https://github.com/databrickslabs/ucx/issues/765
- https://github.com/databrickslabs/ucx/issues/498
- https://github.com/databrickslabs/ucx/issues/445
- https://github.com/databrickslabs/ucx/issues/415
- https://github.com/databrickslabs/ucx/issues/415
- https://github.com/databrickslabs/ucx/issues/342

| Format | Domain |
| --- | --- |
| `Axx` | azure service principals |
| `Cxx` | clusters |
| `Jxx` | jobs |
| `Lxx` | live tables |
| `Pxx` | policies |
| `Nxx` | notebooks |
| `Wxx` | warehouses |
| `Txx` | tables |
| `Sxx` | schemas |

### Proposed Solution

Create a single source of Assessment Codes and use these in assessment.
We would use a format of: `UXXX: <Finding Explanation>`. For Example:
`U001: Unsupported DBR: 10.1`

### Additional Context

See ruff's error codes: https://docs.astral.sh/ruff/rules/#warning-w

**Comment by dmoore247** [comment]
Covered in part by #1123 and #810 and #806 
Enhance assessment.md and `interactive` report according to specs above.

**Comment by ericvergnaud** [comment]
We now have an Advice code that's deterministic. Should we close this ?

**Comment by nfx** [comment]
yes, let's close this. Made some progress in https://github.com/databrickslabs/ucx/pull/2194
