### ISSUE TITLE
[FEATURE]:  Add cli command `databricks labs ucx migrate-tables --what dbfs_root_delta` to migrate DBFS Root Delta Table

### ISSUE THREAD

**Issue by FastLee** [databrickslabs/ucx#901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

User requires a way to trigger the UC CLI process.

### Proposed Solution

Create a CLI command to kick off the DBFS Root Delta Tables.

**Comment by nfx** [comment]
Duplicate of #670
