### ISSUE TITLE
[FEATURE]: Trigger DBFS Root Table Migration As a Job

### ISSUE THREAD

**Issue by FastLee** [databrickslabs/ucx#904]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

Running the table migration may take long time and can be interrupted by local events (Laptop gets shut down)

### Proposed Solution

Create a job to run table migration and report progress.

**Comment by nfx** [comment]
@FastLee How should we report progress?

**Comment by nfx** [comment]
Done in

https://github.com/databrickslabs/ucx/commit/e97d2ef5e94f633485038263b8c9e471bd078922#diff-bf31a0d3769d994ca8c56c723f2b9f2fa2418b61f705bd979760af2e6e540ecbR441-R454

**Comment by nfx** [comment]
Done in

https://github.com/databrickslabs/ucx/blob/e97d2ef5e94f633485038263b8c9e471bd078922/src/databricks/labs/ucx/runtime.py#L441-L455
