### ISSUE TITLE
[FEATURE]: DBFS Root Tables Migration Validation

### ISSUE THREAD

**Issue by FastLee** [databrickslabs/ucx#906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

When the migration of DBFS root tables is complete we need a way to validate the tables were migrated successfully. 

### Proposed Solution

Run a validation to make sure that the tables were created and are populated with data.

### Additional Context

Related issues:
- https://github.com/databrickslabs/ucx/issues/927

**Comment by nfx** [comment]
@FastLee please expand what needs to be done here

**Comment by nfx** [comment]
Duplicate of #927 

the issue by Chase is more well-written compared to this one.
