### ISSUE TITLE
[FEATURE]: Create/Amend mapping between storage prefixes and cloud principals

### ISSUE THREAD

**Issue by FastLee** [databrickslabs/ucx#910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

In the process of creating storage credentials we have to map storage credentials to intended cloud principals so we can create these principals.

### Proposed Solution

The mapping will detect the existing storage credentials and will surface the missing principal/roles that needs to be created for the missing storage credntials.
We should allow the user to select between few options of mapping:

1. Create a single principal/role for all prefixes
2. Create a principal/role based on the existing principals/roles
3. Create a principal/role for each prefix.

The principal can be an AWS Role an Azure SPN or an Azure MI

The process will generate a mapping CSV and upload it to the workspace.

The mapping document will have the following format:
| Principal | Prefix |
|--------|-------|
|  {"role_id":"arn:aws:iam::1234567890:role/DBAdmin"} | s3://container-name/ |
| {"connector_id":"/subscriptions/1234567890/resourceGroups/ucx/providers/Microsoft.Databricks/accessConnectors/ucx-mi"} | abfss://ucx@ucx.dfs.core.windows.net/folder_a |
| {"subscription_id":"1234", "directory_id":"5678"}| abfss://ucx@ucx.dfs.core.windows.net/folder_b |

### Checklist

- [ ] do we have the CSV file? 
- [ ] is it the same name for Azure and AWS? 
- [ ] Is the name of it visible in docs? 
- [ ] is there a command to open that file easily?

**Comment by nfx** [comment]
would it make sense for you to document this entire flow?

<img width="730" alt="image" src="https://github.com/databrickslabs/ucx/assets/259697/2a82bbe4-db2c-4c79-9f2e-d88c3490f0d3">

**Comment by nfx** [comment]
@FastLee when it's going to be implemented?

**Comment by nfx** [comment]
@FastLee this is high-prio :)

**Comment by nfx** [comment]
Closed by #1495
