### ISSUE TITLE
[FEATURE]: Create Cloud Principal [Azure]

### ISSUE THREAD

**Issue by FastLee** [databrickslabs/ucx#914]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

Creating MI/SPN is required for creating external locations.

### Proposed Solution

Create a Terraform script/CLI command to create the MI or SPN. Triggered by:
- https://github.com/databrickslabs/ucx/issues/912

**Comment by nfx** [comment]
Fixed in https://github.com/databrickslabs/ucx/pull/874
