### ISSUE TITLE
[FEATURE]: Multiple workspaces may refer to the same prefix with different principals. We need to dedupe upgrades.

### ISSUE THREAD

**Issue by nkvuong** [databrickslabs/ucx#917]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

Need to handle duplication of credentials & prefixes across different workspaces
- Prefixes that show up on more than one workspace. 
- Prefixes that show up on more than one workspace with different credentials

### Proposed Solution

1. Addressing prefix conflicts/duplications require special processing we have the following options
- Prefixes that show up on more than one workspace. 
  - If already upgraded, ignore
  - If not, warn, and will upgrade later
- Prefixes that show up on more than one workspace with different credentials
  - Prompt, confirm choice of credentials

### Additional Context

Requires:
#910

**Comment by JCZuurmond** [comment]
If I understand it correctly, this is not relevant when using storage credentials. @nkvuong or @FastLee : Where did this request come from? From a customer or from us?

**Comment by nfx** [comment]
Closing in favor of https://github.com/databrickslabs/ucx/issues/335
