### ISSUE TITLE
[FEATURE]: Create account groups cli command should be able to create groups with different name then the workspace names.

### ISSUE THREAD

**Issue by FastLee** [databrickslabs/ucx#921]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

It is a common practice to name the workspace groups with the same names for different SDLC stages.
Creating groups with the same names will create a conflict at the account level.

### Proposed Solution

We need to provide renaming options to rename the workspace groups to the account groups. These options is the reverse image of the mapping option.
We should prompt the user for the renaming options.
We should support the following:
1. 1-1 mapping (no renaming).
2.  Add prefix (data-analysts -> dev-data-analysts)
3.  Add Suffix (data-analysts -> data-analysts-dev)
4.  Replace string (data-analysts-users -> data-analysts-group)

Relates to:

- #17

**Comment by nfx** [comment]
@FastLee why do we need this? We don't want customers to have weird setup if they don't have SCIM in place.

**Comment by nfx** [comment]
it doesn't look like we need it. let's reopen if we see the ask.
