### ISSUE TITLE
[BUG]: UCX assessment does not list No-Isolation Shared Clusters

### ISSUE THREAD

**Issue by souravg-db** [databrickslabs/ucx#925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

No-Isolation shared clusters are not compatible with Unity Catalog. During the assessment, No isolation shared clusters should be listed in the assessment summary dashboard which is not happening at the moment

### Expected Behavior

No isolation shared clusters should be listed in the assessment summary dashboard

### Steps To Reproduce

Create a non-isolation shared cluster and run the assessment

### Cloud

Azure

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by nfx** [comment]
Thank you for the feature request! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.
