### ISSUE TITLE
[FEATURE]: Command to re-map cluster type

### ISSUE THREAD

**Issue by chase-edwards-db** [databrickslabs/ucx#928]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

UC migrations require that users move from non-UC to UC cluster types. This is done manually today, which is tedious and requires significant time investment. A migration tool for cluster types would accelerate this component of the migration process.

### Proposed Solution

This feature should:

- Account for clusters and policies
- Map the above to their UC counterparts

### Additional Context

This is a nuanced problem, due to the differences in capability in UC clusters. The tool may require guidance from a field engineering architect, but the tool could suggest changes at a minimum.

**Comment by nfx** [comment]
@chase-edwards-db This can easily be implemented as CLI command. Get an RSA for a few days to do it and we'll guide how

**Comment by chase-edwards-db** [comment]
Appreciate that I didn't get to this until later, saw it came in. Thanks UCX team!
