### ISSUE TITLE
[FEATURE]: List all jobs, not only the incompatible ones

### ISSUE THREAD

**Issue by ebrire-databricks** [databrickslabs/ucx#936]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

A client asked to have all jobs listed in the dashboard, UCX only displays the incompatible ones. They need to deploy UCX to 400+ workspaces and want to avoid making that change manually. Having a full list is a way to keep track of progress.

### Proposed Solution

It only takes an Explode_Outer() instead of an Explode() in the query behind it

**Comment by nfx** [comment]
Thank you for the feature request! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.
