### ISSUE TITLE
[BUG]: Groups in config file not considered for group migration job

### ISSUE THREAD

**Issue by jincejames** [databrickslabs/ucx#941]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you add the groups to be migrated under 'include_group_names' attribute in the config file after the assessment job has been run, and run the group migration job is executed after this change, all the groups that were detected during the assessment job are renamed/migrated instead of only the groups mentioned under 'include_group_names'. 

### Expected Behavior

The group migration workflow should be migrating only the groups mentioned in the config file and not all of the groups detected during the assessment phase.

### Steps To Reproduce

1. Run the assessment job without 'include_group_names' attribute added in the config file.
2. After the assessment job completes, modify the config file to a subset of groups to be migrated using the 'include_group_names' attribute.
3. Run the group migration workflow.
4. Check the groups migrated/renamed -> You will see that all the groups that were detected as part of assessment job are renamed instead of the ones mentioned in the config file.

### Cloud

AWS

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by nfx** [comment]
Thank you for the feature request! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.

We recommend running with all groups by default.
