### ISSUE TITLE
Workspace directory content crawler

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#97]
Given a workspace directory scan for the following:

- [ ] /mnt/*
- [ ] dbfs:/*
- [ ] dbfs:*
- [ ] /dbfs/*
- [ ] /dbfs/mnt/*
- [ ] dbfs*

**Comment by zpappa** [comment]
Wouldn't this include job run results? Files uploaded via CLI?

What is the intention of this step?

**Comment by nfx** [comment]
Duplicate of #391
