### ISSUE TITLE
[BUG]: tacl cluster fails to install the library

### ISSUE THREAD

**Issue by jincejames** [databrickslabs/ucx#975]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

TACL cluster that's used for the crawl tasks for grants and permissions is created as a shared cluster. In DBR 14.3LTS and shared mode access, it fails to install the library mentioned in the cluster policy.
<img width="526" alt="Screenshot 2024-02-22 at 21 51 54" src="https://github.com/databrickslabs/ucx/assets/6622599/0a2a3110-346c-4ce5-a633-621a674c3b7f">

### Expected Behavior

TACL cluster should be run in single user mode so that the library can be installed, or the whl file should be made as dependent library in the corresponding tasks.

### Cloud

AWS

### Operating System

macOS

### Version

latest via Databricks CLI

**Comment by HariGS-DB** [comment]
@jincejames This error is a bit misleading in UI, try running the job and check if you are getting the error

**Comment by jincejames** [comment]
@HariGS-DB Yes I am getting the error while running the job as well. It fails to install the library since the library file is in dbfs. Probably changing this to a workspace file would fix the issue
<img width="845" alt="Screenshot 2024-02-23 at 10 11 35" src="https://github.com/databrickslabs/ucx/assets/6622599/d9c95dd4-322d-496c-9da0-71adc3f28b2f">

**Comment by jincejames** [comment]
Also is there a specific reason why it should be a shared cluster instead of a single user ?

**Comment by nfx** [comment]
It should be a legacy table acl cluster

**Comment by larsgeorge-db** [comment]
@jincejames here is an example of what the installer creates for the `tacl` cluster:

![image](https://github.com/databrickslabs/ucx/assets/136075433/3ec982f9-9d4c-405b-882d-017beef7ddf6)

This is set up here https://github.com/databrickslabs/ucx/blob/main/src/databricks/labs/ucx/install.py#L795-L821

I assume there was something done that caused it to use a different mode?

**Comment by nfx** [comment]
@jincejames is this issue still relevant? It seems that there were errors in your setup
